import type { Question } from './questions';

export const ECONOMY_TERM_QUESTIONS: Question[] = [
  {
    id: "term-soliditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara soliditet med egna ord.",
    tags: ["Ekonomi", "AM5", "Nyckeltal"],
    answer: "Soliditet visar hur stor del av företagets tillgångar som är finansierade med eget kapital. Formel: eget kapital / totala tillgångar. Det mäter långsiktig finansiell motståndskraft — inte kortsiktig betalningsförmåga.",
    why: "Måttet säger något om hur mycket buffert bolaget har vid förlust eller sämre tider. AM5: bra soliditet är ofta över 30–40 %.",
    example: "Essiq AB rapporterade cirka 28 % soliditet 2021, medan Hälsö Fisk AB hade 11 % 2017.",
    related: ["Eget kapital", "Balansräkning", "Likviditet"]
  },
  {
    id: "term-likviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder likviditet?",
    tags: ["Ekonomi", "AM5", "Nyckeltal"],
    answer: "Likviditet betyder kortsiktig betalningsförmåga — om företaget kan betala sina löpande skulder i tid. Det handlar om pengar och likvida medel, inte om vinst.",
    why: "Ett företag kan visa vinst men ändå få likviditetsproblem om pengarna sitter i kundfordringar eller lager.",
    example: "Essiq AB hade bättre balanslikviditet än Hälsö Fisk AB, men mycket av betalningsförmågan kunde ligga i fordringar.",
    related: ["Kassalikviditet", "Balanslikviditet", "Kassaflöde"]
  },
  {
    id: "term-kassalikviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara kassalikviditet.",
    tags: ["Ekonomi", "AM5", "Formel"],
    answer: "Kassalikviditet = (omsättningstillgångar − lager och pågående arbeten) / kortfristiga skulder. Måttet visar om korta skulder kan betalas utan att sälja lager.",
    why: "Striktare än balanslikviditet eftersom lager inte räknas som direkt betalningsbar tillgång.",
    example: "Hälsö Fisk AB låg runt 80 % i kassalikviditet utifrån 2017 års balansräkning.",
    related: ["Likviditet", "Balanslikviditet", "Lager"]
  },
  {
    id: "term-balanslikviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter balanslikviditet?",
    tags: ["Ekonomi", "AM5", "Formel"],
    answer: "Balanslikviditet = omsättningstillgångar / kortfristiga skulder. Det ger en bred bild av kortsiktig betalningsförmåga. AM5: bra likviditet är ofta över 100 %.",
    why: "Säger inte om tillgångarna redan finns som pengar på banken — därför kompletteras det ofta med kassalikviditet.",
    example: "Essiq AB hade cirka 144 % i balanslikviditet 2021.",
    related: ["Omsättningstillgångar", "Likviditet", "Kassalikviditet"]
  },
  {
    id: "term-resultatrakning",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en resultaträkning?",
    tags: ["Ekonomi", "AM5", "RR"],
    answer: "Resultaträkningen (RR) visar intäkter minus kostnader under en period och leder fram till årets resultat. Den gäller en tidsperiod, inte en enskild dag.",
    why: "Den visar om affären går med vinst eller förlust — inte hur bolaget är finansierat vid en tidpunkt.",
    example: "Essiq AB hade 2021 ett resultat efter finansiella poster på 11 305 793 kr.",
    related: ["Nettoomsättning", "Kostnader", "Årets resultat"]
  },
  {
    id: "term-balansrakning",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en balansräkning?",
    tags: ["Ekonomi", "AM5", "BR"],
    answer: "Balansräkningen (BR) visar tillgångar, skulder och eget kapital vid en viss tidpunkt. Tillgångar − skulder = eget kapital.",
    why: "Den visar hur bolaget är finansierat och hur stor del av tillgångarna som är bundna i skulder eller eget kapital.",
    example: "Hälsö Fisk AB hade 1 184 841 kr i tillgångar och 130 528 kr i eget kapital 2017.",
    related: ["Tillgångar", "Skulder", "Soliditet"]
  },
  {
    id: "term-eget-kapital",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är eget kapital?",
    tags: ["Ekonomi", "AM5"],
    answer: "Eget kapital är tillgångar minus skulder — ägarnas kapital i bolaget. Det fungerar som buffert och är grunden för soliditeten.",
    why: "Inte samma sak som pengar på banken eller hela omsättningen.",
    example: "Essiq AB hade 10 468 395 kr i eget kapital 2021.",
    related: ["Soliditet", "Balansräkning", "Bundet eget kapital"]
  },
  {
    id: "term-kassaflode",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder kassaflöde?",
    tags: ["Ekonomi", "AM5"],
    answer: "Kassaflöde är pengar som kommer in och går ut ur företaget över tid. Det visar faktiska in- och utbetalningar, inte bokfört resultat.",
    why: "Kassaflödet avgör om bolaget kan betala löner och leverantörer även när resultatet ser bra ut.",
    example: "Essiq AB:s likvida medel minskade kraftigt under 2021 trots positivt resultat.",
    related: ["Likviditet", "Resultat", "Kundfordringar"]
  },
  {
    id: "term-tackningsbidrag",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5/AM6",
    question: "Vad är täckningsbidrag?",
    tags: ["Ekonomi", "Projektekonomi", "TB"],
    answer: "Täckningsbidrag (TB) = försäljningsintäkt minus direkta (rörliga) kostnader för en tjänst eller ett projekt. TB i % kallas täckningsgrad (TG).",
    why: "Det visar hur mycket ett projekt bidrar till fasta kostnader och vinst — inte hela intäkten är vinst.",
    example: "Ett projekt som säljs för 180 000 kr med 105 000 kr i direkta kostnader ger 75 000 kr i täckningsbidrag.",
    related: ["Intäkter", "Direkta kostnader", "Lönsamhet"]
  },
  {
    id: "term-budget-prognos",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är skillnaden mellan budget och prognos?",
    tags: ["Ekonomi", "AM5", "Styrning"],
    answer: "Budget är planen i förväg — intäkter och kostnader man siktar på. Prognos är en uppdaterad bedömning av hur utfallet verkar bli när verkligheten förändras.",
    why: "Skillnaden hjälper bolaget styra både mål och verklighet när beläggning eller intäkter ändras.",
    example: "Ett konsultbolag budgeterar 80 % beläggning men justerar prognosen när uppdrag försenas.",
    related: ["Likviditetsbudget", "Resultatbudget", "Uppföljning"]
  },
  {
    id: "term-debiteringsgrad",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5/AM6",
    question: "Vad betyder debiteringsgrad?",
    tags: ["Ekonomi", "Konsult"],
    answer: "Debiteringsgrad visar hur stor del av arbetstiden som kan faktureras till kund. Hög debiteringsgrad ger fler intäkter; låg beläggning pressar lönsamheten.",
    why: "I konsultbolag påverkar debiteringsgrad direkt intäkter och lönsamhet — det är en av de mest kritiska variablerna.",
    example: "Om en konsult arbetar 160 timmar men bara 120 faktureras blir debiteringsgraden 75 %.",
    related: ["Snittdebitering", "Beläggning", "Lönsamhet"]
  },
  {
    id: "term-snittdebitering",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder snittdebitering?",
    tags: ["Ekonomi", "Konsult"],
    answer: "Snittdebitering är genomsnittligt fakturerat pris per timme eller konsultinsats. Det visar om bolaget säljer sin kompetens till en nivå som täcker kostnader.",
    why: "Hög beläggning med för låg timtaxa kan fortfarande ge svag lönsamhet.",
    example: "Debiteringsgraden kan vara hög men snittdebiteringen för låg för att täcka overhead.",
    related: ["Debiteringsgrad", "Timpris", "Täckningsbidrag"]
  },
  {
    id: "term-arsredovisning",
    mode: "begrepp",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vad är en årsredovisning?",
    tags: ["Årsredovisning", "AM5"],
    answer: "En årsredovisning är ett paket med förvaltningsberättelse, resultaträkning, balansräkning, noter och ofta revisionsberättelse. Den ger flera perspektiv på bolagets ekonomi och verksamhet.",
    why: "Den gör det möjligt att läsa siffror och sammanhang tillsammans — inte bara en enskild nyckeltal.",
    example: "AM5 använder Hälsö Fisk AB och Essiq AB som exempel på hur olika bolag kan läsas.",
    related: ["Förvaltningsberättelse", "Resultaträkning", "Balansräkning"]
  },
  {
    id: "term-forvaltningsberattelse",
    mode: "begrepp",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Varför ska man läsa förvaltningsberättelsen?",
    tags: ["Årsredovisning", "AM5"],
    answer: "Förvaltningsberättelsen beskriver vad som hänt i verksamheten under året — marknad, händelser och framtidsutsikter. Den förklarar varför siffrorna ser ut som de gör.",
    why: "Nyckeltal visar vad som hänt; förvaltningsberättelsen visar varför.",
    example: "Hälsö Fisk AB beskriver färre kundbesök och pressad försäljning på grund av infrastrukturförändringar i Kungälv.",
    related: ["Årsredovisning", "Resultat", "Omvärld"]
  },
  {
    id: "term-likviditet-soliditet-samband",
    mode: "samband",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur hänger likviditet och soliditet ihop?",
    tags: ["Samband", "Ekonomi"],
    answer: "Likviditet handlar om kortsiktig betalningsförmåga; soliditet om långsiktig finansiell motståndskraft (eget kapital i relation till tillgångar). Ett bolag kan ha god soliditet men svag likviditet om pengarna är bundna i tillgångar.",
    why: "Båda måste läsas — de mäter olika tidshorisonter och risker.",
    example: "Essiq AB hade bättre balanslikviditet än Hälsö Fisk AB, men soliditeten behöver ändå bedömas separat.",
    related: ["Likviditet", "Soliditet", "Balansräkning"]
  },
  {
    id: "term-resultat-kassaflode-samband",
    mode: "samband",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Varför är resultat och kassaflöde inte samma sak?",
    tags: ["Samband", "Ekonomi"],
    answer: "Resultat visar intäkter minus kostnader enligt redovisningen (ofta vid fakturering). Kassaflöde visar faktiska pengar in och ut. Försäljning kan bokföras som intäkt innan betalning kommit in.",
    why: "Det förklarar varför ett bolag kan visa vinst men ändå ha akuta likviditetsproblem.",
    example: "Essiq AB gjorde positivt resultat men hade kraftigt minskade likvida medel under 2021.",
    related: ["Resultaträkning", "Kassaflöde", "Kundfordringar"]
  },
  {
    id: "mc-soliditet-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter soliditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Hur stor del av tillgångarna som finansieras med kortfristiga skulder",
      "Företagets kortsiktiga betalningsförmåga",
      "Hur stor del av tillgångarna som är finansierade med eget kapital",
      "Skillnaden mellan intäkter och kostnader under en period"
    ],
    correctIndex: 2,
    explanation: "Soliditet = eget kapital / totala tillgångar. Alternativ B beskriver likviditet. Alternativ D beskriver resultat.",
    related: ["Eget kapital", "Balansräkning", "Likviditet"]
  },
  {
    id: "mc-likviditet-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad beskriver likviditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Hur stor andel av tillgångarna som ägs av ägarna",
      "Företagets kortsiktiga betalningsförmåga",
      "Hur lönsamt företaget är på lång sikt",
      "Hur mycket utdelning ägarna kan ta ut"
    ],
    correctIndex: 1,
    explanation: "Likviditet handlar om att kunna betala löpande skulder i tid. Alternativ A beskriver soliditet.",
    related: ["Kassalikviditet", "Balanslikviditet", "Soliditet"]
  },
  {
    id: "mc-kassalikviditet-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur beräknas kassalikviditet?",
    tags: ["Ekonomi", "AM5", "Formel"],
    options: [
      "Omsättningstillgångar / kortfristiga skulder",
      "Eget kapital / totala tillgångar",
      "(Omsättningstillgångar − lager) / kortfristiga skulder",
      "Kassa och bank / långfristiga skulder"
    ],
    correctIndex: 2,
    explanation: "Kassalikviditet exkluderar lagret. Alternativ A är balanslikviditet.",
    related: ["Balanslikviditet", "Likviditet", "Lager"]
  },
  {
    id: "mc-balanslikviditet-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vilken formel beskriver balanslikviditet?",
    tags: ["Ekonomi", "AM5", "Formel"],
    options: [
      "Omsättningstillgångar / kortfristiga skulder",
      "(Omsättningstillgångar − lager) / kortfristiga skulder",
      "Totala tillgångar / totala skulder",
      "Eget kapital / omsättningstillgångar"
    ],
    correctIndex: 0,
    explanation: "Balanslikviditet inkluderar alla omsättningstillgångar. Alternativ B är kassalikviditet.",
    related: ["Kassalikviditet", "Omsättningstillgångar"]
  },
  {
    id: "mc-resultat-vs-balans",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en resultaträkning som en balansräkning inte visar?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Företagets tillgångar vid en viss tidpunkt",
      "Skulder och eget kapital vid årets slut",
      "Intäkter minus kostnader under en tidsperiod",
      "Hur mycket kassa företaget har just nu"
    ],
    correctIndex: 2,
    explanation: "Resultaträkningen visar flöde under en period. Balansräkningen visar ögonblicksbilden.",
    related: ["Resultaträkning", "Balansräkning"]
  },
  {
    id: "mc-eget-kapital-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur definieras eget kapital?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Pengar som finns på företagets bankkonto",
      "Totala intäkter minus totala kostnader",
      "Tillgångar minus skulder",
      "Aktiekapital plus långfristiga lån"
    ],
    correctIndex: 2,
    explanation: "Eget kapital = tillgångar − skulder. Alternativ B beskriver resultat.",
    related: ["Soliditet", "Balansräkning"]
  },
  {
    id: "mc-kassaflode-vs-resultat",
    mode: "samband",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Varför kan ett företag visa vinst men ändå ha dåligt kassaflöde?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Intäkter bokförs när fakturan skickas, men pengarna kanske inte kommit in ännu",
      "Vinst och kassaflöde är alltid samma sak i redovisningen",
      "Kassaflödet räknar bara fasta kostnader",
      "Resultaträkningen visar bara kassa och bank"
    ],
    correctIndex: 0,
    explanation: "Kundfordringar och timing gör att resultat och kassa skiljer sig. Essiq AB 2021 är ett tydligt exempel.",
    related: ["Kassaflöde", "Resultat", "Kundfordringar"]
  },
  {
    id: "mc-tackningsbidrag-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur beräknas täckningsbidrag?",
    tags: ["Ekonomi", "Projektekonomi"],
    options: [
      "Intäkter minus alla kostnader inklusive fasta",
      "Nettoomsättning minus skatt",
      "Försäljningsintäkt minus direkta kostnader",
      "Eget kapital minus skulder"
    ],
    correctIndex: 2,
    explanation: "TB = intäkt − direkta kostnader. Fasta kostnader täcks av TB över tid.",
    related: ["Intäkter", "Direkta kostnader", "Lönsamhet"]
  },
  {
    id: "mc-debiteringsgrad-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter debiteringsgrad i ett konsultbolag?",
    tags: ["Ekonomi", "Konsult"],
    options: [
      "Andelen av omsättningen som går till löner",
      "Andelen av arbetstiden som kan faktureras till kund",
      "Genomsnittligt pris per timme",
      "Andelen av vinsten som delas ut till ägarna"
    ],
    correctIndex: 1,
    explanation: "Debiteringsgrad = fakturerbar tid / total arbetstid. Alternativ C är snittdebitering.",
    related: ["Snittdebitering", "Beläggning"]
  },
  {
    id: "mc-budget-vs-prognos",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är huvudskillnaden mellan budget och prognos?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Budget görs efter räkenskapsåret, prognos görs före",
      "Budget är planen i förväg, prognos är en uppdaterad bedömning av utfallet",
      "Budget används bara i aktiebolag, prognos i enskild firma",
      "Budget visar intäkter, prognos visar kostnader"
    ],
    correctIndex: 1,
    explanation: "Budget = plan. Prognos = justerad bedömning under perioden.",
    related: ["Uppföljning", "Likviditetsbudget"]
  },
  {
    id: "mc-arsredovisning-delar",
    mode: "begrepp",
    type: "mc",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vilka delar ingår i en årsredovisning?",
    tags: ["Årsredovisning", "AM5"],
    options: [
      "Bara resultaträkning och balansräkning",
      "Förvaltningsberättelse, resultaträkning, balansräkning, noter och ofta revisionsberättelse",
      "Bara budget och prognos",
      "SWOT-analys och konkurrentanalys"
    ],
    correctIndex: 1,
    explanation: "Årsredovisningen är ett komplett paket med flera perspektiv.",
    related: ["Förvaltningsberättelse", "Resultaträkning"]
  },
  {
    id: "mc-forvaltningsberattelse-syfte",
    mode: "begrepp",
    type: "mc",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vad är syftet med förvaltningsberättelsen?",
    tags: ["Årsredovisning", "AM5"],
    options: [
      "Att lista alla anställdas löner",
      "Att beskriva vad som hänt i verksamheten under året och ge kontext till siffrorna",
      "Att visa företagets soliditet och likviditet i diagramform",
      "Att presentera nästa års budget"
    ],
    correctIndex: 1,
    explanation: "Förvaltningsberättelsen förklarar varför siffrorna ser ut som de gör.",
    related: ["Årsredovisning", "Resultat"]
  },
  {
    id: "mc-tf-resultat-kassaflode",
    mode: "samband",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Positivt resultat betyder alltid bra kassaflöde.\"",
    tags: ["Ekonomi", "AM5", "Sant/Falskt"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. Resultat baseras på bokföring; kassaflöde visar faktiska pengar in och ut.",
    related: ["Kassaflöde", "Resultat"]
  },
  {
    id: "mc-tf-soliditet-kortsiktig",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Soliditet visar kortsiktig betalningsförmåga.\"",
    tags: ["Ekonomi", "AM5", "Sant/Falskt"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. Soliditet = långsiktig styrka. Likviditet = kortsiktig betalningsförmåga.",
    related: ["Soliditet", "Likviditet"]
  },
  {
    id: "mc-tf-eget-kapital",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Eget kapital = tillgångar minus skulder.\"",
    tags: ["Ekonomi", "AM5", "Sant/Falskt"],
    options: ["Sant", "Falskt"],
    correctIndex: 0,
    explanation: "Sant. Eget kapital är ägarnas andel — inte samma sak som pengar på banken.",
    related: ["Eget kapital", "Soliditet"]
  },
  {
    id: "term-affarsmannaskap",
    mode: "begrepp",
    type: "open",
    category: "Affärsmannaskap",
    source: "AM1",
    question: "Förklara affärsmannaskap med egna ord. Hur skiljer det sig från att bara sälja?",
    tags: ["Affärsmannaskap", "Kundnytta", "Beslut"],
    answer: "Affärsmannaskap är förmågan att förstå kundens problem, analysera marknad och ekonomi, och fatta affärsmässiga beslut som skapar långsiktigt värde för både kund och bolag. Det skiljer sig från att bara sälja genom att fokus ligger på rätt lösning, risk, lönsamhet och relation — inte bara att stänga en order.",
    why: "Tentan testar om du kan koppla kundnytta, analys och ekonomi till ett genomtänkt beslut.",
    example: "En konsult säljer inte '100 timmar M365' utan en avgränsad förstudie som minskar kundens manuella administration och som bolaget kan leverera lönsamt.",
    related: ["Kundnytta", "Lönsamhet", "Analys"]
  },
  {
    id: "term-funktion-kundvarde",
    mode: "begrepp",
    type: "open",
    category: "Kund & värde",
    source: "AM2",
    question: "Vad är skillnaden mellan en funktion och kundvärde?",
    tags: ["Funktion", "Kundvärde", "FAB"],
    answer: "En funktion beskriver vad produkten eller tjänsten kan göra tekniskt. Kundvärde beskriver vilken nytta kunden faktiskt får — sparad tid, lägre kostnad, färre fel eller bättre beslut. Kunden köper sällan funktionen i sig utan värdet den skapar.",
    why: "Utan denna skillnad fastnar sälj och facit i tekniska listor som kunden inte förstår.",
    example: "Power Automate är en funktion. Kundvärdet är att ärenden dirigeras rätt direkt och personalen slipper dubbelregistrering.",
    related: ["FAB", "Feature", "Benefit"]
  },
  {
    id: "term-fab-5p",
    mode: "begrepp",
    type: "open",
    category: "Kund & värde",
    source: "AM2",
    question: "Nämn delarna i FAB och 5P och ge ett kort exempel.",
    tags: ["FAB", "5P", "Marknadsföring"],
    answer: "FAB = Feature (egenskap), Advantage (fördel), Benefit (kundnytta). 5P = Product, Price, Place, Promotion, People — produkt, pris, distributionskanal, marknadsföring och människor som levererar upplevelsen. Exempel: molnlagring (Feature) ger åtkomst överallt (Advantage) och snabbare samarbete (Benefit).",
    why: "Båda modellerna hjälper dig översätta erbjudande till något kunden kan bedöma och köpa.",
    example: "SharePoint-mall (Product) säljs till fast pris (Price) via referenskunder (Place) med case-webinar (Promotion) och erfarna konsulter (People).",
    related: ["FAB", "5P", "Kundnytta"]
  },
  {
    id: "term-juridisk-person",
    mode: "begrepp",
    type: "open",
    category: "Företagsform",
    source: "AM4",
    question: "Vad betyder juridisk person och varför spelar det roll?",
    tags: ["Juridisk person", "Företagsform", "Ansvar"],
    answer: "Juridisk person är en organisation som kan äga tillgångar, ingå avtal och bära ansvar i eget namn — skild från ägarna som fysiska personer. Det spelar roll för ansvar, trovärdighet, skatt och hur kunder och myndigheter ser bolaget.",
    why: "Företagsformsfrågor på tentan handlar ofta om ansvar och trovärdighet, inte bara bolagsformens namn.",
    example: "Ett AB är juridisk person med i regel begränsat ägaransvar, medan en enskild firma ofta innebär att ägaren och verksamheten hänger närmare ihop juridiskt.",
    related: ["AB", "Enskild firma", "Ansvar"]
  },
  {
    id: "term-vision-mission-affarside",
    mode: "samband",
    type: "open",
    category: "Företagsplattform",
    source: "AM1",
    question: "Vad är skillnaden mellan vision, mission och affärsidé?",
    tags: ["Vision", "Mission", "Affärsidé"],
    answer: "Visionen beskriver vart bolaget vill — framtidsbilden. Missionen beskriver vad bolaget gör och för vem idag — uppdraget. Affärsidén är den korta kärnan i verksamheten: vilket problem som löses och för vilken kund, ofta i en mening.",
    why: "Tentan testar om du kan skilja riktning (vision), uppdrag (mission) och kärnerbjudande (affärsidé).",
    example: "Vision: smart digitalisering för mindre organisationer. Mission: minska manuell administration. Affärsidé: praktisk M365-automation för dokumenttunga verksamheter.",
    related: ["Värderingar", "Företagsplattform", "Strategi"]
  },
  {
    id: "term-resultatposter",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är skillnaden mellan nettoomsättning, rörelseresultat och årets resultat?",
    tags: ["Resultaträkning", "AM5", "RR"],
    answer: "Nettoomsättning är intäkter från försäljning minus rabatter och returer. Rörelseresultat är omsättning minus rörelsekostnader — hur kärnverksamheten går. Årets resultat är slutraden efter finansiella poster och skatt — bolagets totala vinst eller förlust under perioden.",
    why: "Olika rader i RR svarar på olika frågor: försäljning, drift och slutresultat.",
    example: "Essiq AB kan ha hög omsättning men lägre rörelseresultat om kostnaderna växer, och årets resultat påverkas ytterligare av räntor och skatt.",
    related: ["Resultaträkning", "Kostnader", "Årets resultat"]
  },
  {
    id: "term-avtalstyper",
    mode: "samband",
    type: "open",
    category: "Avtal",
    source: "AM6",
    question: "Vad är skillnaden mellan ramavtal, avrop, avtal och Letter of Intent?",
    tags: ["Avtal", "Ramavtal", "LOI"],
    answer: "Ramavtal reglerar övergripande villkor för ett längre samarbete. Avrop är en konkret beställning under ramavtalet. Avtal (enskilt) reglerar en specifik leverans eller ett tillfälle. Letter of Intent (LOI) är en avsiktsförklaring — visar vilja att samarbeta men är inte samma sak som ett färdigt leveransavtal.",
    why: "IT-projekt kräver att du vet vilket dokument som faktiskt styr scope, pris och ansvar.",
    example: "Kommunen har ramavtal med IT-leverantörer. Varje ny implementation görs som avrop med eget scope och pris. En LOI inför pilot får inte ersätta uppdragsavtalet.",
    related: ["Scope", "Uppdragsavtal", "Offentlig sektor"]
  },
  {
    id: "term-offentlig-upphandling",
    mode: "begrepp",
    type: "open",
    category: "Upphandling",
    source: "AM7",
    question: "Vad är offentlig upphandling och varför skiljer den sig från en privat offertdialog?",
    tags: ["Upphandling", "LOU", "Offentlig sektor"],
    answer: "Offentlig upphandling är reglerad inköpsprocess för myndigheter och vissa offentligt styrda organ enligt LOU. Den skiljer sig från privat offertdialog genom formella krav, kriterier, offentlighet, dokumentation och möjlighet till överprövning — relation räcker inte som enda grund.",
    why: "Leverantören måste förstå reglerna för att kunna bedöma om ett anbud är lönsamt och korrekt.",
    example: "En kommun publicerar upphandling i Opic/TendSign med skallkrav och utvärderingsmodell — inte bara ett informellt möte och muntlig offert.",
    related: ["LOU", "Anbud", "Skallkrav"]
  },
  {
    id: "term-plan-dokument-samband",
    mode: "samband",
    type: "open",
    category: "Affärsplan",
    source: "AM7/AM9",
    question: "Vad är skillnaden mellan affärsplan, marknadsplan och roadmap?",
    tags: ["Affärsplan", "Marknadsplan", "Roadmap"],
    answer: "Affärsplanen är helheten: kund, marknad, erbjudande, analys, ekonomi, resurser och aktiviteter. Marknadsplanen fokuserar på hur marknaden bearbetas — målgrupp, budskap, kanaler och aktiviteter. Roadmapen är en förenklad, tidsatt kommunikationsbild av riktning och prioriterade steg — inte en full affärsplan.",
    why: "Tentafällan är att blanda ihop dokumenten eller göra roadmap till en komplett affärsplan.",
    example: "Affärsplanen visar varför bolaget satsar på offentlig sektor. Marknadsplanen väljer webinar och referenser. Roadmapen visar Q1 pilot, Q2 paketering, Q3 upphandlingsförberedelse.",
    related: ["Scenarier", "Mål", "Prioritering"]
  },
  {
    id: "term-scenarioplanering-steg",
    mode: "begrepp",
    type: "open",
    category: "Scenario",
    source: "AM9",
    question: "Vilka tre steg ingår i scenarioplanering med handlingsplan?",
    tags: ["Scenario", "Handlingsplan", "AM9"],
    answer: "1) Scenarioanalys — måla upp relevanta framtider (t.ex. optimistiskt, realistiskt, pessimistiskt). 2) Effektanalys — hur varje scenario påverkar kunder, organisation, drift och finansiering. 3) Handlingsplaner — aktiviteter med ansvarig, datum, förväntad effekt och uppföljning.",
    why: "Scenarier ska leda till beslut och åtgärder — inte bara vara tre rubriker utan mätetal.",
    example: "Pessimistiskt scenario med 45 % debiteringsgrad → handlingsplan: ring tio befintliga kunder, ansvarig KAM, deadline fredag, mål tre behovsmöten.",
    related: ["Budget", "Prognos", "KPI"]
  },
  {
    id: "term-marknadsforing-grund",
    mode: "begrepp",
    type: "open",
    category: "Marknadsföring",
    source: "AM9",
    question: "Vad bygger marknadsföring på enligt kursen?",
    tags: ["Marknadsföring", "Strategi", "Positionering"],
    answer: "Marknadsföring bygger på strategi kring erbjudande, målgrupp, differentiering och positionering — inte bara på enskilda aktiviteter eller reklam. Den vilar på varumärkeslöfte, paketering och tydlig koppling till vad kunden ska förstå och köpa.",
    why: "Marknadsföring utan målgrupp och budskap blir bara en aktivitetslista.",
    example: "Ett M365-bolag marknadsför inte 'IT' utan 'mindre manuell administration' till verksamhetschefer via referenscase och webinar.",
    related: ["Marknadsplan", "Differentiering", "Målgrupp"]
  },
  {
    id: "term-marknadsforingslagen",
    mode: "begrepp",
    type: "open",
    category: "Marknadsföring",
    source: "AM9",
    question: "Vad betyder det att marknadsföring ska vara tydlig och inte vilseledande?",
    tags: ["Marknadsföringslagen", "Etik", "Trovärdighet"],
    answer: "Marknadsföring ska tydligt framgå som marknadsföring och vem som står bakom den. Påståenden, priser, gratiserbjudanden och jämförelser får inte vilseleda kunden. Lagen gäller före, under och efter försäljning — inte bara i annonser.",
    why: "Trovärdighet och juridisk risk hänger ihop, särskilt vid effektpåståenden och sponsrat innehåll.",
    example: "Bolaget ska inte lova '50 % besparing' utan baseline, och sponsrat webinar ska märkas som marknadsföring.",
    related: ["Trovärdighet", "Kundnytta", "REBR"]
  },
  {
    id: "term-behovsfragor",
    mode: "begrepp",
    type: "open",
    category: "Sälj",
    source: "AM10",
    question: "Vad är skillnaden mellan öppna, slutna, alternativ- och acceptansfrågor?",
    tags: ["Behovsanalys", "Frågeteknik", "Sälj"],
    answer: "Öppna frågor samlar information (hur, vad, varför). Slutna/ledande frågor bekräftar det du tror (ja/nej). Alternativfrågor får kunden välja mellan vägar. Acceptansfrågor binder delaccepterande: om vi löser X, går vi vidare?",
    why: "Balansen mellan frågetyper avgör om behovsanalysen blir dialog eller förhör.",
    example: "Öppen: 'Hur hanterar ni ärenden idag?' Acceptans: 'Om vi halverar handläggningstiden, är ni öppna för en pilot?'",
    related: ["SPIN", "Säljsamtal", "Aktivt lyssnande"]
  },
  {
    id: "term-spin",
    mode: "begrepp",
    type: "open",
    category: "Sälj",
    source: "AM10",
    question: "Vad står S, P, I och N för i SPIN?",
    tags: ["SPIN", "Behovsanalys", "Sälj"],
    answer: "S = Situation (nuläge), P = Problem (svårigheter), I = Inverkan (konsekvenser av problemet), N = Nytta (värdet av en lösning). Modellen bygger behov steg för steg innan lösningen presenteras.",
    why: "SPIN hjälper konsulten sälja utifrån kundens problem, inte produktlistan.",
    example: "Situation: CRM-flöde idag. Problem: dubbelregistrering. Inverkan: fler fel och stress. Nytta: ett sammanhållet flöde.",
    related: ["Behovsanalys", "Lösningsförslag", "Kundvärde"]
  },
  {
    id: "term-rfi-rfp-rfq",
    mode: "samband",
    type: "open",
    category: "Upphandling",
    source: "AM7",
    question: "Vad är skillnaden mellan RFI, RFP och RFQ?",
    tags: ["RFI", "RFP", "RFQ", "Upphandling"],
    answer: "RFI (Request for Information) samlar marknadsinformation innan större beslut. RFP (Request for Proposal) ber om lösningsförslag och offert på projekt eller tjänst. RFQ (Request for Quotation) används när behovet är tydligare och kunden vill jämföra pris och villkor.",
    why: "Fel svarstyp vid fel förfrågan gör att leverantören missar vad kunden faktiskt utvärderar.",
    example: "RFI: beskriv M365-möjligheter. RFP: föreslå införandeplan och riskhantering. RFQ: pris per användare och leveranstid.",
    related: ["Offentlig upphandling", "Anbud", "Köpmognad"]
  },
  {
    id: "mc-funktion-kundvarde",
    mode: "begrepp",
    type: "mc",
    category: "Kund & värde",
    source: "AM2",
    question: "Vad är kundvärde?",
    tags: ["Kundvärde", "FAB"],
    options: [
      "En teknisk funktion i produkten",
      "Nyttan kunden faktiskt får av lösningen",
      "Priset per timme",
      "Antalet anställda i leverantörsbolaget"
    ],
    correctIndex: 1,
    explanation: "Kundvärde = konkret nytta. Funktionen är bara medlet.",
    related: ["FAB", "Benefit"]
  },
  {
    id: "mc-fab-delar",
    mode: "begrepp",
    type: "mc",
    category: "Kund & värde",
    source: "AM2",
    question: "Vad står B för i FAB?",
    tags: ["FAB", "Sälj"],
    options: ["Budget", "Benefit (kundnytta)", "Balansräkning", "Business Model Canvas"],
    correctIndex: 1,
    explanation: "FAB = Feature, Advantage, Benefit. B är kundnyttan.",
    related: ["Feature", "Advantage"]
  },
  {
    id: "mc-juridisk-person",
    mode: "begrepp",
    type: "mc",
    category: "Företagsform",
    source: "AM4",
    question: "Vad innebär juridisk person?",
    tags: ["Företagsform", "Ansvar"],
    options: [
      "Att ägaren alltid är privatperson",
      "Att organisationen kan ingå avtal och bära ansvar i eget namn",
      "Att bolaget inte behöver betala skatt",
      "Att endast statliga myndigheter kan vara kunder"
    ],
    correctIndex: 1,
    explanation: "Juridisk person = organisation med egen rättskapacitet, skild från ägarna.",
    related: ["AB", "Avtal"]
  },
  {
    id: "mc-resultatposter",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar rörelseresultatet?",
    tags: ["Resultaträkning", "RR"],
    options: [
      "Intäkter minus rörelsekostnader",
      "Tillgångar minus skulder",
      "Kassaflöde under perioden",
      "Eget kapital vid årets slut"
    ],
    correctIndex: 0,
    explanation: "Rörelseresultat = kärnverksamhetens resultat före finansiella poster.",
    related: ["Nettoomsättning", "Årets resultat"]
  },
  {
    id: "mc-avtalstyper",
    mode: "samband",
    type: "mc",
    category: "Avtal",
    source: "AM6",
    question: "Vad är en Letter of Intent (LOI)?",
    tags: ["Avtal", "LOI"],
    options: [
      "Ett färdigt leveransavtal med bindande scope",
      "En avsiktsförklaring inför möjligt samarbete",
      "Samma sak som ett ramavtal",
      "Ett GDPR-avtal för personuppgifter"
    ],
    correctIndex: 1,
    explanation: "LOI visar vilja att samarbeta men ersätter inte leveransavtal.",
    related: ["Ramavtal", "Uppdragsavtal"]
  },
  {
    id: "mc-plan-dokument",
    mode: "samband",
    type: "mc",
    category: "Affärsplan",
    source: "AM7",
    question: "Vad är huvudsyftet med en roadmap?",
    tags: ["Roadmap", "Affärsplan"],
    options: [
      "Ersätta hela affärsplanen med alla ekonomiska detaljer",
      "Visa prioriterade steg och tidsordning som kommunikationsbild",
      "Reglera personuppgiftsbehandling",
      "Beräkna soliditet och likviditet"
    ],
    correctIndex: 1,
    explanation: "Roadmap = förenklad, tidsatt riktning — inte full affärsplan.",
    related: ["Affärsplan", "Marknadsplan"]
  },
  {
    id: "mc-rfi-rfp-rfq",
    mode: "samband",
    type: "mc",
    category: "Upphandling",
    source: "AM7",
    question: "När passar RFQ bäst?",
    tags: ["RFQ", "Upphandling"],
    options: [
      "När kunden bara vill utforska marknaden",
      "När behovet är tydligt och kunden vill jämföra pris och villkor",
      "När kunden saknar budget",
      "När inget avtal ska skrivas"
    ],
    correctIndex: 1,
    explanation: "RFQ = tydligare behov, fokus på jämförbar prissättning.",
    related: ["RFI", "RFP"]
  },
  {
    id: "mc-spin-delar",
    mode: "begrepp",
    type: "mc",
    category: "Sälj",
    source: "AM10",
    question: "Vad står I för i SPIN?",
    tags: ["SPIN", "Behovsanalys"],
    options: ["Investering", "Inverkan (konsekvenser av problemet)", "Integration", "Intäkt"],
    correctIndex: 1,
    explanation: "I = Inverkan — vad problemet kostar eller skadar.",
    related: ["Problem", "Nytta"]
  },
  {
    id: "mc-behovsfragor",
    mode: "begrepp",
    type: "mc",
    category: "Sälj",
    source: "AM10",
    question: "Vilken frågetyp samlar mest ny information om kundens situation?",
    tags: ["Behovsanalys", "Frågeteknik"],
    options: ["Slutna ja/nej-frågor", "Öppna frågor", "Acceptansfrågor", "Alternativfrågor"],
    correctIndex: 1,
    explanation: "Öppna frågor (hur, vad, varför) öppnar dialogen.",
    related: ["SPIN", "Säljsamtal"]
  },
  {
    id: "mc-tf-marknadsforingslagen",
    mode: "begrepp",
    type: "mc",
    category: "Marknadsföring",
    source: "AM9",
    question: "Påstående: \"Marknadsföringslagen gäller bara i reklamannonser.\"",
    tags: ["Marknadsföringslagen", "Sant/Falskt"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. Lagen omfattar marknadsföring före, under och efter försäljning.",
    related: ["Trovärdighet", "Etik"]
  }
];