export interface Question {
  id: string;
  mode: 'resonemang' | 'case' | 'examinatorrisk' | 'repetition';
  type: 'open' | 'mc';
  category: string;
  source: string;
  question: string;
  tags: string[];
  answer?: string;
  why?: string;
  example?: string;
  related?: string[];
  options?: string[];
  correctIndex?: number;
  explanation?: string;
}

export const FOKUS_QUESTIONS: Question[] = [
  {
    id: "essay-kundproblem-vardeerbjudande",
    mode: "resonemang",
    type: "open",
    category: "Kund & värde",
    source: "AM1/AM2",
    question: "Utgå från ett specifikt kundproblem inom IT-sektorn. Formulera ett värdeerbjudande och förklara hur det skapar konkret nytta för kunden.",
    tags: ["Kund", "Värdeerbjudande", "BMC", "FAB"],
    answer: "Ett starkt svar utgår från kundens utmaning (t.ex. ineffektiv administration), inte tekniken. Värdeerbjudandet ska visa på konkret nytta som mindre tidsåtgång, lägre risk eller bättre beslutsunderlag, och motivera varför detta är värdefullt för just det kundsegmentet.",
    why: "Detta testar förmågan att koppla ihop kundens behov med den faktiska nyttan av en lösning, snarare än att bara lista funktioner.",
    example: "En kommun har långa ledtider i ärendehantering. Värdeerbjudandet är en automatiserad flödeslösning som frigör tid för personalen och ger medborgarna snabbare svar.",
    related: ["Kundsegment", "Värdeerbjudande", "FAB", "Kundnytta"]
  },
  {
    id: "essay-fab-saljargument",
    mode: "resonemang",
    type: "open",
    category: "Kund & värde",
    source: "AM2",
    question: "Beskriv en teknisk egenskap (Feature) hos en tjänst och använd FAB-modellen för att omvandla den till ett affärsmässigt säljargument (Benefit).",
    tags: ["FAB", "Erbjudande", "Sälj"],
    answer: "Svaret ska tydligt visa kedjan: Egenskap (vad det är), Fördel (vad den gör bättre) och Nytta (varför kunden tjänar på det). Fokus ska ligga på 'Benefit' – den faktiska kundnyttan.",
    why: "FAB är ett kritiskt verktyg för att översätta teknik till affärsvärde.",
    example: "Feature: Molnbaserad lagring. Advantage: Åtkomst från alla enheter. Benefit: Ökad flexibilitet och samarbetsförmåga för ett distribuerat team.",
    related: ["Features", "Advantages", "Benefits", "Kundnytta"]
  },
  {
    id: "essay-bmc-roda-traden",
    mode: "resonemang",
    type: "open",
    category: "Affärsmodell",
    source: "AM1/BMC",
    question: "Beskriv den 'röda tråden' i en Business Model Canvas för ett konsultbolag. Visa specifikt hur värdeerbjudandet hänger ihop med kundsegment och intäktsströmmar.",
    tags: ["BMC", "Affärsmodell", "Kundsegment", "Intäkter"],
    answer: "Ett bra svar visar hur de olika rutorna i BMC stödjer varandra. Det ska framgå hur bolaget skapar värde för ett specifikt segment, hur de når dem och hur detta resulterar i en hållbar intäktsmodell.",
    why: "BMC är inte nio isolerade rutor; styrkan ligger i hur de samverkar för att skapa en lönsam helhet.",
    example: "Nischade IT-konsulter (Nyckelresurs) löser komplex säkerhet (Värdeerbjudande) för banker (Kundsegment), vilket motiverar ett högt timpris eller retainer-avtal (Intäktsström).",
    related: ["Kundsegment", "Värdeerbjudande", "Intäktsströmmar", "Kostnadsstruktur"]
  },
  {
    id: "essay-swot-pestelid-beslut",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM2/AM3",
    question: "Hur kan PESTELID användas som underlag för en SWOT-analys? Ge ett exempel på hur en extern omvärldsfaktor kan leda till ett konkret affärsbeslut.",
    tags: ["PESTELID", "SWOT", "Beslut", "Omvärld"],
    answer: "PESTELID identifierar externa faktorer (möjligheter/hot) i omvärlden. Dessa förs in i SWOT-analysen. Svaret ska avslutas med ett logiskt beslut baserat på denna analys, t.ex. en nysatsning eller en riskreducering.",
    why: "Testar förmågan att gå från observation av omvärlden till strategisk handling.",
    example: "Ny lagstiftning (Legal i PESTELID) skapar ett behov av efterlevnad. Detta blir en 'Möjlighet' i SWOT. Beslutet blir att paketera en ny rådgivningstjänst inom just detta område.",
    related: ["Extern analys", "Intern analys", "Möjligheter", "Hot"]
  },
  {
    id: "essay-konkurrent-positionering",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM3",
    question: "Redogör för skillnaden mellan direkta konkurrenter och substitut. Förklara hur ett bolag kan använda denna insikt för att positionera sig på marknaden.",
    tags: ["Konkurrenter", "Substitut", "Positionering", "Differentiering"],
    answer: "Direkta konkurrenter erbjuder liknande lösningar, medan substitut löser samma problem på ett helt annat sätt (t.ex. 'göra själv'). Positioneringen ska bygga på unik kundnytta och bevisbar differentiering.",
    why: "Positionering handlar om att förstå vad kunden faktiskt väljer mellan.",
    example: "Ett konsultbolag tävlar inte bara mot andra byråer utan också mot kundens möjlighet att anställa egen personal eller köpa in en färdig SaaS-tjänst.",
    related: ["Direkta konkurrenter", "Substitut", "Differentiering", "Trovärdighet"]
  },
  {
    id: "essay-produktmarknad-risk",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM3",
    question: "Använd Ansoff-matrisen för att jämföra två olika tillväxtstrategier (t.ex. marknadspenetration vs. diversifiering). Resonera kring riskerna i de båda valen.",
    tags: ["Ansoff", "Produktmarknad", "Risk", "Tillväxt"],
    answer: "Svaret ska visa förståelse för att riskerna ökar när man rör sig mot nya produkter eller nya marknader. Marknadspenetration är lägst risk, medan diversifiering innebär högst osäkerhet.",
    why: "Det är viktigt att kunna värdera risk i förhållande till potentiell tillväxt.",
    example: "Att sälja befintliga M365-tjänster till befintliga kunder (penetration) är tryggt. Att starta en helt ny AI-avdelning för en ny industri (diversifiering) kräver stora investeringar och ny kompetens.",
    related: ["Marknadspenetration", "Produktutveckling", "Diversifiering", "Risk"]
  },
  {
    id: "essay-foretagsform-trovardighet",
    mode: "resonemang",
    type: "open",
    category: "Företagsform",
    source: "AM4/AM6",
    question: "Varför är valet av företagsform mer än bara en juridisk fråga för ett nystartat konsultbolag? Koppla valet till ansvar, trovärdighet och kundens upplevda risk.",
    tags: ["Företagsform", "Ansvar", "Trovärdighet", "Risk"],
    answer: "Ett Aktiebolag (AB) begränsar det personliga ansvaret men signalerar också seriositet och ekonomisk stabilitet till kunden, vilket sänker deras upplevda risk vid stora upphandlingar.",
    why: "Företagsformen är en del av bolagets 'förpackning' och affärsstrategi.",
    example: "En stor myndighet kräver ofta att leverantören är ett AB för att säkerställa att det finns en viss struktur och ansvarsfördelning bakom avtalet.",
    related: ["Aktiebolag", "Enskild firma", "Handelsbolag", "Personligt ansvar"]
  },
  {
    id: "essay-foretagsplattform-beteende",
    mode: "resonemang",
    type: "open",
    category: "Företagsplattform",
    source: "AM1/AM4",
    question: "Förklara sambandet mellan vision, mission och värderingar. Ge ett konkret exempel på hur en kärnvärdering kan styra ett beslut i den dagliga affärsverksamheten.",
    tags: ["Vision", "Mission", "Värderingar", "Kultur"],
    answer: "Visionen är målet, missionen är vägen dit, och värderingarna är kompassen för hur vi agerar. Ett bra svar visar hur en värdering (t.ex. 'Långsiktighet') leder till att man tackar nej till en kortsiktig vinst som skadar kundrelationen.",
    why: "Företagsplattformen ska vara ett praktiskt styrverktyg, inte bara vackra ord.",
    example: "Om värderingen är 'Transparens' så innebär det att vi öppet redovisar risker i projektet för kunden, även om det kan göra dem tveksamma i början.",
    related: ["Vision", "Mission", "Värderingar", "Kundrelation"]
  },
  {
    id: "essay-mal-kpi-bsc",
    mode: "resonemang",
    type: "open",
    category: "Styrning",
    source: "AM4",
    question: "Hur hjälper Balanced Scorecard (det balanserade styrkortet) ett företag att styra mot sina mål? Föreslå relevanta KPI:er från minst två olika perspektiv.",
    tags: ["Balanced Scorecard", "KPI", "Mål", "Styrning"],
    answer: "BSC balanserar hårda ekonomiska mått med mjuka mått som kundnöjdhet, interna processer och medarbetarnas lärande. Detta ger en mer komplett bild av bolagets hälsa och framtida potential.",
    why: "Ensidigt fokus på ekonomi kan dölja problem i leverans eller kundrelationer.",
    example: "Ekonomiskt perspektiv: Täckningsbidrag. Kundperspektiv: Net Promoter Score (NPS) eller återköpsfrekvens.",
    related: ["Ekonomi", "Kund", "Process", "Lärande"]
  },
  {
    id: "essay-ekonomisk-halsokoll",
    mode: "resonemang",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Du ska göra en ekonomisk 'hälsokoll' på ett bolag. Vilka nyckeltal (t.ex. soliditet, likviditet, resultat) tittar du på och hur läser du dem tillsammans för att förstå helheten?",
    tags: ["Resultaträkning", "Balansräkning", "Likviditet", "Soliditet", "Kassaflöde"],
    answer: "Resultatet visar lönsamhet, soliditeten visar långsiktig styrka och likviditeten visar förmågan att betala räkningar idag. Svaret ska betona att en enskild siffra inte säger allt – man måste se hur de påverkar varandra.",
    why: "Affärsmannaskap innebär att kunna tolka ekonomiska signaler som en helhetsbild.",
    example: "Ett bolag med hög vinst (resultat) men mycket låg likviditet riskerar ändå konkurs om de inte kan betala sina skulder i tid.",
    related: ["Lönsamhet", "Likviditet", "Soliditet", "Kassaflöde"]
  },
  {
    id: "essay-resultat-kassaflode-likviditet",
    mode: "case",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara logiken bakom att ett företag kan visa en stabil vinst i resultaträkningen men samtidigt lida av akuta likviditetsproblem.",
    tags: ["Resultat", "Kassaflöde", "Likviditet", "Kundfordringar"],
    answer: "Vinst är bokföringsmässig (intäkt uppstår vid fakturering), medan likviditet handlar om faktiska pengar på kontot. Om kunder betalar sent (långa kredittider) eller om kapital binds i lager, saknas pengar för löner och hyra trots att affären går med vinst.",
    why: "Detta är en av de viktigaste insikterna i ekonomisk styrning.",
    example: "Vi fakturerar 1 miljon i december men kunden har 90 dagars betalning. Resultatet ser bra ut för året, men kassan är tom i januari.",
    related: ["Resultat", "Kundfordringar", "Kassaflöde", "Kassalikviditet"]
  },
  {
    id: "essay-halso-essiq-jamforelse",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vid en jämförelse av två bolags årsredovisningar, varför är det viktigt att även läsa förvaltningsberättelsen och inte bara stirra på nyckeltalen?",
    tags: ["Årsredovisning", "Förvaltningsberättelse", "Jämförelse", "Ekonomi"],
    answer: "Nyckeltal visar *vad* som hänt, men förvaltningsberättelsen förklarar *varför*. Den ger kontext om marknadsläge, framtidsutsikter och engångshändelser som kan ha påverkat siffrorna temporärt.",
    why: "Kvalitativ analys är minst lika viktig som kvantitativ analys för att förstå risker.",
    example: "Ett bolag kan ha lägre marginal på grund av en stor strategisk investering som förväntas ge avkastning först nästa år.",
    related: ["Soliditet", "Likviditet", "Förvaltningsberättelse", "Bransch"]
  },
  {
    id: "essay-konsultbudget-scenario",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "Resonera kring vikten av att arbeta med olika scenarier (t.ex. optimistiskt vs. försiktigt) i en budget. Hur påverkar debiteringsgraden bolagets känslighet?",
    tags: ["Budget", "Prognos", "Scenario", "Likviditet"],
    answer: "Svaret ska visa att budgeten är ett styrmedel baserat på antaganden. Genom att testa vad som händer om debiteringsgraden sjunker med 10 % kan bolaget förbereda åtgärder i god tid.",
    why: "I konsultbranschen är debiteringsgraden den mest kritiska variabeln för lönsamhet.",
    example: "Ett optimistiskt scenario räknar med 85 % beläggning. Ett försiktigt scenario visar att bolaget fortfarande överlever vid 65 % beläggning, vilket ger trygghet.",
    related: ["Debiteringsgrad", "Prognos", "Likviditet", "Beläggning"]
  },
  {
    id: "essay-medarbetarkostnad-overhead",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "En konsult har en månadslön på 45 000 kr. Redogör för vilka ytterligare kostnader som tillkommer för företaget och varför timpriset mot kunden måste vara betydligt högre än timlönen.",
    tags: ["Medarbetarkostnad", "Overhead", "Pris", "Lönsamhet"],
    answer: "Svaret ska inkludera sociala avgifter, semesterlön, pension, försäkringar, utbildning, kontor, IT och säljkostnader. Dessutom måste debiterbara timmar täcka även den tid som inte kan faktureras.",
    why: "Förståelse för 'total cost of employment' och prissättningens logik.",
    example: "En medarbetare kostar ofta 1,5 till 2 gånger sin bruttolön när alla overhead-kostnader räknas in.",
    related: ["Sociala avgifter", "Overhead", "Debiteringsgrad", "Täckningsbidrag"]
  },
  {
    id: "essay-debiteringsgrad-pris-tb",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "Förklara hur debiteringsgrad, timpris och täckningsbidrag samverkar för att skapa lönsamhet i ett specifikt konsultprojekt.",
    tags: ["Debiteringsgrad", "Pris", "Täckningsbidrag", "Lönsamhet"],
    answer: "Täckningsbidraget är vad som blir kvar när projektets rörliga kostnader är betalda. För att täcka bolagets fasta kostnader krävs både ett rätt prissatt projekt och att konsulterna faktiskt har tid att utföra det (debiteringsgrad).",
    why: "Kopplingen mellan projektstyrning och bolagets totala ekonomi.",
    example: "Om vi sänker priset för att vinna en affär måste vi öka debiteringsgraden eller sänka kostnaderna för att behålla samma täckningsbidrag.",
    related: ["Beläggning", "Timpris", "Direkta kostnader", "Scope"]
  },
  {
    id: "essay-affarsmodell-intakter",
    mode: "case",
    type: "open",
    category: "Affärsmodell",
    source: "AM6",
    question: "Välj en lämplig intäktsmodell för en ny IT-tjänst (t.ex. abonnemang, fastpris eller löpande räkning). Motivera valet utifrån kundnytta och bolagets risk.",
    tags: ["Affärsmodell", "Intäktsmodell", "Kundnytta", "BMC"],
    answer: "Svaret ska väga kundens önskan om förutsägbarhet mot bolagets risk för 'scope creep'. Abonnemang ger stabila intäkter, medan fastpris kräver extremt god ordning på vad som ingår.",
    why: "Intäktsmodellen är en strategisk del av affärsmodellen.",
    example: "Ett abonnemang (SaaS) är bra för kunden då tröskeln att börja är låg, och bra för oss då vi får återkommande intäkter.",
    related: ["Timpris", "Fastpris", "Abonnemang", "Supportavtal"]
  },
  {
    id: "essay-fastpris-timpris-risk",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "När är det affärsmässigt motiverat att erbjuda kunden ett fastpris istället för löpande räkning? Vilken är den största risken för leverantören och hur hanteras den?",
    tags: ["Fastpris", "Timpris", "Risk", "Scope"],
    answer: "Fastpris motiveras när kunden kräver budgetkontroll och scope är tydligt definierat. Den största risken är att projektet tar längre tid än beräknat (scope creep), vilket hanteras genom strikt ändringshantering i avtalet.",
    why: "Prismodellen styr incitament och riskfördelning mellan parterna.",
    example: "Vi säljer en förstudie till fast pris eftersom vi vet exakt vad som ska levereras, men utvecklingen sker på löpande räkning då behoven kan ändras.",
    related: ["Scope", "Ändringshantering", "Kundrisk", "Lönsamhet"]
  },
  {
    id: "essay-avtalskarta-it",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Rita upp en 'avtalskarta' för ett IT-projekt. Vilka olika avtalstyper (t.ex. NDA, DPA, SLA) bör ingå och vilken funktion fyller de för att minska affärsrisken?",
    tags: ["Avtal", "Kundavtal", "NDA", "DPA", "SLA"],
    answer: "Svaret ska visa förståelse för att avtal skyddar båda parter. NDA skyddar hemligheter, DPA reglerar personuppgifter (GDPR) och SLA garanterar en viss servicenivå efter leverans.",
    why: "Rätt avtalsstruktur är en förutsättning för en trygg och professionell affär.",
    example: "Huvudavtalet reglerar vad vi ska göra, medan SLA:et garanterar att vi svarar inom 4 timmar om systemet går ner.",
    related: ["Scope", "Ansvar", "Sekretess", "Personuppgifter"]
  },
  {
    id: "essay-gdpr-data-ansvar",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Resonera kring GDPR som en affärsrisk. Vad innebär det att vara personuppgiftsbiträde i ett konsultuppdrag och hur påverkar det avtalsskrivandet?",
    tags: ["GDPR", "Personuppgifter", "DPA", "Risk"],
    answer: "Svaret ska förklara att biträdet hanterar data åt kunden (ansvarig). Ett Personuppgiftsbiträdesavtal (DPA) är ett lagkrav och en trygghet som visar att vi hanterar data säkert och enligt instruktion.",
    why: "Dataansvar är en central del av moderna IT-leveranser.",
    example: "Om vi bygger ett HR-system hanterar vi känsliga data. Utan ett korrekt DPA riskerar både kunden och vi stora böter och skadat förtroende.",
    related: ["Personuppgiftsansvarig", "Personuppgiftsbiträde", "Säkerhet", "Avtal"]
  },
  {
    id: "essay-sla-support-efterleverans",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Hur kan välformulerade supportavtal och SLA (Service Level Agreements) skapa långsiktiga värden för både kunden och konsultbolaget?",
    tags: ["SLA", "Support", "Efterleverans", "Intäkter"],
    answer: "Kunden får trygghet och garanterad hjälp, medan konsultbolaget bygger en närmare kundrelation och får förutsägbara, återkommande intäkter.",
    why: "Efterleverans är ofta där den verkliga lönsamheten och kundlojaliteten byggs.",
    example: "Genom att ha ett SLA på plats vet kunden att de prioriteras vid problem, vilket gör att de vågar satsa mer på vår lösning.",
    related: ["Kundtrygghet", "Återkommande intäkt", "Avtal", "Ansvar"]
  },
  {
    id: "essay-rebr-kallkritik",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "AM3/REBR",
    question: "När du använder externa källor (t.ex. marknadsrapporter som Randstads REBR) som underlag för ett beslut, hur bör du resonera källkritiskt för att inte övertolka resultaten?",
    tags: ["REBR", "Källkritik", "Beslut", "Omvärld"],
    answer: "Ett affärsmässigt svar visar på källkritik: Vem har skrivit rapporten? Är urvalet representativt för vår bransch? Data stödjer en hypotes men är sällan en absolut sanning för just vår specifika affär.",
    why: "Att kunna värdera information är en nyckelkompetens i beslutsfattande.",
    example: "En rapport säger att 'alla' vill ha distansarbete, men det betyder inte att just våra seniora säkerhetskonsulter fungerar bäst hemifrån i alla projekt.",
    related: ["Omvärldsanalys", "Antaganden", "Källkritik", "Beslut"]
  },
  {
    id: "essay-lagkonjunktur-paketering",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM3",
    question: "Hur bör ett konsultbolag justera sin paketering och sina säljargument under en lågkonjunktur? Vilken typ av kundnytta blir extra viktig då?",
    tags: ["Lågkonjunktur", "Paketering", "Kundnytta", "Risk"],
    answer: "Fokus flyttas från tillväxt och innovation till effektivisering, kostnadsbesparing och riskminimering. Argumenten måste vara 'need to have' snarare än 'nice to have'.",
    why: "Affärsmannaskap innebär att anpassa erbjudandet efter kundens aktuella verklighet.",
    example: "Istället för att sälja 'Digital Transformation' säljer vi 'Automatisering som sänker personalkostnaden med 20 % på sex månader'.",
    related: ["Kostnadsbesparing", "Riskminskning", "ROI", "Prioritering"]
  },
  {
    id: "essay-sticka-ut",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM2",
    question: "Många bolag hävdar att de är 'bäst' eller 'mest innovativa'. Hur kan ett mindre bolag sticka ut genom att använda konkreta bevis istället för tomma superlativ?",
    tags: ["Differentiering", "Trovärdighet", "Bevis", "Kundnytta"],
    answer: "Svaret ska betona vikten av bevis: Referenscase med mätbara resultat, certifieringar, nischkompetens eller erbjudande om en pilot. Trovärdighet byggs genom vad man *gjort*, inte vad man *säger*.",
    why: "Differentiering bygger på substans, inte på adjektiv.",
    example: "Istället för att säga 'Vi är experter på AI' säger vi 'Vi har implementerat tre AI-flöden som minskat manuellt arbete med 400 timmar/år för kund X'.",
    related: ["Differentiering", "Nisch", "Referenser", "Mätbar effekt"]
  },
  {
    id: "essay-matbar-effekt",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM4",
    question: "Varför är det viktigt att definiera hur effekten av en leverans ska mätas redan *innan* projektet startar? Ge exempel på hur du gör en nytta mätbar.",
    tags: ["Mätbar effekt", "KPI", "ROI", "Före/efter"],
    answer: "Genom att mäta nuläget (baseline) kan man efteråt bevisa värdet. Det gör det lättare att få betalt, få referenser och motivera framtida investeringar för kunden.",
    why: "Mätbarhet är grunden för att kunna visa ROI (Return on Investment).",
    example: "Mät antal manuella fel i faktureringen under en månad före systembyte, och jämför med antalet fel en månad efteråt.",
    related: ["KPI", "Före/efter", "ROI", "Kundnytta"]
  },
  {
    id: "essay-kopa-nu",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM2",
    question: "Kunden tvekar och vill vänta med beslutet till nästa kvartal. Hur resonerar du kring 'alternativkostnad' för att motivera ett köp här och nu?",
    tags: ["Köpbeslut", "Risk", "Alternativkostnad", "Kundnytta"],
    answer: "Svaret ska visa på vad det *kostar att inte göra något*. Varje månad utan den nya lösningen innebär fortsatta förluster, högre risker eller missade intäkter som ofta överstiger kostnaden för att agera direkt.",
    why: "Att förstå kundens passivitet som en kostnad är ett starkt säljargument.",
    example: "Att vänta tre månader på automationen innebär 300 timmar extra manuellt arbete. Det är en kostnad som kunden aldrig får tillbaka.",
    related: ["Alternativkostnad", "Brådska", "Risk", "Beslutsargument"]
  },
  {
    id: "essay-trovardighet-nystartat",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM6",
    question: "Hur kan ett nystartat bolag utan tunga referenser bygga tillräcklig trovärdighet för att vinna en affär hos en skeptisk kund?",
    tags: ["Trovärdighet", "Referenser", "Pilot", "Risk"],
    answer: "Genom att minimera kundens risk: Erbjud en tidsbegränsad pilot, var extremt transparent med arbetssätt, visa på individuell expertkompetens (CV) och ha fläckfria avtal.",
    why: "Riskreducering är nyckeln när historik saknas.",
    example: "Erbjud kunden att köpa en 'förstudie' till ett lågt fast pris för att visa vad vi går för innan det stora avtalet tecknas.",
    related: ["Pilot", "Referenser", "Scope", "Riskreducering"]
  },
  {
    id: "essay-kundens-riskfragor",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM6",
    question: "Sätt dig i kundens stol inför en stor IT-investering. Vilka är de tre mest kritiska 'riskfrågorna' du bör ställa till leverantören, och vad förväntar du dig för typ av svar?",
    tags: ["Kundfrågor", "Risk", "Avtal", "Ekonomi"],
    answer: "Frågorna bör röra: 1. Vad händer om tidsplanen spricker (ansvar/vite)? 2. Hur hanteras vår data (säkerhet/GDPR)? 3. Hur vet vi att lösningen faktiskt ger den effekt ni lovar (KPI/uppföljning)? Svaren ska vara konkreta och avtalsbundna.",
    why: "Förmågan att se affären ur köparens perspektiv är kärnan i affärsmannaskap.",
    example: "Kund: 'Vad händer om er konsult slutar mitt i projektet?' Leverantör: 'Vi har en dokumenterad överlämningsprocess och en resursgaranti i avtalet.'",
    related: ["Kundrisk", "Avtal", "Mätbar effekt", "Efterleverans"]
  },
  {
    id: "essay-hallbar-affar",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Tentarisk/AM1-AM6",
    question: "Resonera kring begreppet 'en hållbar affär'. Varför är det dåligt affärsmannaskap att sälja något som kunden inte behöver, även om det ger en hög vinst kortsiktigt?",
    tags: ["Hållbar affär", "Kundnytta", "Lönsamhet", "Långsiktighet"],
    answer: "En hållbar affär bygger på förtroende och återköp. Att lura på kunden något skadar bolagets varumärke, leder till konflikter och förstör möjligheten till framtida affärer och referenser.",
    why: "Affärsmannaskap handlar om långsiktig värdeskapande, inte bara nästa månads vinst.",
    example: "Ett konsultbolag som säljer in 1000 timmar för ett problem som kunde lösas på 100 timmar kommer aldrig få komma tillbaka till den kunden.",
    related: ["Kundnytta", "Lönsamhet", "Etik", "Långsiktighet"]
  },
  {
    id: "essay-presentation-roda-traden",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "Grupparbete",
    question: "Hur strukturerar du en affärspresentation för att skapa en tydlig 'röd tråd' från kundens problem till den ekonomiska slutkalkylen och avtalet?",
    tags: ["Presentation", "Röd tråd", "Grupparbete", "Helhet"],
    answer: "Börja i kundens verklighet (problemet), visa lösningen (nyttan), motivera varför vi är rätt val (analys/bevis), presentera kalkylen (ROI) och avsluta med hur vi tryggar leveransen (avtal/risk).",
    why: "En sammanhängande argumentation är avgörande för att få med sig beslutsfattare.",
    example: "Presentationens struktur: Problem -> Lösning -> Marknadskontext -> Pris & Nytta -> Riskhantering -> Nästa steg.",
    related: ["Kundproblem", "Affärsmodell", "Ekonomi", "Avtal"]
  },
  {
    id: "essay-helhetscase",
    mode: "examinatorrisk",
    type: "open",
    category: "Tentarisk",
    source: "AM1-AM6",
    question: "Miniessä: Beskriv ett fiktivt IT-konsultbolags resa från att identifiera ett kundproblem till att leverera en mätbar effekt. Inkludera analys, affärsmodell, ekonomi och avtalstänk.",
    tags: ["Helhetscase", "Kundnytta", "Analys", "Ekonomi", "Avtal"],
    answer: "Svaret ska väva ihop kursens alla delar. Det ska framgå hur omvärldsanalysen motiverade valet, hur BMC-modellen ser ut, hur budgeten bär sig och hur avtalet skyddar affären så att kunden slutligen får sin utlovade nytta.",
    why: "Detta är den ultimata prövningen av om studenten kan tillämpa kursens alla delar i ett sammanhang.",
    example: "Ett bolag ser ett behov av GDPR-efterlevnad (Analys), skapar en paketerad tjänst (BMC), prissätter den för att täcka overhead (Ekonomi), säkrar upp med DPA (Avtal) och mäter minskad risk för kunden (Effekt).",
    related: ["BMC", "SWOT", "Budget", "Avtal", "KPI"]
  }
];
