export interface Question {
  id: string;
  mode: 'resonemang' | 'case' | 'examinatorrisk' | 'repetition';
  type: 'open' | 'mc';
  category: string;
  source: string;
  question: string;
  tags: string[];
  answer?: string;
  why?: string;
  example?: string;
  related?: string[];
  options?: string[];
  correctIndex?: number;
  explanation?: string;
}

export const FOKUS_QUESTIONS: Question[] = [
  {
    id: "essay-kundproblem-vardeerbjudande",
    mode: "resonemang",
    type: "open",
    category: "Kund & värde",
    source: "AM1/AM2",
    question: "Beskriv ett kundproblem och formulera ett värdeerbjudande som visar konkret kundnytta.",
    tags: ["Kund", "Värdeerbjudande", "BMC", "FAB"],
    answer: "Ett starkt svar börjar i kundens problem, inte i tekniken. Värdeerbjudandet ska visa vilken nytta kunden får, till exempel mindre administration, lägre risk, snabbare leverans eller bättre beslutsunderlag, och varför just den nyttan är viktig för kundsegmentet.",
    why: "Det här ersätter flera små begreppsfrågor om kundsegment, värdeerbjudande och nytta med en fråga där du måste använda begreppen i ett resonemang.",
    example: "En kommunal verksamhet har långa manuella handläggningsflöden. Erbjudandet kan vara ett M365-baserat automationspaket som minskar väntetid och frigör tid för personalen.",
    related: ["Kundsegment", "Värdeerbjudande", "FAB", "Kundnytta"]
  },
  {
    id: "essay-fab-saljargument",
    mode: "resonemang",
    type: "open",
    category: "Kund & värde",
    source: "AM2",
    question: "Använd FAB för att göra om en teknisk egenskap till ett säljargument.",
    tags: ["FAB", "Erbjudande", "Sälj"],
    answer: "Ett bra svar visar kedjan egenskap, fördel och kundnytta. Du ska alltså inte stanna vid vad lösningen är, utan förklara vad den gör bättre och varför kunden bryr sig.",
    why: "Om tentan inte är en begreppstenta blir FAB relevant som verktyg för att skriva kundnära och affärsmässigt.",
    example: "Egenskap: automatiserat Power Automate-flöde. Fördel: färre manuella steg. Nytta: snabbare handläggning och mindre risk för fel.",
    related: ["Features", "Advantages", "Benefits", "Kundnytta"]
  },
  {
    id: "essay-bmc-roda-traden",
    mode: "resonemang",
    type: "open",
    category: "Affärsmodell",
    source: "AM1/BMC",
    question: "Visa den röda tråden i en Business Model Canvas för ett IT-konsultbolag.",
    tags: ["BMC", "Affärsmodell", "Kundsegment", "Intäkter"],
    answer: "Ett bra svar binder ihop kundsegment, värdeerbjudande, kanaler/relationer, nyckelresurser, intäkter och kostnader. Poängen är att visa hur bolaget skapar värde, levererar det och får betalt utan att modellen faller isär.",
    why: "BMC är inte nio lösa rutor. På essänivå behöver du visa sambandet mellan rutorna.",
    example: "SME-kunder med administrativt slöseri köper ett paketerat automationsprojekt. Konsulternas M365-kompetens är nyckelresurs, LinkedIn/referenser är kanal och intäkten kan vara projektpris plus supportavtal.",
    related: ["Kundsegment", "Värdeerbjudande", "Intäktsströmmar", "Kostnadsstruktur"]
  },
  {
    id: "essay-swot-pestelid-beslut",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM2/AM3",
    question: "Koppla PESTELID till SWOT och avsluta med ett affärsbeslut.",
    tags: ["PESTELID", "SWOT", "Beslut", "Omvärld"],
    answer: "PESTELID används för att hitta externa omvärldsfaktorer. Dessa kan sedan föras in i SWOT som möjligheter eller hot, medan styrkor och svagheter är interna. Ett starkt svar slutar med ett konkret beslut, till exempel paketering, målgruppsval eller riskhantering.",
    why: "Det här testar om du kan använda analysmodeller för att dra slutsatser, inte bara nämna vad bokstäverna står för.",
    example: "Teknologisk utveckling och lågkonjunktur kan bli hot eller möjligheter. Om bolaget har stark M365-kompetens kan beslutet bli att sälja kostnadsbesparande automation till kunder med pressad ekonomi.",
    related: ["Extern analys", "Intern analys", "Möjligheter", "Hot"]
  },
  {
    id: "essay-konkurrent-positionering",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM3",
    question: "Analysera konkurrenter och substitut och förklara hur bolaget bör positionera sig.",
    tags: ["Konkurrenter", "Substitut", "Positionering", "Differentiering"],
    answer: "Ett bra svar skiljer direkta konkurrenter från substitut och visar vad kunden jämför med. Positioneringen ska bygga på kundnytta och trovärdiga bevis, inte bara på att bolaget säger sig vara bättre.",
    why: "Det här bakar ihop konkurrensanalys, differentiering och säljargument i en tentanära fråga.",
    example: "Ett litet konsultbolag kan positionera sig mot större byråer genom snabbare start, närmare kundkontakt och paketerad M365-specialisering, men måste bevisa detta med pilot, referenser eller tydlig leveransplan.",
    related: ["Direkta konkurrenter", "Substitut", "Differentiering", "Trovärdighet"]
  },
  {
    id: "essay-produktmarknad-risk",
    mode: "resonemang",
    type: "open",
    category: "Analys & strategi",
    source: "AM3",
    question: "Jämför två produkt-/marknadsval och motivera vilket som är rimligast.",
    tags: ["Ansoff", "Produktmarknad", "Risk", "Tillväxt"],
    answer: "Ett bra svar använder produkt-/marknadstänk: befintlig eller ny produkt mot befintlig eller ny marknad. Du ska väga potential mot risk och avsluta med ett motiverat val.",
    why: "Frågan gör Ansoff praktisk. Det viktiga är inte namnet på modellen, utan hur den hjälper gruppen välja väg.",
    example: "För ett nystartat konsultbolag är marknadspenetration eller produktutveckling ofta rimligare än diversifiering eftersom trovärdighet, referenser och leveranskapacitet ännu är begränsade.",
    related: ["Marknadspenetration", "Produktutveckling", "Diversifiering", "Risk"]
  },
  {
    id: "essay-foretagsform-trovardighet",
    mode: "resonemang",
    type: "open",
    category: "Företagsform",
    source: "AM4/AM6",
    question: "Motivera företagsform för ett konsultbolag och koppla valet till ansvar och trovärdighet.",
    tags: ["Företagsform", "Ansvar", "Trovärdighet", "Risk"],
    answer: "Ett bra svar jämför minst två företagsformer och kopplar valet till personligt ansvar, kapitalbehov, kundens förtroende och risk. Aktiebolag kan vara rimligt när man vill begränsa personligt ansvar och signalera seriositet, men kräver mer formalia.",
    why: "Här räcker det inte att kunna vad AB betyder. Du måste visa varför formen passar affären.",
    example: "Ett IT-konsultbolag som skriver kundavtal och hanterar data kan vinna på AB eftersom ansvar och avtal känns tydligare för kunden än i en enskild firma.",
    related: ["Aktiebolag", "Enskild firma", "Handelsbolag", "Personligt ansvar"]
  },
  {
    id: "essay-foretagsplattform-beteende",
    mode: "resonemang",
    type: "open",
    category: "Företagsplattform",
    source: "AM1/AM4",
    question: "Förklara hur vision, mission och värderingar kan bli konkret beteende i affären.",
    tags: ["Vision", "Mission", "Värderingar", "Kultur"],
    answer: "Ett starkt svar kopplar plattformen till beslut i vardagen. Visionen visar riktning, missionen beskriver uppdraget och värderingarna styr hur bolaget säljer, prioriterar, levererar och hanterar kunden.",
    why: "Det här gör kultur och plattform affärsmässiga i stället för fina ord på en slide.",
    example: "Om värderingen är transparens måste det synas i offert, riskdialog, tidrapportering och hur man säger nej till otydliga uppdrag.",
    related: ["Vision", "Mission", "Värderingar", "Kundrelation"]
  },
  {
    id: "essay-mal-kpi-bsc",
    mode: "resonemang",
    type: "open",
    category: "Styrning",
    source: "AM4",
    question: "Sätt mål och KPI:er med Balanced Scorecard för ett konsultbolag.",
    tags: ["Balanced Scorecard", "KPI", "Mål", "Styrning"],
    answer: "Ett bra svar använder flera perspektiv, till exempel ekonomi, kund, interna processer samt lärande och tillväxt. KPI:erna ska visa om bolaget rör sig mot målet, inte bara vara lätta att mäta.",
    why: "Frågan testar styrning: vilka mått skulle faktiskt hjälpa bolaget att fatta bättre beslut?",
    example: "Ekonomi: täckningsbidrag per projekt. Kund: återköpsgrad. Process: leverans i tid. Lärande: certifieringar eller förbättrade arbetssätt.",
    related: ["Ekonomi", "Kund", "Process", "Lärande"]
  },
  {
    id: "essay-ekonomisk-halsokoll",
    mode: "resonemang",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Gör en ekonomisk hälsokoll av ett företag med resultat, balans, likviditet, soliditet och kassaflöde.",
    tags: ["Resultaträkning", "Balansräkning", "Likviditet", "Soliditet", "Kassaflöde"],
    answer: "Ett starkt svar läser flera mått tillsammans. Resultatet visar lönsamhet, balansräkningen visar finansiering, likviditeten visar kort betalningsförmåga, soliditeten visar långsiktig motståndskraft och kassaflödet visar om pengar faktiskt rör sig in och ut.",
    why: "Det här är essävarianten av många gamla ekonomibegrepp. Du ska visa helhetsbedömning, inte bara definitioner.",
    example: "Ett bolag kan ha vinst men ändå vara pressat om pengar binds i fordringar, lagret är stort eller kassaflödet är svagt.",
    related: ["Lönsamhet", "Likviditet", "Soliditet", "Kassaflöde"]
  },
  {
    id: "essay-resultat-kassaflode-likviditet",
    mode: "case",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara varför ett företag kan visa vinst men ändå få likviditetsproblem.",
    tags: ["Resultat", "Kassaflöde", "Likviditet", "Kundfordringar"],
    answer: "Resultat handlar om intäkter minus kostnader under en period, men likviditet och kassaflöde handlar om betalningsförmåga och pengar in och ut. Ett bolag kan därför visa vinst men sakna pengar om kunder betalar sent, kapital binds i lager eller stora utbetalningar kommer före inbetalningar.",
    why: "Det här är en klassisk resonemangsfråga eftersom många blandar ihop resultat, kassaflöde och likviditet.",
    example: "Ett konsultbolag kan fakturera ett stort projekt i december men få betalt i februari. Resultatet ser bra ut, men januari kan ändå bli pressad.",
    related: ["Resultat", "Kundfordringar", "Kassaflöde", "Kassalikviditet"]
  },
  {
    id: "essay-halso-essiq-jamforelse",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Jämför två bolag utifrån årsredovisning och dra en försiktig slutsats.",
    tags: ["Årsredovisning", "Förvaltningsberättelse", "Jämförelse", "Ekonomi"],
    answer: "Ett bra svar jämför flera nyckeltal och läser dem tillsammans med förvaltningsberättelsen. Slutsatsen ska vara försiktig: ett bolag kan se starkt ut på ett mått men svagare på ett annat, och verksamhetens situation kan förklara siffrorna.",
    why: "Det här tränar dig att inte dra för snabba slutsatser från en enda siffra.",
    example: "Hälsö Fisk och Essiq kan jämföras med soliditet, likviditet, resultat och texten om vad som hänt i verksamheten. Skillnaderna behöver förklaras med bransch, storlek och omvärld.",
    related: ["Soliditet", "Likviditet", "Förvaltningsberättelse", "Bransch"]
  },
  {
    id: "essay-konsultbudget-scenario",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "Gör ett kort budgetresonemang för ett konsultbolag med ett optimistiskt och ett försiktigt scenario.",
    tags: ["Budget", "Prognos", "Scenario", "Likviditet"],
    answer: "Ett bra svar skiljer budget från prognos och visar vad som händer när beläggning, pris eller kostnader ändras. Du ska resonera om både lönsamhet och likviditet, särskilt om intäkter kommer senare än kostnader.",
    why: "Det här gör budgetfrågorna mer verkliga: man styr inte med en statisk siffra, utan med antaganden och uppföljning.",
    example: "Optimistiskt scenario: 80 procent debiteringsgrad och full betalning i tid. Försiktigt scenario: 60 procent debiteringsgrad, sen kundbetalning och högre säljkostnad.",
    related: ["Debiteringsgrad", "Prognos", "Likviditet", "Beläggning"]
  },
  {
    id: "essay-medarbetarkostnad-overhead",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "Förklara vad en konsult egentligen kostar företaget och varför priset måste bära mer än lönen.",
    tags: ["Medarbetarkostnad", "Overhead", "Pris", "Lönsamhet"],
    answer: "Ett bra svar tar med lön, sociala avgifter, semester, utrustning, administration, säljtid, ledning och annan overhead. Timpriset måste täcka både direkt kostnad, oddebiterad tid, fasta kostnader och vinst.",
    why: "Frågan bakar ihop medarbetarkostnad, beläggning, overhead och prissättning.",
    example: "En konsult som kostar 45 000 kr i lön per månad kostar mer än så för bolaget när sociala avgifter, pension, dator, kontor och icke debiterbar tid räknas in.",
    related: ["Sociala avgifter", "Overhead", "Debiteringsgrad", "Täckningsbidrag"]
  },
  {
    id: "essay-debiteringsgrad-pris-tb",
    mode: "case",
    type: "open",
    category: "Budget",
    source: "AM6",
    question: "Koppla debiteringsgrad, pris och täckningsbidrag till lönsamhet i ett konsultprojekt.",
    tags: ["Debiteringsgrad", "Pris", "Täckningsbidrag", "Lönsamhet"],
    answer: "Debiteringsgraden visar hur stor del av tiden som kan faktureras. Priset avgör intäkten per debiterad timme och täckningsbidraget visar vad som återstår efter direkta kostnader för att täcka fasta kostnader och vinst.",
    why: "Det här är mer tentanära än att bara fråga vad täckningsbidrag betyder.",
    example: "Ett högt timpris hjälper inte om debiteringsgraden är låg. Ett fastprisprojekt kan också få svagt täckningsbidrag om scope glider och fler timmar krävs än planerat.",
    related: ["Beläggning", "Timpris", "Direkta kostnader", "Scope"]
  },
  {
    id: "essay-affarsmodell-intakter",
    mode: "case",
    type: "open",
    category: "Affärsmodell",
    source: "AM6",
    question: "Välj affärsmodell och intäktsmodell för ett IT-bolag och motivera valet.",
    tags: ["Affärsmodell", "Intäktsmodell", "Kundnytta", "BMC"],
    answer: "Ett starkt svar kopplar intäktsmodellen till kundnytta, risk och leverans. Projektpris, timpris, abonnemang eller supportavtal passar olika bra beroende på hur tydligt uppdraget är och hur kunden vill köpa trygghet.",
    why: "Frågan tvingar ihop affärsmodell, ekonomi och kundperspektiv.",
    example: "Ett automationspaket kan säljas som fast startprojekt plus löpande support, så kunden får tydlig startkostnad och bolaget får återkommande intäkt.",
    related: ["Timpris", "Fastpris", "Abonnemang", "Supportavtal"]
  },
  {
    id: "essay-fastpris-timpris-risk",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "När är fastpris bättre än timpris, och vilken risk måste hanteras?",
    tags: ["Fastpris", "Timpris", "Risk", "Scope"],
    answer: "Fastpris kan passa när uppdraget är avgränsat och kunden vill ha kostnadskontroll. Timpris passar bättre när behovet är oklart eller förändras. Den centrala risken är scope creep: om mer arbete smyger in utan ändrad ersättning försämras lönsamheten.",
    why: "Det här kombinerar prissättning, risk och avtalslogik.",
    example: "En förstudie kan säljas fast eftersom leveransen är tydlig. Ett längre förändringsarbete kan behöva timpris eller tydliga ändringsbeställningar.",
    related: ["Scope", "Ändringshantering", "Kundrisk", "Lönsamhet"]
  },
  {
    id: "essay-avtalskarta-it",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Gör en avtalskarta för ett IT-projekt och förklara varför varje del behövs.",
    tags: ["Avtal", "Kundavtal", "NDA", "DPA", "SLA"],
    answer: "Ett bra svar tar upp kundavtal eller uppdragsavtal, tydlig scope, ansvar, pris, leverans, ändringar, sekretess och personuppgiftshantering. Om support ingår kan även SLA behövas.",
    why: "Avtal blir här inte ett begrepp utan ett sätt att minska missförstånd, risk och framtida konflikt.",
    example: "För ett systemprojekt kan avtalskartan innehålla uppdragsavtal, personuppgiftsbiträdesavtal, sekretessavtal, licensvillkor och SLA för support.",
    related: ["Scope", "Ansvar", "Sekretess", "Personuppgifter"]
  },
  {
    id: "essay-gdpr-data-ansvar",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Resonera om GDPR och dataansvar som affärsrisk i ett IT-konsultuppdrag.",
    tags: ["GDPR", "Personuppgifter", "DPA", "Risk"],
    answer: "Ett bra svar identifierar om personuppgifter behandlas, vem som är personuppgiftsansvarig och vem som är biträde. Det ska också visa hur avtalet, säkerheten och arbetssättet minskar risken för kunden och konsultbolaget.",
    why: "GDPR är inte bara juridik. Det påverkar trovärdighet, kundens risk och vad som måste stå i avtalet.",
    example: "Om konsulten får åtkomst till kundregister behövs tydlig åtkomststyrning, personuppgiftsbiträdesavtal och rutiner för incidenter.",
    related: ["Personuppgiftsansvarig", "Personuppgiftsbiträde", "Säkerhet", "Avtal"]
  },
  {
    id: "essay-sla-support-efterleverans",
    mode: "case",
    type: "open",
    category: "Avtal & affär",
    source: "AM6",
    question: "Förklara hur support och SLA efter leverans kan skapa både kundtrygghet och intäkter.",
    tags: ["SLA", "Support", "Efterleverans", "Intäkter"],
    answer: "Support och SLA kan minska kundens risk efter projektet genom tydliga svarstider, ansvar och prioriteringar. För bolaget kan det skapa återkommande intäkter, men bara om omfattning, pris och ansvar är tydligt avtalade.",
    why: "Frågan binder ihop kundrelation, affärsmodell och avtal efter själva projektleveransen.",
    example: "Efter ett automationsprojekt kan kunden köpa månatlig support med svarstid, mindre ändringar och övervakning av flöden.",
    related: ["Kundtrygghet", "Återkommande intäkt", "Avtal", "Ansvar"]
  },
  {
    id: "essay-rebr-kallkritik",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "AM3/REBR",
    question: "Använd REBR eller extern källa i ett affärsbeslut utan att överdriva vad källan bevisar.",
    tags: ["REBR", "Källkritik", "Beslut", "Omvärld"],
    answer: "Ett bra svar använder källan som stöd för omvärldsbild eller marknadsantagande, men skiljer fakta från tolkning. Slutsatsen ska visa vad källan faktiskt säger, vad den inte säger och hur den ändå påverkar beslutet.",
    why: "Det här är en sannolik essäfråga om läraren vill se affärsmannaskap: använd underlag, dra rimliga slutsatser och var inte slarvig.",
    example: "En trendrapport kan stödja att digitalisering ökar, men den bevisar inte automatiskt att just vår tjänst kommer sälja. Beslutet kan ändå bli att testa en smal pilot.",
    related: ["Omvärldsanalys", "Antaganden", "Källkritik", "Beslut"]
  },
  {
    id: "essay-lagkonjunktur-paketering",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM3",
    question: "Hur bör ett konsultbolag paketera sitt erbjudande i lågkonjunktur?",
    tags: ["Lågkonjunktur", "Paketering", "Kundnytta", "Risk"],
    answer: "I lågkonjunktur bör erbjudandet kopplas tydligare till kostnadsbesparing, riskminskning, effektivisering eller snabb återbetalning. Kunden behöver förstå varför köpet är rimligt nu trots pressad budget.",
    why: "Den här frågan matchar ett mer affärsutvecklingsinriktat sätt att tänka: kundens läge styr paketering och argument.",
    example: "I stället för att sälja 'digital transformation' kan bolaget sälja ett avgränsat automationspaket som frigör 10 timmar administration per vecka.",
    related: ["Kostnadsbesparing", "Riskminskning", "ROI", "Prioritering"]
  },
  {
    id: "essay-sticka-ut",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM2",
    question: "Hur kan ett litet bolag sticka ut utan att använda tomma superlativ?",
    tags: ["Differentiering", "Trovärdighet", "Bevis", "Kundnytta"],
    answer: "Ett bra svar bygger differentiering på konkret kundnytta och bevis: tydlig nisch, snabb leverans, mätbara resultat, referenser, pilot eller specialistkompetens. Tomma ord som bäst och mest innovativ måste ersättas av något kunden kan kontrollera.",
    why: "Det här tränar exakt den typ av affärsmässigt språk som ofta skiljer ett svagt grupparbete från ett starkt.",
    example: "Bolaget kan säga: vi hjälper HR-avdelningar minska manuell onboardingtid med M365-flöden, och visar en pilot med före/efter-mätning.",
    related: ["Differentiering", "Nisch", "Referenser", "Mätbar effekt"]
  },
  {
    id: "essay-matbar-effekt",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM4",
    question: "Hur visar du att erbjudandet ger mätbar effekt?",
    tags: ["Mätbar effekt", "KPI", "ROI", "Före/efter"],
    answer: "Ett bra svar sätter upp mätetal före leverans, mäter efter leverans och kopplar effekten till kundnytta. Det kan handla om sparad tid, färre fel, kortare ledtid, bättre återköp eller lägre kostnad.",
    why: "Mätbar effekt är starkare än allmänna påståenden. Det gör affären trovärdig.",
    example: "Före projektet tar onboarding 4 timmar per anställd. Efter automation tar den 1 timme. Effekten blir 3 timmar sparad tid per anställd.",
    related: ["KPI", "Före/efter", "ROI", "Kundnytta"]
  },
  {
    id: "essay-kopa-nu",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM2",
    question: "Motivera varför kunden ska köpa nu och inte vänta.",
    tags: ["Köpbeslut", "Risk", "Alternativkostnad", "Kundnytta"],
    answer: "Ett starkt svar visar kundens kostnad eller risk med att vänta. Argumentet kan vara förlorad tid, fortsatt felrisk, högre framtida kostnad eller missad effektivisering, men det måste kopplas till kundens situation.",
    why: "Det här är mer affärsmässigt än att bara beskriva produkten. Du tränar på att svara ur kundens beslutsperspektiv.",
    example: "Om kunden förlorar 30 timmar administration varje månad kan väntan i tre månader bli dyrare än ett avgränsat startprojekt.",
    related: ["Alternativkostnad", "Brådska", "Risk", "Beslutsargument"]
  },
  {
    id: "essay-trovardighet-nystartat",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM6",
    question: "Hur kan ett nystartat eller fiktivt bolag bli trovärdigt inför kund?",
    tags: ["Trovärdighet", "Referenser", "Pilot", "Risk"],
    answer: "Ett bra svar erkänner trovärdighetsproblemet och minskar kundens risk. Det kan göras med tydlig scope, pilot, CV/kompetens, certifieringar, referenser, demo, transparent process och tydliga avtal.",
    why: "Grupparbeten blir ofta svaga när de låtsas att kunden redan litar på bolaget. Här tränar du på att hantera den invändningen.",
    example: "Bolaget kan erbjuda en betald förstudie eller pilot med fast pris och tydlig leverans innan kunden binder sig till ett större projekt.",
    related: ["Pilot", "Referenser", "Scope", "Riskreducering"]
  },
  {
    id: "essay-kundens-riskfragor",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM6",
    question: "Vilka frågor bör kunden ställa innan de köper, och hur bör bolaget svara?",
    tags: ["Kundfrågor", "Risk", "Avtal", "Ekonomi"],
    answer: "Ett starkt svar tar kundens perspektiv: vad kostar det, vad ingår, vem ansvarar, hur mäts effekt, vad händer om scope ändras, hur hanteras data och vad händer efter leverans? Bolagets svar ska minska risk med tydliga avtal, mätetal och leveransplan.",
    why: "Det här tränar dig att tänka som en köpare, vilket ofta ger bättre affärssvar än att bara beskriva säljarens erbjudande.",
    example: "Kunden kan fråga: vad händer om integrationen inte fungerar? Ett bra svar är en testfas, tydliga acceptanskriterier och ändringshantering.",
    related: ["Kundrisk", "Avtal", "Mätbar effekt", "Efterleverans"]
  },
  {
    id: "essay-hallbar-affar",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Examinatorrisk/AM1-AM6",
    question: "Resonera om vad som gör affären hållbar för både kund och bolag.",
    tags: ["Hållbar affär", "Kundnytta", "Lönsamhet", "Långsiktighet"],
    answer: "En hållbar affär skapar verklig nytta för kunden och rimlig lönsamhet för bolaget. Den ska vara tydligt avgränsad, etisk, levererbar och långsiktig, så att kunden får effekt och bolaget inte säljer något som förstör marginal, förtroende eller kvalitet.",
    why: "Den här frågan binder ihop affärsmannaskapets kärna: bra affär för båda parter.",
    example: "Ett för billigt fastpris kan se bra ut för kunden men bli ohållbart om bolaget inte kan leverera kvalitet utan att tappa pengar.",
    related: ["Kundnytta", "Lönsamhet", "Etik", "Långsiktighet"]
  },
  {
    id: "essay-presentation-roda-traden",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "Grupparbete",
    question: "Bygg en röd tråd för en presentation från problem till ekonomi, analys och avtal.",
    tags: ["Presentation", "Röd tråd", "Grupparbete", "Helhet"],
    answer: "Ett starkt svar börjar med kundproblem och målgrupp, går vidare till erbjudande och kundnytta, visar analysen bakom valet, förklarar affärsmodell och ekonomi och avslutar med risk, avtal och mätbar effekt.",
    why: "Om frågan blir essäliknande behöver du kunna strukturera ett helt svar, inte bara kunna separata modeller.",
    example: "Problem: manuell administration. Lösning: M365-automation. Analys: PESTELID/SWOT visar behov. Ekonomi: projektpris plus support. Avtal: scope, DPA och SLA. Effekt: sparad tid.",
    related: ["Kundproblem", "Affärsmodell", "Ekonomi", "Avtal"]
  },
  {
    id: "essay-helhetscase",
    mode: "examinatorrisk",
    type: "open",
    category: "Examinatorrisk",
    source: "AM1-AM6",
    question: "Miniessä: motivera ett IT-konsultbolag från kundproblem till erbjudande, analys, ekonomi, avtal och mätbar effekt.",
    tags: ["Helhetscase", "Kundnytta", "Analys", "Ekonomi", "Avtal"],
    answer: "Ett bra minessä-svar har en röd tråd: tydligt kundproblem, avgränsat kundsegment, värdeerbjudande, analys som motiverar valet, affärsmodell och ekonomi som håller, avtal som hanterar risk och KPI:er som visar effekt.",
    why: "Det här är bankens mest tentanära fråga. Kan du svara på den kan du väva ihop stora delar av kursen.",
    example: "Ett M365-bolag hjälper små organisationer automatisera onboarding. SWOT/PESTELID visar behov och risker, BMC visar affärsmodellen, budgeten visar lönsamhet, avtalen hanterar data och scope, KPI mäter sparad tid.",
    related: ["BMC", "SWOT", "Budget", "Avtal", "KPI"]
  }
];
