// AUTO-GENERATED by scripts/build-25q-questions.ts — do not edit by hand.
// Source: 25q.md (Kort sammanfattning + Fördjupning & Exempel)
// Generated: 2026-06-19T06:59:40.697Z

import type { TentaprioQuestion } from './questions';

export const TENTAPRIO_QUESTIONS: TentaprioQuestion[] = [
  {
    id: "tentaprio-1",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Förklara vad balans- och resultaträkning innehåller och vad man kan utläsa ur dessa",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 1"],
    answer: `Balansräkningen visar företagets ekonomiska ställning (tillgångar, skulder och eget kapital) vid en viss tidpunkt, medan resultaträkningen visar företagets intäkter, kostnader och resultat under en viss period.`,
    why: `**Balansräkningen** innehåller:

* tillgångar, exempelvis kassa, kundfordringar, lager, inventarier och immateriella tillgångar.  
* eget kapital.  
* långfristiga och kortfristiga skulder.

Balansräkningen balanserar enligt principen: Tillgångar = eget kapital + skulder. Ur balansräkningen kan man bland annat utläsa hur verksamheten är finansierad, hur stora skulder den har, hur mycket eget kapital som finns och om det finns tillräckliga omsättningstillgångar för att betala kortfristiga skulder. Den används exempelvis för att beräkna soliditet och kassalikviditet.  
**Resultaträkningen** visar förenklat:

* Nettoomsättning - rörelsekostnader = rörelseresultat, EBIT.  
* Rörelseresultat +/- finansiella poster = resultat efter finansiella poster.  
* Resultat efter finansiella poster - skatt = årets resultat.

Ur resultaträkningen kan man utläsa om verksamheten går med vinst eller förlust, vilka kostnader som är stora och om kärnverksamheten är lönsam. Omsättningen ensam räcker därför inte för att bedöma hur företaget mår.`,
    originalNumber: 1,
    examArea: 1,
  },
  {
    id: "tentaprio-2",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Hur räknar man ut kassalikviditet och soliditet? Vad visar de?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 2"],
    answer: `Kassalikviditet mäter företagets förmåga att betala kortfristiga skulder på kort sikt, medan soliditet mäter andelen eget kapital av de totala tillgångarna för att visa den långsiktiga finansiella styrkan.`,
    why: `* **Kassalikviditet** = (omsättningstillgångar - varulager - pågående arbeten) / kortfristiga skulder × 100. Ett värde på 100 procent innebär förenklat att de snabbt tillgängliga omsättningstillgångarna motsvarar de kortfristiga skulderna. Ett värde under 100 procent kan signalera likviditetsrisk, men bedömningen beror på bransch och betalningsvillkor.  
* **Soliditet** = eget kapital / totala tillgångar × 100. Högre soliditet innebär normalt större långsiktig motståndskraft och mindre beroende av lån, medan låg soliditet gör företaget känsligare för förluster och ränteförändringar. Som en generell riktpunkt för god soliditet anges 30-40 procent i föreläsningen.`,
    originalNumber: 2,
    examArea: 1,
  },
  {
    id: "tentaprio-3",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "För vilka gäller marknadsföringslagen och vad gäller den för?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 3"],
    answer: `Marknadsföringslagen gäller vid marknadsföring (som reklam och försäljningskontakter) till både privata, offentliga och kommersiella mottagare. Den skyddar konsumenter och näringsidkare genom att kräva tydlighet och förbjuda vilseledande eller aggressiva metoder.`,
    why: `Lagen gäller marknadsföring av produkter i bred mening, exempelvis:

* varor.  
* tjänster.  
* fast egendom.  
* arbetstillfällen och andra nyttigheter.

Lagen omfattar alla åtgärder som syftar till att förbättra försäljningen eller tillgången till en produkt. Den kan även omfatta företagets agerande före, under och efter försäljningen, exempelvis information om villkor och reklamationsrätt.`,
    originalNumber: 3,
    examArea: 1,
  },
  {
    id: "tentaprio-4",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Beskriv tre företagsformer och vad som kännetecknar dessa",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 4"],
    answer: `En enskild näringsverksamhet drivs av en fysisk person med personligt ansvar. Ett handelsbolag drivs av minst två personer med personligt och solidariskt ansvar. Ett aktiebolag är en egen juridisk person där ägarnas risk normalt begränsas till insatt kapital.`,
    why: `* **Enskild näringsverksamhet:** Har inget kapitalkrav, är enkel att starta och företaget är inte en separat juridisk person från ägaren.  
* **Handelsbolag:** Är en juridisk person, men det solidariska ansvaret innebär att en fordringsägare kan kräva hela skuldbeloppet av en enda av bolagsmännen (som sedan internt får lösa fördelningen med de andra).  
* **Aktiebolag:** Kräver minst 25 000 kronor i aktiekapital för ett privat bolag, ska ha en styrelse och måste lämna in årsredovisning. För ett konsultbolag med flera ägare och viss affärsrisk är detta ofta det rimligaste valet då det ger tydligare ägarstruktur och begränsat personligt ansvar.`,
    originalNumber: 4,
    examArea: 1,
  },
  {
    id: "tentaprio-5",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Vad är TB, vad står det för och vad ingår i begreppet?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 5"],
    answer: `TB står för täckningsbidrag och visar hur mycket en produkt eller ett projekt bidrar med rent ekonomiskt efter att de direkta/rörliga kostnaderna har dragits av från försäljningsintäkten.`,
    why: `* Formel: TB = försäljningsintäkt - rörliga eller direkta kostnader.  
* Exempel: Om ett projekt säljs för 180 000 kr, och de direkta konsultkostnaderna och licenserna ligger på 105 000 kr, blir TB 75 000 kr.  
* TB ska först och främst täcka företagets gemensamma fasta kostnader (exempelvis ledning, administration och kontor). Det som sedan återstår bidrar till vinsten, varför TB inte är detsamma som projektets slutgiltiga vinst.  
* Täckningsgrad (TG) visar TB i procent av intäkten: TG = TB / försäljningsintäkt × 100. I fallet ovan blir TG cirka 41,7 procent.`,
    originalNumber: 5,
    examArea: 1,
  },
  {
    id: "tentaprio-6",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Beskriv delarna i offentlig upphandling och hur processen går till",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 6"],
    answer: `Offentlig upphandling är en formell inköpsprocess som sträcker sig från en behovsanalys och annonsering, via inlämnade anbud och strikt utvärdering, fram till ett tilldelningsbeslut och avtalstecknande.`,
    why: `De viktigaste stegen i processen är:

1. **Behovsanalys och marknadsdialog (RFI):** Organisationen identifierar behov, planerar och samlar in marknadsinformation.  
2. **Upphandlingsdokument och annonsering:** Kravspecifikation, avtalsutkast och utvärderingsmodell tas fram och publiceras i ett upphandlingssystem så leverantörer får tillgång till det.  
3. **Frågor, svar och anbud:** Leverantörer kan ställa förtydligande frågor som besvaras likvärdigt, varpå anbud lämnas in inom en tidsfrist.  
4. **Prövning och utvärdering:** Krav på leverantören prövas och obligatoriska krav kontrolleras. Godkända anbud utvärderas enligt en angiven modell (t.ex. bästa förhållandet mellan pris och kvalitet).  
5. **Tilldelningsbeslut, avtalsspärr och avtal:** Kunden meddelar vinnaren. Efter en avtalsspärr (där konkurrenter kan begära överprövning) tecknas slutligen avtal och leveransen kan inledas och sedan följas upp.`,
    originalNumber: 6,
    examArea: 1,
  },
  {
    id: "tentaprio-7",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Vilka fyra delar består en årsredovisning av?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 7"],
    answer: `Enligt kursens förenklade modell består årsredovisningen alltid av fyra specifika delar: förvaltningsberättelse, resultaträkning, balansräkning och revisionsberättelse.`,
    why: `* **Förvaltningsberättelse:** Verksamhetens egen löptext som beskriver viktiga händelser, utveckling och risker under det gångna året.  
* **Resultaträkning:** En sammanställning som visar företagets intäkter, kostnader och resultat under räkenskapsåret.  
* **Balansräkning:** En ögonblicksbild som visar tillgångar, eget kapital och skulder på balansdagen.  
* **Revisionsberättelse:** Revisorns uttalande angående årsredovisningen, dess anmärkningar och frågan om ansvarsfrihet. *I mer fullständiga årsredovisningar kan även noter och kassaflödesanalys ingå, men på tentan ska man fokusera på den fyrdelade mallen*.`,
    originalNumber: 7,
    examArea: 1,
  },
  {
    id: "tentaprio-8",
    mode: "tentaprio",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "25q.md",
    question: "Vad är EBIT och var hittar man det?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio 25","Fråga 8"],
    answer: `EBIT (Earnings Before Interest and Taxes) visar rörelseresultatet, alltså hur lönsam den operativa kärnverksamheten är, före finansiella poster och skatt. Siffran återfinns i resultaträkningen.`,
    why: `* Förenklad uträkning: Nettoomsättning - verksamhetens rörelsekostnader = EBIT (rörelseresultat).  
* Det är ett centralt mått när man vill jämföra olika företags prestationer med varandra, eftersom det isolerar kärnverksamhetens lönsamhet utan att lån, räntor och skatt påverkar bilden.  
* Till skillnad från begreppet EBITDA dras av- och nedskrivningar av för att räkna ut EBIT.

## **BLOCK B – KUNDBEARBETNING & KUNDRELATION**`,
    originalNumber: 8,
    examArea: 1,
  },
  {
    id: "tentaprio-9",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad ingår i modellen 5P och hur använder vi den?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 9"],
    answer: `5P-modellen används för att analysera ett paketerat erbjudande i sin helhet och består av: Produkt, Pris, Plats, Påverkan och Personal.`,
    why: `Det räcker inte med en bra produkt om kunden inte hittar den eller om personalens bemötande brister. För ett IT-bolag kan 5P se ut så här:

* **Produkt:** Ett paketerat automationsprojekt.  
* **Pris:** Fast pris för förstudien, kombinerat med abonnemang för förvaltning.  
* **Plats:** Digital försäljning och leverans som kompletteras med kundmöten.  
* **Påverkan:** Att använda LinkedIn, kundcase och webinarier för kommunikation.  
* **Personal:** Konsulter som besitter både teknisk kompetens och stark verksamhetsförståelse.`,
    originalNumber: 9,
    examArea: 2,
  },
  {
    id: "tentaprio-10",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Förklara och ge exempel på differentiering och positionering relaterat till IT-branschen",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 10"],
    answer: `Differentiering är de faktiska och konkreta skillnaderna i erbjudandet jämfört med konkurrenterna, medan positionering handlar om hur företaget vill bli uppfattat i målgruppens medvetande.`,
    why: `* **Differentiering (vad företaget gör):** Företaget skapar skillnader i sin produkt, tjänst, image eller personal. Ett IT-konsultbolag kan exempelvis bygga in processkartläggning och utbildning av personalen, istället för att bara sälja en renodlad teknisk installation.  
* **Positionering (hur företaget upplevs):** Företaget bygger en mental plats hos kunden kopplat till exempelvis prestanda, pris eller enkelhet. Det nämnda konsultbolaget kanske positionerar sig som "den verksamhetsnära automationspartnern för mindre organisationer" snarare än den billigaste leverantören på marknaden. En lyckad positionering måste alltid stödjas av verklig differentiering.`,
    originalNumber: 10,
    examArea: 2,
  },
  {
    id: "tentaprio-11",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad ingår i begreppet FAB? Vad betyder det och vad innebär det?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 11"],
    answer: `FAB står för Features (egenskaper), Advantages (fördelar) och Benefits (kundnytta). Modellen används av säljare för att omvandla tekniska specifikationer till konkreta argument utifrån det kunden faktiskt värderar.`,
    why: `* **Features:** Vad lösningen har för egenskaper eller funktioner. (Exempel: Systemet har ett automatiserat attestflöde.)  
* **Advantages:** Vad egenskapen medför i praktiken. (Exempel: Färre dokument skickas manuellt och statusen blir fullt synlig.)  
* **Benefits:** Den konkreta effekten eller nyttan för kunden. (Exempel: Kunden sparar arbetstid, minskar felmarginaler och får snabbare godkännanden.) För att nyttan (Benefits) ska fungera måste den kopplas till det kunden faktiskt efterfrågar, vilket gör en genomförd behovsanalys avgörande.`,
    originalNumber: 11,
    examArea: 2,
  },
  {
    id: "tentaprio-12",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad betyder USP och ESP, vad skiljer dem åt? Ge exempel",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 12"],
    answer: `USP (Unique Selling Proposition) är ett rationellt, konkret och särskiljande försäljningsargument. ESP (Emotional Selling Proposition) fokuserar istället på ett känslomässigt argument, som att sälja in en känsla av trygghet eller status.`,
    why: `Skillnaden ligger i att en USP betonar funktion eller nytta, medan ESP betonar känsla.

* **USP-exempel inom IT:** "Vi bygger hela lösningen direkt i er befintliga Microsoft 365-miljö, vilket minskar behovet av nya och dyra licenser."  
* **ESP-exempel inom IT:** "Ni får full kontroll över er digitalisering och slipper vara beroende av riskfyllda och ångestfyllda IT-projekt." De fungerar allra bäst tillsammans, men båda måste ha hög trovärdighet.`,
    originalNumber: 12,
    examArea: 2,
  },
  {
    id: "tentaprio-13",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad ingår i begreppet paketering? Ge exempel från IT-branschen",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 13"],
    answer: `Paketering innebär att man samlar separata produkter och tjänster i ett begripligt helhetserbjudande med definierat innehåll, fastställt pris och tydlig kundnytta. Det underlättar kundens köpprocess.`,
    why: `* Ett välbyggt paket innehåller tydliga delar, funktioner, prismodell (exempelvis abonnemang), avgränsningar och en specifik målgrupp.  
* Genom att paketera flyttar man ofta kundens fokus från priset på enskilda konsulttimmar till värdet av den samlade lösningen, vilket också kan öka marginalerna.  
* **IT-exempel:** Ett konsultbolag erbjuder "Start" (processkartläggning), "Införande" (datamigrering och test) samt "Förvaltning" (ett fast månadsabonnemang för support). Även Microsoft 365 är ett exempel där program säljs som ett sammanhållet paket istället för var för sig.`,
    originalNumber: 13,
    examArea: 2,
  },
  {
    id: "tentaprio-14",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad ligger i begreppet marknadsföring?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 14"],
    answer: `Marknadsföring är processen att förstå marknadens behov och att kommunicera ett relevant värdeerbjudande till rätt målgrupp, med syfte att bygga relationer och driva försäljning.`,
    why: `Begreppet omfattar mycket mer än att bara "göra reklam". I kursen bygger marknadsföringen bland annat på:

* målgruppsstrategi och kundlöfte.  
* differentiering, paketering och positionering.  
* val av kanaler, från bred "one-to-many" (t.ex. annonser) till personlig "one-to-one" (t.ex. kundbesök).  
* koppling till försäljning och kundrelation.

*Exempel: Ett IT-bolag identifierar verksamhetschefer som en nyckelmålgrupp, positionerar sig som en verksamhetsnära automationspartner, publicerar ett skräddarsytt kundcase och bjuder in till webinar där de sedan följer upp intressenter i sin pipeline*.`,
    originalNumber: 14,
    examArea: 2,
  },
  {
    id: "tentaprio-15",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad innehåller begreppet konsultmässighet?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 15"],
    answer: `Konsultmässighet innebär att bygga förtroende genom ett professionellt och ansvarstagande uppträdande. Det bygger på att kunden inte bara köper teknisk kompetens, utan också verksamhetsförståelse och god kommunikationsförmåga.`,
    why: `Konsultmässighet innefattar bland annat:

* God förståelse för ekonomi, kundvärde och verksamheten som helhet.  
* Tydlig kommunikation, integritet och förmåga att bygga relationer och visa respekt för sekretess.  
* Självständighet, att hålla tider och överenskommelser.  
* Mod att rapportera risker i tid. (Exempel: Om ett projekt riskerar att bli försenat väntar inte den konsultmässiga medarbetaren till leveransdagen. Istället informeras kunden tidigt med en presentation av orsak, konsekvenser och lösningsförslag.)`,
    originalNumber: 15,
    examArea: 2,
  },
  {
    id: "tentaprio-16",
    mode: "tentaprio",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "25q.md",
    question: "Vad är en marknadsplan? Ge exempel på aktiviteter",
    tags: ["Kundbearbetning & kundrelation","Tentaprio 25","Fråga 16"],
    answer: `En marknadsplan är en strukturerad karta som beskriver exakt hur organisationen ska använda marknadsföring och kommunikation för att ta sig från nuläget till sina mätbara mål.`,
    why: `Den strategiska planen kan innehålla:

* Nulägesanalys, målgrupper och positionering.  
* Budskap, kundlöften och kanalval.  
* Tidplan, ansvariga, budget och uppföljning via KPI:er.

Dessa byggstenar realiseras sedan i konkreta aktiviteter, exempelvis:

* Mässor, webinarier och föreläsningar.  
* Kundbesök, annonsering och sökordsoptimering.  
* Kundcase, utskick och närvaro i sociala medier.

## **BLOCK C – FÖRSÄLJNING & FÖRHANDLINGSTEKNIK**`,
    originalNumber: 16,
    examArea: 2,
  },
  {
    id: "tentaprio-17",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Beskriv utförligt de huvudsakliga stegen i den generella säljprocessen",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 17"],
    answer: `Säljprocessen är en systematisk väg från planering och kontaktskapande, via kartläggning av behov och lösningspresentation, fram till förhandling, avslut och överlämning till produktion. Processen hindrar säljaren från att rusa in med offerter för tidigt.`,
    why: `Processens viktigaste steg:

1. **Planering och identifikation:** Välj målgrupp, sätt mål och kvalificera prospekt med matchande behov.  
2. **Kontakt och bearbetning:** Etablera en första kontakt (t.ex. cold calls) med sikte på ett möte.  
3. **Behovsanalys och förberedelser:** Förstå köparrollerna, lyssna aktivt och kartlägg kundens problem.  
4. **Lösningsförslag och argumentation:** Översätt behoven till ett kundanpassat förslag och visa det ur kundens perspektiv med trovärdiga argument.  
5. **Invändningshantering och förhandling:** Bemöt tvivel konstruktivt, förhandla villkor och arbeta mot win-win.  
6. **Avslut och överlämning:** Hjälp kunden fatta beslut, teckna avtal och se till att leveransavdelningen förstår förväntningarna innan löpande uppföljning tar vid.`,
    originalNumber: 17,
    examArea: 3,
  },
  {
    id: "tentaprio-18",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Förklara SPIN-modellen och ge minst två frågor per område",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 18"],
    answer: `SPIN är en frågemodell optimerad för komplex försäljning och står för Situationsfrågor, Problemfrågor, Inverkansfrågor och Nyttofrågor. Den hjälper säljaren utveckla och fördjupa kundens behov i samtalet innan lösningen presenteras.`,
    why: `* **S - Situationsfrågor:** Förstå nuläget. *"Hur hanterar ni kundärenden i dag?" "Vilka system använder ni och hur integreras de?"*  
* **P - Problemfrågor:** Upptäck missnöje och friktion. *"Vilka problem uppstår när information registreras på flera ställen?" "Var i processen uppstår mest förseningar?"*  
* **I - Inverkansfrågor:** Förstå konsekvenserna av problemen. *"Vad kostar dubbelarbetet er i förlorad tid under en månad?" "Hur påverkas kunden när ett ärende blir försenat?"*  
* **N - Nyttofrågor:** Låter kunden själv bygga upp värdet av en lösning. *"Vad skulle det innebära för er om ni bara hade ett system för allt?" "Vilken nytta får ni om handläggningstiden minskar med 30 procent?"*`,
    originalNumber: 18,
    examArea: 3,
  },
  {
    id: "tentaprio-19",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Ge minst fem exempel på vad som är viktigt vid förhandlingsteknik",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 19"],
    answer: `Vid förhandling är det helt centralt att ha tydliga förberedda mål, att förstå vad motparten verkligen värderar, och att alltid söka långsiktiga win-win-lösningar där du byter eftergifter istället för att ge bort dem.`,
    why: `Minst fem viktiga principer är:

* Förbered dina egna mål, smärtgränser och förstå motpartens dolda behov.  
* Säkerställ att du sitter med rätt beslutsfattare som har mandat.  
* Sträva efter win-win men våga säga nej till upplägg som gör affären olönsam.  
* Kräv alltid något tillbaka för varje eftergift (om kunden vill ha rabatt, kräv då snabbare betalningsvillkor i utbyte).  
* Våga vara tyst för att ge utrymme och verka samtidigt inte för desperat.  
* Använd kalla fakta och tänk i banor av givande och tagande (småsaker för dig kan vara guld värda för motparten).`,
    originalNumber: 19,
    examArea: 3,
  },
  {
    id: "tentaprio-20",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Vid strategisk, komplex försäljning kan man identifiera fyra olika köparroller. Vilka är de, hur kan de påverka och vad vill man uppnå genom att identifiera dem?",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 20"],
    answer: `De fyra rollerna är den Ekonomiska köparen (hanterar budget), den Tekniska köparen (granskar krav), Användarköparen (arbetar i lösningen) och Guiden (hjälper säljaren internt). Kartläggningen görs för att veta vem som fattar beslut och vilka argument var och en behöver höra.`,
    why: `* **Ekonomisk köpare:** Har slutligt budgetansvar och bedömer affärsnytta, investering och risk.  
* **Teknisk köpare:** Kan ofta fälla affären (även utan eget budgetansvar) om tekniska regler, säkerhetskrav eller inköpsregler bryts.  
* **Användarköpare:** Utvärderar funktionen. Bryr sig om hur deras egen vardag kommer förändras och förenklas.  
* **Guide:** Personen på insidan (eller med insyn) som hjälper säljaren att förstå företagets dolda beslutsprocesser och relationer.

Genom att förstå dessa roller (som ibland är samlade hos en enda person) vet säljaren vem som kan säga ja, vem som kan säga nej, och hur beslut faktiskt går till i organisationen.`,
    originalNumber: 20,
    examArea: 3,
  },
  {
    id: "tentaprio-21",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Ge två exempel på hur jag kan hantera invändningar",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 21"],
    answer: `När invändningar dyker upp måste säljaren ta reda på grundorsaken bakom dem. Det kan göras antingen genom att erkänna invändningen och leda samtalet tillbaka till värdet, eller genom att ställa motfrågor för att förstå oron.`,
    why: `* **Exempel 1 - Erkänn invändningen och ta tillbaka initiativet:** Säljaren avfärdar inte kunden, utan validerar oron innan man byter perspektiv till nyttan. *Kund: "Det verkar dyrt." Säljare: "Jag förstår att investeringen är högre än tänkt. Låt oss gå igenom kostnadsdrivarna och jämföra det med den enorma tidsbesparing vi räknade fram nyss."*  
* **Exempel 2 - Vänd tillbaka en fråga:** Säljaren försöker isolera det verkliga problemet för att anpassa sin lösning. *Kund: "Vi vet inte om vi hinner med införandet." Säljare: "Vilken del av införandet ser ut att bli svårast för er att bemanna?"*`,
    originalNumber: 21,
    examArea: 3,
  },
  {
    id: "tentaprio-22",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Beskriv två metoder för att få till ett avslut på en säljprocess",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 22"],
    answer: `Ett professionellt säljavslut hjälper kunden att fatta beslut. Två metoder är "Alternativavslut" (ge två konkreta val) och "Direkt frågeavslut" (fråga rakt ut om kunden är redo).`,
    why: `* **Alternativavslut:** Säljaren ger kunden två realistiska tidsramar eller paket som båda leder till en affär. *Exempel: "Vill ni starta pilotprojektet i april eller passar maj bättre?"* Detta hjälper kunden att ta ett naturligt steg utan att låsas till en massiv "ja eller nej"-fråga.  
* **Direkt frågeavslut:** Säljaren agerar tydligt. *Exempel: "Utifrån det vi har gått igenom, är ni redo att godkänna förstudien och boka ett startmöte?"* Detta kräver en väl genomförd behovsanalys och tydliga köpsignaler i botten. *Oavsett teknik måste avslutet resultera i en väldokumenterad order som kan lämnas över korrekt till de som ska bygga och leverera tjänsten*.`,
    originalNumber: 22,
    examArea: 3,
  },
  {
    id: "tentaprio-23",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Beskriv innehållet i och nyttan med tratten eller pipeline för mig som säljare",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 23"],
    answer: `En säljtratt (pipeline) synliggör affärsmöjligheter i olika steg (från lead till avslut) och används som säljarens främsta verktyg för att prioritera rätt aktiviteter, hitta flaskhalsar och prognostisera framtida intäkter.`,
    why: `Tratten visar bland annat steg som: skapa leads, kvalificera prospekt, boka möte, skicka lösningsförslag och att stänga affären. Som säljare drar jag bland annat denna nytta av modellen:

* Jag får överblick över var jag ska investera min tid och vem som ansvarar för nästa steg.  
* Jag kan identifiera var affärer fastnar (t.ex. om många möten bokas men få offerter skickas, kan behovsanalysen i mötet behöva vässas).  
* En möjlighet är inte bara ett namn; den innehåller sannolikhet, affärsvärde, nästa aktivitet och en säljare.`,
    originalNumber: 23,
    examArea: 3,
  },
  {
    id: "tentaprio-24",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "Beskriv tre olika typer av frågor du kan använda i mötet med kunden",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 24"],
    answer: `En bra behovsanalys blandar öppna frågor (får kunden att berätta mer), slutna frågor (bekräftar saklig fakta) och alternativfrågor (lotsar kunden att ta ställning till olika vägar framåt).`,
    why: `* **Öppna frågor:** Ställs primärt tidigt i behovsanalysen då säljaren söker förståelse. Börjar på vad, hur, när, vem osv. (Exempel: "Hur hanterar ni kundärenden i dag?")  
* **Slutna / ledande frågor:** Svaras med ett enkelt ja eller nej. Dessa bör användas sparsamt då de stryper en diskussion, men är bra för att förtydliga missförstånd. (Exempel: "Är det korrekt att dubbelregistreringen tar ungefär två timmar?")  
* **Alternativfrågor:** Hjälper kunden fatta avgränsade beslut och för samtalet i hamn. (Exempel: "Vill ni börja med en mindre pilot eller slå till på en förstudie?")`,
    originalNumber: 24,
    examArea: 3,
  },
  {
    id: "tentaprio-25",
    mode: "tentaprio",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "25q.md",
    question: "På vilket sätt skiljer sig Insight Selling från andra säljmodeller?",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio 25","Fråga 25"],
    answer: `I traditionell försäljning frågar säljaren efter ett färdigt behov och matchar det mot en lösning. I Insight Selling tillför säljaren värde genom att proaktivt utmana kundens världsbild och lära dem upptäcka dolda problem och möjligheter.`,
    why: `Insight Selling positionerar säljaren mer som rådgivare och partner tidigt i processen genom att:

* Agera tankeväckare med branschinsikter och nya perspektiv.  
* Flytta diskussionen från verktyg till verksamhetsnytta.  
* **Exempel:** Kunden ber om ett nytt rapportverktyg för snyggare layouter. En Insight-säljare visar att layouten egentligen inte är problemet, utan att den underliggande datakvaliteten brister i organisationen. Diskussionen och affären flyttas därmed från ett billigt utseendeverktyg till ett omfattande informationsflödesprojekt.`,
    originalNumber: 25,
    examArea: 3,
  }
];
