// AUTO-GENERATED by scripts/build-tenta-questions.ts — do not edit by hand.
// Sources: instuderingsfragor-affarsmannaskap.md, tentaprio-25.md
// Generated: 2026-06-19T06:42:46.131Z

import type { TentaQuestion } from './questions';

export const TENTA_EXAM_INFO = {
  areas: [
    { id: 1 as const, label: "Företagsekonomi & avtalsrätt", questionsOnExam: 6, passAt: 4 },
    { id: 2 as const, label: "Kundbearbetning & kundrelation", questionsOnExam: 6, passAt: 4 },
    { id: 3 as const, label: "Försäljning & förhandlingsteknik", questionsOnExam: 8, passAt: 5 },
  ],
  answerGuide: [
    "Förklara vad begreppet eller modellen betyder",
    "Redogör för hur det används eller varför det är viktigt",
    "Sätt svaret i ett affärsmässigt sammanhang",
    "Ge ett relevant exempel när frågan efterfrågar det",
  ],
  priorityCount: 25,
  totalCount: 61,
} as const;

export const TENTA_QUESTIONS: TentaQuestion[] = [
  {
    id: "tenta-5",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, avsnitten om balansräkning och resultaträkning.",
    question: "Förklara vad balans- och resultaträkning innehåller och vad man kan utläsa ur dessa",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★★","Prio 1"],
    answer: `**Balansräkningen** visar företagets ekonomiska ställning vid en viss tidpunkt. Den innehåller:

- tillgångar, exempelvis kassa, kundfordringar, lager, inventarier och immateriella tillgångar,
- eget kapital,
- långfristiga och kortfristiga skulder.

Balansräkningen balanserar enligt principen:

> Tillgångar = eget kapital + skulder

Ur balansräkningen kan man bland annat utläsa hur verksamheten är finansierad, hur stora skulder den har, hur mycket eget kapital som finns och om det finns tillräckliga omsättningstillgångar för att betala kortfristiga skulder. Den används exempelvis för att beräkna soliditet och kassalikviditet.

**Resultaträkningen** visar företagets intäkter och kostnader under en viss period, exempelvis ett år. Förenklat ser den ut så här:

> Nettoomsättning - rörelsekostnader = rörelseresultat, EBIT  
> Rörelseresultat +/- finansiella poster = resultat efter finansiella poster  
> Resultat efter finansiella poster - skatt = årets resultat

Ur resultaträkningen kan man utläsa om verksamheten går med vinst eller förlust, vilka kostnader som är stora och om kärnverksamheten är lönsam. Omsättningen ensam räcker därför inte för att bedöma hur företaget mår.`,
    originalNumber: 5,
    examArea: 1,
    isPriority: true,
    priorityOrder: 1,
    priorityLevel: "high",
  },
  {
    id: "tenta-7",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, \"Likviditet\" och \"Soliditet\".",
    question: "Hur räknar man ut kassalikviditet och soliditet? Vad visar de?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★★","Prio 2"],
    answer: `**Kassalikviditet** visar företagets kortsiktiga betalningsförmåga, alltså om verksamheten kan betala sina kortfristiga skulder med relativt snabbt tillgängliga tillgångar.

Formeln är:

> Kassalikviditet = (omsättningstillgångar - varulager - pågående arbeten) / kortfristiga skulder × 100

Ett värde på 100 procent innebär förenklat att de snabbt tillgängliga omsättningstillgångarna motsvarar de kortfristiga skulderna. Ett värde under 100 procent kan signalera likviditetsrisk, men bedömningen måste göras utifrån bransch, betalningsvillkor och kvaliteten på exempelvis kundfordringar.

**Soliditet** visar hur stor del av företagets tillgångar som är finansierade med eget kapital i stället för skulder.

Den förenklade formeln i kursen är:

> Soliditet = eget kapital / totala tillgångar × 100

Högre soliditet innebär normalt större långsiktig motståndskraft och mindre beroende av lån. Låg soliditet kan göra företaget mer känsligt för förluster och ränteförändringar. I föreläsningen anges 30-40 procent som en generell riktpunkt för en god soliditet, men vad som är bra varierar mellan branscher och företagets utvecklingsfas.

Kort sagt: **kassalikviditet handlar om att överleva på kort sikt, medan soliditet handlar om långsiktig finansiell styrka.**`,
    answerSummary: `**Kassalikviditet** visar företagets kortsiktiga betalningsförmåga, alltså om verksamheten kan betala sina kortfristiga skulder med relativt snabbt tillgängliga tillgångar.`,
    originalNumber: 7,
    examArea: 1,
    isPriority: true,
    priorityOrder: 2,
    priorityLevel: "high",
  },
  {
    id: "tenta-55",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 9.",
    question: "För vilka gäller marknadsföringslagen och vad gäller den för?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★★","Prio 3"],
    answer: `Marknadsföringslagen skyddar konsumenter och näringsidkare och är relevant vid marknadsföring till såväl privata som offentliga och kommersiella mottagare.

Den gäller marknadsföring av produkter i bred mening, exempelvis:

- varor,
- tjänster,
- fast egendom,
- arbetstillfällen,
- andra nyttigheter.

Den omfattar reklam, försäljningskontakter och andra åtgärder som syftar till att förbättra försäljningen eller tillgången till en produkt. Även företagets agerande före, under och efter försäljningen kan omfattas, exempelvis information om villkor och reklamationsrätt.

Marknadsföringen ska bland annat vara tydlig och får inte vara vilseledande eller aggressiv.`,
    answerSummary: `Marknadsföringslagen skyddar konsumenter och näringsidkare och är relevant vid marknadsföring till såväl privata som offentliga och kommersiella mottagare.`,
    originalNumber: 55,
    examArea: 1,
    isPriority: true,
    priorityOrder: 3,
    priorityLevel: "high",
  },
  {
    id: "tenta-12",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 3 och företagsformer 2025.",
    question: "Beskriv tre företagsformer och vad som kännetecknar dessa",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★","Prio 4"],
    answer: `### Enskild näringsverksamhet

En enskild näringsverksamhet drivs av en fysisk person. Ägaren är personligt ansvarig för företagets ekonomi och skulder. Det finns inget kapitalkrav och formen är relativt enkel att starta och administrera. Företaget är inte en separat juridisk person på samma sätt som ett aktiebolag.

### Handelsbolag

Ett handelsbolag startas av minst två bolagsmän. Handelsbolaget är en juridisk person, men bolagsmännen har personligt och solidariskt ansvar för företagets skulder. Solidariskt ansvar innebär att en fordringsägare kan kräva hela beloppet av en av bolagsmännen, som sedan får reglera fördelningen internt.

### Aktiebolag

Ett aktiebolag kan startas av en eller flera ägare och är en egen juridisk person. Bolaget ansvarar normalt för sina skulder och ägarnas risk är i grunden begränsad till satsat kapital. Ett privat aktiebolag kräver minst 25 000 kronor i aktiekapital, ska ha styrelse och lämna årsredovisning till Bolagsverket.

För ett konsultbolag med flera ägare och viss affärsrisk är aktiebolag ofta ett rimligt val eftersom det ger tydligare ägarstruktur och begränsat personligt ansvar. Valet måste dock även väga in administration, skatt, finansiering och trovärdighet.`,
    originalNumber: 12,
    examArea: 1,
    isPriority: true,
    priorityOrder: 4,
    priorityLevel: "medium",
  },
  {
    id: "tenta-29",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, avsnittet om projektekonomi.",
    question: "Vad är TB, vad står det för och vad ingår i begreppet?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★","Prio 5"],
    answer: `TB står för **täckningsbidrag**. Det visar hur mycket en produkt, tjänst eller ett projekt bidrar med efter att de direkta eller rörliga kostnaderna har dragits av.

> TB = försäljningsintäkt - rörliga eller direkta kostnader

TB ska först täcka företagets fasta och gemensamma kostnader, exempelvis ledning, administration, kontor, sälj och system. Det som därefter återstår bidrar till vinst.

**Exempel:** Ett projekt säljs för 180 000 kronor. Direkta konsultkostnader och projektunika licenser är 105 000 kronor. TB blir 75 000 kronor. Det är inte samma sak som projektets slutliga vinst, eftersom företagets fasta kostnader också ska täckas.

**Täckningsgrad, TG**, visar TB i procent av intäkten:

> TG = TB / försäljningsintäkt × 100

I exemplet blir TG cirka 41,7 procent.`,
    answerSummary: `TB står för **täckningsbidrag**. Det visar hur mycket en produkt, tjänst eller ett projekt bidrar med efter att de direkta eller rörliga kostnaderna har dragits av.`,
    originalNumber: 29,
    examArea: 1,
    isPriority: true,
    priorityOrder: 5,
    priorityLevel: "medium",
  },
  {
    id: "tenta-57",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 7 och 1-AllDocuments.",
    question: "Beskriv delarna i offentlig upphandling och hur processen går till",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★","Prio 6"],
    answer: `En förenklad offentlig upphandlingsprocess kan beskrivas så här:

1. **Behovsanalys och planering:** den upphandlande organisationen identifierar behov, omfattning, budget, marknad och lämpligt förfarande.
2. **Marknadsdialog eller RFI:** kunden kan samla information från marknaden innan kraven låses.
3. **Upphandlingsdokument:** kunden tar fram kravspecifikation, kommersiella villkor, kvalificeringskrav, tilldelningskriterier, utvärderingsmodell och avtalsutkast.
4. **Annonsering:** upphandlingen publiceras i ett upphandlingssystem och leverantörerna får tillgång till dokumenten.
5. **Frågor och svar:** leverantörer kan begära förtydliganden inom angiven tid. Svaren ska hanteras så att leverantörerna behandlas likvärdigt.
6. **Anbud:** leverantören lämnar sitt anbud inom tidsfristen och måste följa formkrav och instruktioner.
7. **Prövning av leverantör:** kunden bedömer bland annat uteslutningsgrunder och om leverantören uppfyller kvalificeringskraven.
8. **Prövning av anbud:** obligatoriska krav kontrolleras. Anbud som inte uppfyller dem kan behöva förkastas.
9. **Utvärdering:** godkända anbud jämförs enligt den i förväg angivna modellen, exempelvis pris eller bästa förhållandet mellan pris och kvalitet.
10. **Tilldelningsbeslut:** kunden meddelar vilken leverantör som ska tilldelas avtalet och varför.
11. **Avtalsspärr och möjlig överprövning:** avtal tecknas normalt inte direkt. Leverantörer kan ansöka om överprövning om de anser att reglerna har brutits och att de lidit eller riskerar att lida skada.
12. **Avtal och leverans:** när processen är klar tecknas avtalet. Vid ramavtal kan kommande uppdrag ske genom avrop.
13. **Uppföljning:** kunden följer upp att leverantören och leveransen uppfyller avtalet.

Leverantören måste analysera både möjligheten att vinna och förmågan att leverera. Det räcker inte att bara erbjuda ett lågt pris.`,
    originalNumber: 57,
    examArea: 1,
    isPriority: true,
    priorityOrder: 6,
    priorityLevel: "medium",
  },
  {
    id: "tenta-18",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, \"Årsredovisning\".",
    question: "Vilka fyra delar består en årsredovisning av?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★★","Prio 7"],
    answer: `Enligt kursens förenklade modell består årsredovisningen av:

1. **Förvaltningsberättelse:** verksamhetens egen beskrivning av viktiga händelser, utveckling och risker under året.
2. **Resultaträkning:** visar intäkter, kostnader och resultat under räkenskapsåret.
3. **Balansräkning:** visar tillgångar, eget kapital och skulder på balansdagen.
4. **Revisionsberättelse:** revisorns uttalande och eventuella anmärkningar, bland annat om årsredovisningen och ansvarsfrihet.

I fullständiga årsredovisningar förekommer även noter och ibland kassaflödesanalys. På tentan bör man dock följa lärarens uttryckliga fyrdelning när frågan ber om de fyra delarna.`,
    originalNumber: 18,
    examArea: 1,
    isPriority: true,
    priorityOrder: 7,
    priorityLevel: "medium",
  },
  {
    id: "tenta-34",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, \"Resultaträkning\".",
    question: "Vad är EBIT och var hittar man det?",
    tags: ["Företagsekonomi & avtalsrätt","Tentaprio ★","Prio 8"],
    answer: `EBIT betyder **Earnings Before Interest and Taxes**, på svenska rörelseresultat före finansiella poster och skatt.

Förenklat:

> Nettoomsättning - verksamhetens rörelsekostnader = EBIT/rörelseresultat

EBIT visar hur lönsam den operativa kärnverksamheten är innan finansieringen och skatten påverkar resultatet. Därför är det användbart när man vill jämföra verksamhetens prestation utan att skillnader i lån och skatt får samma betydelse.

EBIT finns i **resultaträkningen**, vanligtvis på raden rörelseresultat. Det ska inte blandas ihop med EBITDA, som dessutom ligger före av- och nedskrivningar.`,
    answerSummary: `EBIT betyder **Earnings Before Interest and Taxes**, på svenska rörelseresultat före finansiella poster och skatt.`,
    originalNumber: 34,
    examArea: 1,
    isPriority: true,
    priorityOrder: 8,
    priorityLevel: "low",
  },
  {
    id: "tenta-15",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2.",
    question: "Vad ingår i modellen 5P och hur använder vi den?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★★","Prio 9"],
    answer: `Kursens 5P består av:

- **Produkt:** vad kunden erbjuds, exempelvis en tjänst, produkt eller kombination.
- **Pris:** vad kunden betalar och vilken prismodell som används.
- **Plats:** var och genom vilka distributions- eller leveranskanaler erbjudandet når kunden.
- **Påverkan:** hur företaget kommunicerar, marknadsför och påverkar målgruppen.
- **Personal:** människorna som säljer, levererar och representerar erbjudandet.

Modellen används för att analysera erbjudandet som en helhet. Det räcker inte att ha en bra produkt om priset är fel, kunden inte hittar den, marknadsföringen är otydlig eller personalen saknar rätt kompetens och bemötande.

**Exempel för ett IT-bolag:**

- Produkt: ett paketerat automationsprojekt.
- Pris: fast pris för förstudie och abonnemang för förvaltning.
- Plats: digital försäljning och leverans, kompletterad med kundmöten.
- Påverkan: LinkedIn, webinarier, kundcase och rekommendationer.
- Personal: konsulter med både teknisk kompetens och verksamhetsförståelse.`,
    originalNumber: 15,
    examArea: 2,
    isPriority: true,
    priorityOrder: 9,
    priorityLevel: "high",
  },
  {
    id: "tenta-20",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2.",
    question: "Förklara och ge exempel på differentiering och positionering relaterat till IT-branschen",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★★","Prio 10"],
    answer: `**Differentiering** är de konkreta skillnader som gör att ett företag eller erbjudande inte blir helt jämförbart med konkurrenterna. Företaget kan differentiera sig genom produkt, tjänst, personal, image eller distributionskanal.

**Exempel:** Ett IT-konsultbolag skiljer sig genom att kombinera processkartläggning, Microsoft 365-kompetens och utbildning av kundens personal. Konkurrenterna kanske främst säljer teknisk implementation.

**Positionering** handlar om vilken plats företaget vill ta i målgruppens medvetande jämfört med andra alternativ. Positioneringen kan bygga på pris, kvalitet, enkelhet, anpassningsbarhet, prestanda, långsiktighet eller andra relevanta dimensioner.

**Exempel:** Samma konsultbolag positionerar sig som "den verksamhetsnära och lättillgängliga automationspartnern för mindre organisationer", inte som den billigaste eller största leverantören.

Skillnaden är alltså att differentiering beskriver **vad som faktiskt skiljer erbjudandet**, medan positionering beskriver **hur företaget vill bli uppfattat**. En trovärdig positionering måste stödjas av verklig differentiering.`,
    answerSummary: `**Differentiering** är de konkreta skillnader som gör att ett företag eller erbjudande inte blir helt jämförbart med konkurrenterna. Företaget kan differentiera sig genom produkt, tjänst, personal, image eller distributionskanal.`,
    originalNumber: 20,
    examArea: 2,
    isPriority: true,
    priorityOrder: 10,
    priorityLevel: "high",
  },
  {
    id: "tenta-10",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2, avsnittet om erbjudandet.",
    question: "Vad ingår i begreppet FAB? Vad betyder det och vad innebär det?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★","Prio 11"],
    answer: `FAB står för:

- **Features:** egenskaper eller funktioner,
- **Advantages:** fördelar som egenskaperna ger,
- **Benefits:** den konkreta nyttan eller effekten för kunden.

Modellen används för att gå från en teknisk beskrivning till ett kundorienterat argument. Säljaren ska inte stanna vid vad lösningen innehåller, utan förklara varför det är viktigt för just kunden.

**Exempel:**

- Feature: Lösningen har ett automatiserat attestflöde i Power Automate.
- Advantage: Färre dokument behöver skickas manuellt och statusen blir synlig.
- Benefit: Kunden sparar arbetstid, minskar risken för borttappade ärenden och får snabbare godkännanden.

Benefits ska kopplas till sådant kunden faktiskt värderar, exempelvis tidsbesparing, lägre kostnad, minskad risk, högre kvalitet eller större trygghet. Därför kräver ett bra FAB-argument en genomförd behovsanalys.`,
    originalNumber: 10,
    examArea: 2,
    isPriority: true,
    priorityOrder: 11,
    priorityLevel: "medium",
  },
  {
    id: "tenta-23",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 10 och mastermaterialets begreppsavsnitt.",
    question: "Vad betyder USP och ESP, vad skiljer dem åt? Ge exempel",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★","Prio 12"],
    answer: `**USP, Unique Selling Proposition**, är ett tydligt och särskiljande försäljningsargument. Det beskriver en konkret anledning till att kunden ska välja just detta erbjudande framför alternativen.

**ESP, Emotional Selling Proposition**, är ett känslomässigt försäljningsargument. Det kopplar erbjudandet till en känsla som trygghet, kontroll, enkelhet, status eller framtidstro.

**IT-exempel:**

- USP: "Vi bygger lösningen direkt i kundens befintliga Microsoft 365-miljö, vilket minskar behovet av nya system och licenser."
- ESP: "Ni får kontroll över digitaliseringen och slipper känna att ni är beroende av ett svårt och riskfyllt IT-projekt."

Skillnaden är att USP främst betonar en rationell och särskiljande egenskap eller nytta, medan ESP betonar hur kunden ska känna. De fungerar bäst tillsammans och måste vara trovärdiga. Ett argument är inte unikt bara för att företaget kallar det unikt.`,
    answerSummary: `**USP, Unique Selling Proposition**, är ett tydligt och särskiljande försäljningsargument. Det beskriver en konkret anledning till att kunden ska välja just detta erbjudande framför alternativen.`,
    originalNumber: 23,
    examArea: 2,
    isPriority: true,
    priorityOrder: 12,
    priorityLevel: "medium",
  },
  {
    id: "tenta-17",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2, \"Paketering\".",
    question: "Vad ingår i begreppet paketering? Ge exempel från IT-branschen",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★","Prio 13"],
    answer: `Paketering innebär att samla produkter och tjänster i ett begripligt erbjudande med tydligt innehåll, pris och kundnytta. Ett paket kan innehålla:

- vilka delar och leveranser som ingår,
- funktioner, fördelar och nyttor,
- en tydlig prisbild,
- fast pris, abonnemang eller olika nivåer,
- avgränsningar och eventuella tillval,
- en bestämd målgrupp.

Paketering kan underlätta kundens köpprocess eftersom kunden lättare förstår vad som köps och vad det kostar. Det kan också ge bättre marginal, skapa merförsäljning och flytta fokus från enskilda konsulttimmar till värdet av en samlad lösning.

**IT-exempel:** Ett konsultbolag erbjuder:

- Start: processkartläggning och rekommendation.
- Införande: konfiguration, datamigrering, test och utbildning.
- Förvaltning: support, uppföljning och mindre förbättringar som månadsabonnemang.

Ett annat exempel är Microsoft 365 där flera program och tjänster säljs som ett sammanhållet paket i stället för var för sig.`,
    answerSummary: `Paketering innebär att samla produkter och tjänster i ett begripligt erbjudande med tydligt innehåll, pris och kundnytta. Ett paket kan innehålla:`,
    originalNumber: 17,
    examArea: 2,
    isPriority: true,
    priorityOrder: 13,
    priorityLevel: "medium",
  },
  {
    id: "tenta-61",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 9.",
    question: "Vad ligger i begreppet marknadsföring?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★","Prio 14"],
    answer: `Marknadsföring innebär att förstå marknaden och kunderna och att kommunicera ett relevant erbjudande till potentiella och befintliga kunder. I kursens modell bygger marknadsföringen på:

- strategi för produkter och tjänster,
- varumärkesplattform och kundlöfte,
- målgrupps- och kundstrategi,
- differentiering,
- paketering,
- positionering,
- val av budskap och kanaler,
- aktiviteter och uppföljning,
- koppling till försäljning och kundrelation.

Marknadsföring kan vara bred, exempelvis annonser och kunskapsinnehåll, eller personlig, exempelvis kundbesök och riktad kommunikation. Den omfattar mer än att synas. Syftet är att få rätt målgrupp att förstå erbjudandets värde och röra sig vidare mot relation, dialog eller köp.

**Exempel:** Ett IT-bolag identifierar verksamhetschefer i dokumentintensiva organisationer som målgrupp, positionerar sig som en verksamhetsnära automationspartner, publicerar ett relevant kundcase, bjuder in till webinar och följer upp intresserade deltagare i säljpipelinen.


---

## Snabb mall att använda på tentan

När du får en fråga som börjar med "beskriv", "förklara" eller "redogör", kan du bygga svaret så här:

1. **Definition:** "Begreppet betyder..."
2. **Innehåll:** "Det består av/fungerar genom..."
3. **Betydelse:** "Det är viktigt eftersom..."
4. **Exempel:** "I ett IT-konsultbolag kan det exempelvis..."
5. **Avgränsning:** "Det ska inte blandas ihop med..."

Ett kort men utvecklat svar enligt denna struktur är normalt starkare än en lång lista med ord utan förklaring.`,
    answerSummary: `Marknadsföring innebär att förstå marknaden och kunderna och att kommunicera ett relevant erbjudande till potentiella och befintliga kunder. I kursens modell bygger marknadsföringen på:`,
    originalNumber: 61,
    examArea: 2,
    isPriority: true,
    priorityOrder: 14,
    priorityLevel: "medium",
  },
  {
    id: "tenta-8",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 1, avsnitten om konsulten och konsultmässighet.",
    question: "Vad innehåller begreppet konsultmässighet?",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★★","Prio 15"],
    answer: `Konsultmässighet innebär att uppträda professionellt, ansvarstagande och förtroendeskapande i kundrelationen. Kunden köper inte bara teknisk kompetens, utan även konsultens förmåga att förstå verksamheten, kommunicera och ta ansvar.

Konsultmässighet kan bland annat innebära:

- god verksamhetskunskap och förståelse för ekonomi och kundvärde,
- kunskap om det egna företagets erbjudande,
- tydlig och anpassad kommunikation,
- helhetssyn och analytisk förmåga,
- professionalism, integritet och affärsmässighet,
- relationsbyggande och gott bemötande,
- självständighet och initiativförmåga,
- att hålla tider och överenskommelser,
- att rapportera risker och problem tidigt,
- att respektera sekretess och kundens information,
- att representera både sig själv och konsultföretaget på ett trovärdigt sätt.

**Exempel:** Om en migrering riskerar att bli försenad väntar en konsultmässig projektledare inte till leveransdagen. Projektledaren informerar kunden tidigt, beskriver orsaken, visar konsekvenserna och presenterar realistiska handlingsalternativ.`,
    answerSummary: `Konsultmässighet innebär att uppträda professionellt, ansvarstagande och förtroendeskapande i kundrelationen. Kunden köper inte bara teknisk kompetens, utan även konsultens förmåga att förstå verksamheten, kommunicera och ta ansvar.`,
    originalNumber: 8,
    examArea: 2,
    isPriority: true,
    priorityOrder: 15,
    priorityLevel: "medium",
  },
  {
    id: "tenta-42",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 9, \"Marknadsplan\".",
    question: "Vad är en marknadsplan? Ge exempel på aktiviteter",
    tags: ["Kundbearbetning & kundrelation","Tentaprio ★","Prio 16"],
    answer: `En marknadsplan beskriver hur organisationen ska använda marknadsföring och kommunikation för att nå sina mål. Den fungerar som en karta från nuläge till önskat resultat.

Den kan innehålla:

- nulägesanalys av produkt, tjänst, SWOT, kultur och identitet,
- syfte och mätbara mål,
- målgrupper,
- positionering och differentiering,
- budskap och kundlöfte,
- val av kanaler,
- aktiviteter, ansvariga, tidplan och budget,
- årshjul,
- koppling till försäljning och pipeline,
- uppföljning med KPI:er.

Exempel på aktiviteter är:

- mässor,
- webinarier,
- kundbesök,
- föreläsningar och kunskapsdelning,
- utskick,
- annonser,
- demonstrationer,
- sociala medier,
- kundcase och referenser,
- sökordsoptimering och webbplatsinnehåll.

**Exempel:** Ett IT-konsultbolag vill skapa tio kvalificerade möten med ekonomichefer. Det genomför ett webinar om automatiserad fakturahantering, annonserar mot målgruppen, följer upp deltagarna och mäter antal möten och affärsmöjligheter.`,
    answerSummary: `En marknadsplan beskriver hur organisationen ska använda marknadsföring och kommunikation för att nå sina mål. Den fungerar som en karta från nuläge till önskat resultat.`,
    originalNumber: 42,
    examArea: 2,
    isPriority: true,
    priorityOrder: 16,
    priorityLevel: "low",
  },
  {
    id: "tenta-38",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10 och 11.",
    question: "Beskriv utförligt de huvudsakliga stegen i den generella säljprocessen",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★★","Prio 17"],
    answer: `Den generella säljprocessen kan beskrivas så här:

1. **Säljplanering:** välj vilka kunder och segment som ska prioriteras, sätt mål, planera aktiviteter och bestäm hur arbetet ska följas upp.
2. **Identifiera kund eller prospekt:** hitta företag där det finns en möjlig matchning mellan behov och erbjudande. Samla information och kvalificera möjligheten.
3. **Kontakt och bearbetning:** ta kontakt genom exempelvis nätverk, social selling, cold call eller befintlig kundrelation. Målet är ofta att skapa ett relevant nästa steg, exempelvis ett möte.
4. **Förbered kundmötet:** förstå kunden, deltagarna, möjliga köparroller, mötets mål, agenda och dokumentation.
5. **Behovsanalys:** använd frågor och aktivt lyssnande för att förstå nuläge, problem, konsekvenser, mål och beslutslogik. SPIN kan användas vid komplex försäljning.
6. **Skapa lösningsförslag:** översätt behovet till en kundanpassad lösning med mål, omfattning, funktioner, tidplan, investering, värde, risk och avtalsfrågor.
7. **Presentera och argumentera:** visa lösningen ur kundens perspektiv. Använd trovärdiga och konkreta argument som kopplas till kundens uttalade behov.
8. **Hantera invändningar:** förstå vad som ligger bakom invändningen, exempelvis faktisk risk, missuppfattning eller taktiskt motiv, och besvara den konstruktivt.
9. **Förhandling:** förhandla pris, omfattning, ansvar, tid och andra villkor med tydliga mål och strävan efter en hållbar win-win-lösning.
10. **Avslut eller avstamp:** hjälp kunden att fatta beslut, bekräfta överenskommelsen och teckna avtal. I vissa affärer blir detta ett avstamp för nästa beslut snarare än ett enda slutligt avslut.
11. **Överlämning till leverans:** säkerställ att genomförandeorganisationen förstår vad som har sålts, vad som lovats och vilka förväntningar kunden har.
12. **Uppföljning och relationsutveckling:** stäm av efter leverans, hantera avvikelser, fråga om kunden är nöjd och identifiera nya behov.

Processen är inte alltid helt linjär, men den hindrar säljaren från att hoppa direkt från första kontakt till en generell offert.`,
    originalNumber: 38,
    examArea: 3,
    isPriority: true,
    priorityOrder: 17,
    priorityLevel: "high",
  },
  {
    id: "tenta-52",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"SPIN\".",
    question: "Förklara SPIN-modellen och ge minst två frågor per område",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★★","Prio 18"],
    answer: `SPIN är en frågemodell för komplex försäljning. Bokstäverna står för Situation, Problem, Inverkan och Nytta. Modellen hjälper säljaren att utveckla kundens behov innan lösningen presenteras.

### S - Situationsfrågor

Kartlägger nuläget och bakgrunden.

- "Hur hanterar ni kundärenden i dag?"
- "Vilka system använder ni och hur är de integrerade?"

### P - Problemfrågor

Gör problem, svårigheter och missnöje tydliga.

- "Vilka problem uppstår när information registreras i flera system?"
- "Var i processen uppstår flest förseningar eller fel?"

### I - Inverkansfrågor

Undersöker konsekvenserna och gör problemets betydelse tydlig.

- "Vad kostar dubbelarbetet i tid under en vanlig månad?"
- "Hur påverkas kunden och personalen när ett ärende blir fel eller försenat?"

### N - Nyttofrågor

Får kunden att formulera värdet av en förbättring eller lösning.

- "Vad skulle det innebära för er om hela flödet kunde hanteras i ett system?"
- "Vilken nytta skulle ni få om handläggningstiden kunde minskas med 30 procent?"

Grundidén är att gå från indirekta behov, exempelvis missnöje och problem, till tydliga och specifika behov som kunden själv uttrycker. Säljaren ska inte mekaniskt förhöra kunden, utan lyssna och anpassa följdfrågorna.`,
    answerSummary: `SPIN är en frågemodell för komplex försäljning. Bokstäverna står för Situation, Problem, Inverkan och Nytta. Modellen hjälper säljaren att utveckla kundens behov innan lösningen presenteras.`,
    originalNumber: 52,
    examArea: 3,
    isPriority: true,
    priorityOrder: 18,
    priorityLevel: "high",
  },
  {
    id: "tenta-50",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 11, \"Förhandling\".",
    question: "Ge minst fem exempel på vad som är viktigt vid förhandlingsteknik",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★★","Prio 19"],
    answer: `Viktiga principer är:

1. **Förbered tydliga mål:** bestäm önskat resultat, lägsta acceptabla nivå och vilka frågor som är förhandlingsbara.
2. **Förstå motpartens behov och motiv:** ta reda på vad som är viktigt, inklusive dolda eller indirekta intressen.
3. **Förhandla med rätt beslutsfattare:** säkerställ att personen har mandat eller att beslutsvägen är känd.
4. **Sträva efter win-win:** sök en lösning som båda parter kan leva med och som stödjer en långsiktig relation.
5. **Kräv något tillbaka för varje eftergift:** ge inte rabatt eller ändrade villkor utan motprestation.
6. **Våga vara tyst:** tystnad ger motparten utrymme att tänka och minskar risken att man förhandlar mot sig själv.
7. **Våga säga nej:** acceptera inte villkor som gör affären olönsam eller orimligt riskfylld.
8. **Använd fakta och var trovärdig:** argumentera sakligt och underskatta inte motparten.
9. **Verka inte alltför angelägen:** ett desperat intryck försvagar förhandlingsläget.
10. **Tänk i givande och tagande:** oviktiga detaljer för dig kan ha värde för motparten och användas som eftergifter.

**Exempel:** Kunden vill ha 10 procent rabatt. Leverantören kan svara att priset kan sänkas om kunden accepterar längre avtalstid, standardiserad leverans eller snabbare betalningsvillkor. Då blir eftergiften ett byte, inte en ensidig förlust.`,
    originalNumber: 50,
    examArea: 3,
    isPriority: true,
    priorityOrder: 19,
    priorityLevel: "high",
  },
  {
    id: "tenta-19",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"Strategisk försäljning\".",
    question: "Vid strategisk, komplex försäljning kan man identifiera fyra olika köparroller. Vilka är de, hur kan de påverka och vad vill man uppnå genom att identifiera dem?",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★","Prio 20"],
    answer: `De fyra köparrollerna är:

- **Ekonomisk köpare:** har den slutliga ekonomiska beslutskraften eller kontrollerar budgeten. Rollen bedömer investering, risk, affärsnytta och kostnad.
- **Teknisk köpare:** granskar krav, teknik, avtal, säkerhet eller inköpsregler. Rollen kan ofta stoppa ett köp om lösningen inte uppfyller krav, även om den inte alltid fattar det slutliga affärsbeslutet.
- **Användarköpare:** ska använda lösningen eller påverkas direkt av den. Rollen värderar funktion, användbarhet och hur vardagen förändras.
- **Guide:** en person som hjälper säljaren att förstå organisationen, beslutsprocessen, relationerna och eventuella hinder. Guiden kan vara intern hos kunden eller på annat sätt ha god insyn.

Rollerna kan finnas hos olika personer, men en person kan också bära flera roller. Genom att identifiera dem kan säljaren förstå:

- vem som kan säga ja,
- vem som kan säga nej,
- vilka behov och argument som är viktiga för varje roll,
- vilka personer som måste involveras,
- hur beslutet faktiskt fattas.

**Exempel:** Vid försäljning av ett nytt ärendehanteringssystem kan ekonomichefen vara ekonomisk köpare, IT-säkerhetschefen teknisk köpare, handläggarna användarköpare och en verksamhetsutvecklare fungera som guide. Ett förslag som bara övertygar handläggarna kan ändå stoppas av säkerhetskrav eller budgetbeslut.`,
    originalNumber: 19,
    examArea: 3,
    isPriority: true,
    priorityOrder: 20,
    priorityLevel: "medium",
  },
  {
    id: "tenta-49",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 11, \"Hantera invändningar\".",
    question: "Ge två exempel på hur jag kan hantera invändningar",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★","Prio 21"],
    answer: `Först bör säljaren ta reda på vad som ligger bakom invändningen. Det kan vara en faktisk orsak, en missuppfattning, osäkerhet, ett personligt motiv eller ett taktiskt förhandlingsdrag.

### Exempel 1: Erkänn invändningen och ta tillbaka initiativet

Kund: "Det här verkar dyrare än vi hade tänkt oss."  
Säljare: "Jag förstår att investeringen är högre än er första uppskattning. Låt oss därför gå igenom vilka delar som driver kostnaden och jämföra dem med den tidsbesparing och riskminskning ni sa var viktigast."

Säljaren avfärdar inte kunden, men leder samtalet tillbaka till värde och fakta.

### Exempel 2: Vänd tillbaka en fråga

Kund: "Vi är osäkra på om organisationen hinner med införandet."  
Säljare: "Vilken del av införandet tror ni blir svårast att bemanna?"  

Frågan hjälper säljaren att hitta den verkliga orsaken och anpassa lösningen, exempelvis genom en mindre pilot, annan tidplan eller mer utbildningsstöd.

En invändning kan också skjutas upp om den behandlas bättre senare i presentationen, men säljaren ska då tydligt lova att återkomma.`,
    answerSummary: `Först bör säljaren ta reda på vad som ligger bakom invändningen. Det kan vara en faktisk orsak, en missuppfattning, osäkerhet, ett personligt motiv eller ett taktiskt förhandlingsdrag.`,
    originalNumber: 49,
    examArea: 3,
    isPriority: true,
    priorityOrder: 21,
    priorityLevel: "medium",
  },
  {
    id: "tenta-51",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 11, \"Tekniker för avslut\".",
    question: "Beskriv två metoder för att få till ett avslut på en säljprocess",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★","Prio 22"],
    answer: `### Alternativavslut

Säljaren ger kunden två realistiska alternativ som båda innebär ett nästa steg.

**Exempel:** "Vill ni starta pilotprojektet i april eller passar maj bättre?"  

Metoden hjälper kunden att ta ställning utan att frågan bara blir ett stort ja eller nej. Alternativen måste vara ärliga och kunden ska vara redo för beslutet.

### Direkt frågeavslut

Säljaren frågar tydligt om kunden vill gå vidare.

**Exempel:** "Utifrån det vi har gått igenom, är ni redo att godkänna förstudien och boka startmötet?"

Ett tydligt avslut ska bygga på tidigare behovsanalys, acceptans och köpsignaler. Andra tekniker i kursen är självklarhetsavslut, låsning, testperiod och användning av referenser.

Avslutet är inte bara att få en underskrift. Överenskommelsen ska dokumenteras och lämnas över korrekt till genomförandeorganisationen. Annars riskerar säljaren att lova något som leveransen inte kan uppfylla.`,
    originalNumber: 51,
    examArea: 3,
    isPriority: true,
    priorityOrder: 22,
    priorityLevel: "medium",
  },
  {
    id: "tenta-32",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"Pipeline - Tratt\".",
    question: "Beskriv innehållet i och nyttan med tratten eller pipeline för mig som säljare",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★★","Prio 23"],
    answer: `En sales pipeline eller säljtratt visar affärsmöjligheterna i olika steg från första kontakt till avslutad affär. Kursens exempel innehåller:

- skapa leads,
- kvalificera prospekt,
- säljbesök eller möte,
- offert- eller lösningsförslag,
- stänga affären.

Kundens sida av tratten kan beskrivas som medvetenhet, intresse, avsikt, övervägande och beslut.

Som säljare använder jag pipelinen för att:

- se hur många affärsmöjligheter som finns i varje steg,
- prioritera tid och aktiviteter,
- skilja verkliga prospekt från svaga leads,
- se var affärerna fastnar,
- planera nästa aktivitet och ansvarig person,
- uppskatta framtida försäljning,
- följa konvertering och förbättra säljarbetet.

**Exempel:** Om företaget har många leads men nästan inga bokade möten kan problemet ligga i kvalificering, budskap eller kontaktmetod. Om många offerter skickas men få affärer stängs kan behovsanalys, värdeargumentation eller förhandling behöva förbättras.

En pipeline är alltså inte bara en lista över kontakter. Varje möjlighet ska ha ett tydligt steg, sannolikhet, värde, nästa aktivitet och ägare.`,
    answerSummary: `En sales pipeline eller säljtratt visar affärsmöjligheterna i olika steg från första kontakt till avslutad affär. Kursens exempel innehåller:`,
    originalNumber: 32,
    examArea: 3,
    isPriority: true,
    priorityOrder: 23,
    priorityLevel: "medium",
  },
  {
    id: "tenta-36",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, avsnitten om frågetyper.",
    question: "Beskriv tre olika typer av frågor du kan använda i mötet med kunden",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★","Prio 24"],
    answer: `### Öppna frågor

Öppna frågor får kunden att berätta och börjar ofta med vad, hur, när, var, vem, vilka eller varför.

**Exempel:** "Hur hanterar ni kundärenden i dag?"  
De passar tidigt i behovsanalysen när säljaren behöver förstå situation och problem.

### Slutna eller ledande frågor

De används för att bekräfta något och kan ofta besvaras med ja eller nej. De ska användas sparsamt eftersom de kan stänga samtalet.

**Exempel:** "Är det korrekt att dubbelregistreringen tar ungefär två timmar per dag?"

### Alternativfrågor

Alternativfrågor hjälper kunden att ta ställning mellan tydliga alternativ och kan föra samtalet framåt.

**Exempel:** "Vill ni börja med en mindre pilot i april eller en full förstudie i maj?"

Andra användbara typer är utmanande frågor och acceptansfrågor. Oavsett frågetyp ska säljaren lyssna aktivt, använda tystnad och undvika att mötet känns som ett förhör.`,
    originalNumber: 36,
    examArea: 3,
    isPriority: true,
    priorityOrder: 24,
    priorityLevel: "low",
  },
  {
    id: "tenta-53",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 11, \"Insight selling\".",
    question: "På vilket sätt skiljer sig Insight Selling från andra säljmodeller?",
    tags: ["Försäljning & förhandlingsteknik","Tentaprio ★","Prio 25"],
    answer: `Insight Selling bygger på att säljaren eller konsulten hjälper kunden att upptäcka utmaningar, möjligheter och perspektiv som kunden inte redan har formulerat. Säljaren tillför alltså värde genom sin kunskap och sina idéer redan under säljprocessen.

I en mer traditionell behovsbaserad modell frågar säljaren främst efter ett känt behov och kopplar en lösning till det. I Insight Selling går säljaren längre genom att:

- utmana kundens nuvarande sätt att tänka,
- visa nya affärsmöjligheter eller risker,
- bidra med branschkunskap och nya perspektiv,
- påverka beslutsprocessen tidigt,
- agera rådgivare och partner i stället för enbart leverantör.

**Exempel:** Kunden efterfrågar ett nytt rapportverktyg. En insight-säljare visar att huvudproblemet egentligen inte är rapporternas utseende utan bristande datakvalitet och dubbla datakällor. Diskussionen flyttas därför från att köpa ett verktyg till att förbättra hela informationsflödet.

Metoden kan ge starkare relation, tydligare differentiering och större kundvärde. Den kräver dock verklig kompetens och respekt; att bara motsäga kunden är inte Insight Selling.`,
    answerSummary: `Insight Selling bygger på att säljaren eller konsulten hjälper kunden att upptäcka utmaningar, möjligheter och perspektiv som kunden inte redan har formulerat. Säljaren tillför alltså värde genom sin kunskap och sina idéer redan under säljprocessen.`,
    originalNumber: 53,
    examArea: 3,
    isPriority: true,
    priorityOrder: 25,
    priorityLevel: "low",
  },
  {
    id: "tenta-1",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 9, avsnittet om marknadsföringslagen.",
    question: "Vilka målgrupper omfattas av marknadsföringslagen?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Marknadsföringslagen ska skydda både **konsumenter och näringsidkare** mot otillbörlig marknadsföring. Den är alltså relevant både när ett företag marknadsför sig mot privatpersoner, B2C, och när marknadsföringen riktas mot andra företag eller offentliga organisationer, B2B.

Lagen omfattar marknadsföring av produkter i bred mening, exempelvis varor, tjänster, fast egendom, arbetstillfällen och andra nyttigheter. Den gäller inte bara annonser, utan även försäljning och andra kontakter som syftar till att öka försäljningen eller tillgången till en produkt. Företagets agerande före, under och efter försäljningen kan omfattas.

**Exempel:** Ett IT-bolag får inte marknadsföra ett abonnemang som "helt gratis i tre månader" om kunden samtidigt måste betala en obligatorisk medlems- eller startavgift som inte framgår tydligt.`,
    answerSummary: `Marknadsföringslagen ska skydda både **konsumenter och näringsidkare** mot otillbörlig marknadsföring. Den är alltså relevant både när ett företag marknadsför sig mot privatpersoner, B2C, och när marknadsföringen riktas mot andra företag eller offentliga organisationer, B2B.`,
    originalNumber: 1,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-2",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 4 och mastermaterialets avsnitt om företagsplattformen.",
    question: "Beskriv begreppen vision, mission och värderingar",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `**Visionen** beskriver det långsiktiga önskade läget och vart verksamheten strävar. Den ska skapa inspiration, motivation och riktning samt fungera som stöd för beslut och prioriteringar. En vision ska vara mer långsiktig och inspirerande än ett vanligt verksamhetsmål.

**Missionen** beskriver varför verksamheten finns och vilket övergripande bidrag den ska ge till kunder eller samhälle. Den förklarar hur företaget arbetar mot visionen och vilket grundläggande värde det skapar.

**Värderingarna** beskriver vad organisationen står för och vilka beteenden som ska prägla arbetet. De ska inte bara vara fina ord, utan påverka hur medarbetare fattar beslut, samarbetar, leder och bemöter kunder.

**Exempel för ett IT-konsultbolag:**

- Vision: "Smart digitalisering ska vara möjlig även för organisationer utan en stor IT-avdelning."
- Mission: "Vi förenklar kundernas administration genom användbara Microsoft 365- och automationslösningar."
- Värderingar: tydlighet, ansvar och lärande. Tydlighet kan exempelvis innebära att kunden alltid får veta status, risker och nästa steg.

Tillsammans med affärsidén bildar dessa delar företagets gemensamma plattform.`,
    answerSummary: `**Visionen** beskriver det långsiktiga önskade läget och vart verksamheten strävar. Den ska skapa inspiration, motivation och riktning samt fungera som stöd för beslut och prioriteringar. En vision ska vara mer långsiktig och inspirerande än ett vanligt verksamhetsmål.`,
    originalNumber: 2,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-3",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 4 och mastermaterialets begreppsavsnitt.",
    question: "Vad ligger i begreppet affärsidé?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `En affärsidé beskriver **vad företaget erbjuder, till vem och vilken nytta erbjudandet skapar**. Den ska ge en praktisk bild av vad verksamheten gör i vardagen och varför kunder ska vilja betala för det.

En tydlig affärsidé brukar därför besvara frågor som:

- Vilket kundproblem eller behov löser vi?
- Vilken målgrupp riktar vi oss till?
- Vilken produkt eller tjänst erbjuder vi?
- Hur skapar vi värde och hur skiljer vi oss från alternativen?
- Hur kan verksamheten bli kommersiellt hållbar?

**Exempel:** "Vi hjälper små och medelstora organisationer att kartlägga, automatisera och förbättra administrativa arbetsflöden i Microsoft 365." Här framgår både målgruppen, erbjudandet och kundnyttan.

Affärsidén är mer konkret och verksamhetsnära än visionen. Visionen beskriver vart företaget vill nå på lång sikt, medan affärsidén beskriver vad företaget gör för att ta sig dit.`,
    answerSummary: `En affärsidé beskriver **vad företaget erbjuder, till vem och vilken nytta erbjudandet skapar**. Den ska ge en praktisk bild av vad verksamheten gör i vardagen och varför kunder ska vilja betala för det.`,
    originalNumber: 3,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-4",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"Olika roller inom sälj i konsultvärlden\".",
    question: "Ge exempel på olika roller inom sälj i konsultvärlden",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `I konsultvärlden kan säljansvaret vara fördelat på flera roller:

- **Säljchef:** har ofta det övergripande ansvaret för försäljningen inom företaget eller ett affärsområde. Säljchefen sätter mål, följer upp resultat och leder säljarbetet.
- **Konsultchef:** ansvarar för en konsultgrupp, dess budget och beläggning och kan därför också ha ett säljansvar.
- **KAM, Key Account Manager:** är kundkontoansvarig för strategiskt viktiga kunder. Rollen fokuserar på den långsiktiga relationen och på att utveckla fler affärer hos nyckelkunden.
- **Säljare:** arbetar direkt med hela eller stora delar av säljprocessen, från uppsökande kontakt och behovsanalys till offert, förhandling och avslut. Därefter lämnas affären ofta över till leveransorganisationen.
- **Affärskonsult eller projektledare:** kan behöva sälja in nya uppdrag, utveckla befintliga kunder och ansvara för sin egen beläggning och budget.

I en mindre konsultorganisation kan samma person ha flera roller. En projektledare kan exempelvis både identifiera ett kundbehov, utforma lösningen, delta i förhandlingen och sedan leda leveransen.`,
    originalNumber: 4,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-6",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 1, kursbeskrivningen och mastermaterialets röda tråd.",
    question: "Vad innehåller begreppet affärsmannaskap?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `Affärsmannaskap innebär att förstå kundens behov, skapa ett tydligt kundvärde och samtidigt fatta kommersiellt kloka beslut för den egna verksamheten. Det handlar om att få ihop **kundnytta, relation, leverans, risk och lönsamhet**.

Begreppet omfattar bland annat att:

- förstå kundens verksamhet, mål, behov och beslutsprocess,
- översätta tekniska egenskaper till konkret affärsnytta,
- förstå det egna företagets erbjudande, kostnader, pris och marginal,
- bedöma avtal, ansvar och kommersiella risker,
- bygga förtroende och långsiktiga kundrelationer,
- se helheten i stället för att bara optimera sin egen del,
- fatta beslut som är bra både för kunden och leverantören.

**Exempel:** Ett IT-bolag säljer inte bara ett automatiserat flöde. Det visar hur lösningen minskar dubbelarbete, sparar tid, minskar fel och kan ge en rimlig återbetalning på investeringen. Samtidigt säkerställer bolaget att pris, omfattning och avtal gör leveransen lönsam och hanterbar.

Affärsmannaskap är alltså mer än försäljning. En affär är inte bra om kunden inte får värde, leveransen inte fungerar eller leverantören förlorar pengar.`,
    answerSummary: `Affärsmannaskap innebär att förstå kundens behov, skapa ett tydligt kundvärde och samtidigt fatta kommersiellt kloka beslut för den egna verksamheten. Det handlar om att få ihop **kundnytta, relation, leverans, risk och lönsamhet**.`,
    originalNumber: 6,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-9",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 6, avsnittet om avtalsnivåer.",
    question: "Vad innebär det att vi har tecknat ett ramavtal med en kund?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Ett ramavtal reglerar de övergripande ramarna för ett framtida samarbete, exempelvis priser, avtalsvillkor, ansvar, kompetenskrav och hur beställningar får göras. De konkreta uppdragen beställs därefter genom **avrop** inom ramavtalet.

Att ett konsultbolag har tecknat ramavtal innebär därför normalt att bolaget är en godkänd leverantör enligt ramens villkor. Det betyder däremot inte automatiskt att bolaget har fått en garanterad försäljningsvolym. Försäljning uppstår först när kunden gör avrop eller när leverantören vinner en avropsförfrågan.

**Exempel:** En kommun har ett ramavtal med tre IT-konsultbolag. När kommunen behöver en projektledare gör den ett avrop enligt ramavtalets regler. Avropet anger det konkreta uppdraget, tidsperioden och kompetensbehovet.

Ramavtalet minskar behovet av att förhandla alla grundvillkor från början vid varje uppdrag, men leverantören måste fortfarande förstå avropsordningen och konkurrensen mellan ramavtalsleverantörerna.`,
    answerSummary: `Ett ramavtal reglerar de övergripande ramarna för ett framtida samarbete, exempelvis priser, avtalsvillkor, ansvar, kompetenskrav och hur beställningar får göras. De konkreta uppdragen beställs därefter genom **avrop** inom ramavtalet.`,
    originalNumber: 9,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-11",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 3 och arbetsmallen BMC, PESTELID, SWOT, Ansoff.",
    question: "Vad ingår i en PESTLIED-omvärldsanalys och hur kan man använda den som verktyg?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `PESTLIED används för att analysera yttre faktorer som företaget inte helt kan styra:

- **P - Politiska faktorer:** politiska beslut, offentlig finansiering och styrning.
- **E - Ekonomiska faktorer:** konjunktur, räntor, inflation, investeringsvilja och valutaläge.
- **S - Sociala faktorer:** värderingar, beteenden, arbetsliv och samhällstrender.
- **T - Tekniska eller teknologiska faktorer:** ny teknik, digitalisering, AI och teknisk utveckling.
- **L - Legala faktorer:** lagar, regler, avtal och myndighetskrav.
- **I - Internationella faktorer:** globala marknader, geopolitik och internationell konkurrens.
- **E - Environment/miljö:** klimat, resursanvändning och miljökrav.
- **D - Demografiska faktorer:** befolkning, ålder, utbildningsnivå och kompetenstillgång.

Verktyget används genom att identifiera relevanta faktorer, bedöma om påverkan är positiv eller negativ, hur stor den är och inom vilken tidsram den kan märkas. Därefter kopplas analysen till beslut.

**Exempel:** Ett IT-konsultbolag kan identifiera AI-utveckling som en teknologisk möjlighet, AI-regler och GDPR som legala krav, lågkonjunktur som ekonomisk risk och kompetensbrist som en demografisk utmaning. Resultatet kan leda till att bolaget erbjuder mindre pilotprojekt med tydligt business case i stället för stora och riskfyllda införanden.

PESTLIED ska alltså inte bara bli en lista. Nyttan uppstår när analysen leder till prioriteringar, riskhantering och förändringar i erbjudandet.`,
    originalNumber: 11,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-13",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, avsnittet om bearbetning och kontakt.",
    question: "Vad innebär cold calls eller canvasbesök?",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `**Cold calls** är uppsökande telefonsamtal till personer eller organisationer där det inte redan finns en etablerad kontakt eller pågående affärsdialog. Målet är ofta att väcka intresse, kvalificera kunden och boka ett möte, inte att genomföra hela försäljningen i det första samtalet.

**Canvasbesök** är motsvarande uppsökande aktivitet genom ett oanmält eller direkt fysiskt besök hos en potentiell kund.

För att lyckas behöver säljaren:

- ta reda på grundläggande information om kunden,
- ha ett tydligt budskap eller en kort hisspitch,
- veta vad målet med kontakten är,
- snabbt visa relevans för kunden,
- förbereda sig på vanliga invändningar,
- respektera kundens tid.

**Exempel:** En IT-konsult ringer en verksamhetschef och säger kort att bolaget hjälper dokumenttunga verksamheter att minska manuell administration. Målet är att boka ett 20-minuters möte om kundens nuvarande arbetsflöden, inte att sälja ett färdigt system direkt.`,
    answerSummary: `**Cold calls** är uppsökande telefonsamtal till personer eller organisationer där det inte redan finns en etablerad kontakt eller pågående affärsdialog. Målet är ofta att väcka intresse, kvalificera kunden och boka ett möte, inte att genomföra hela försäljningen i det första samtalet.`,
    originalNumber: 13,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-14",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, jämförelsen mellan företagsekonomi och projektekonomi.",
    question: "Vad är det för skillnad mellan företagsekonomi och projektekonomi?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `**Företagsekonomi** omfattar all ekonomi som rör hela företaget på kort och lång sikt. Där ingår alla intäkter, alla kostnader, investeringar, finansiering, likviditet, soliditet och företagets totala lönsamhet. Perspektivet gäller verksamheten tills vidare.

**Projektekonomi** avgränsas till ett bestämt projekt och en bestämd tidsperiod. Den omfattar projektets intäkter och direkta kostnader samt projektets bidrag till företagets fasta kostnader och vinst.

Ett centralt projektmått är:

> TB, täckningsbidrag = projektets intäkter - projektets rörliga eller direkta kostnader

**Exempel:** Ett IT-projekt säljs för 500 000 kronor. Konsulttid, resor och projektunika licenser kostar 320 000 kronor. Projektets TB blir 180 000 kronor. Bidraget ska hjälpa till att täcka företagets gemensamma kostnader, exempelvis administration, kontor, sälj och ledning, och därefter ge vinst.

Ett projekt kan alltså se lönsamt ut isolerat men ändå inte vara tillräckligt lönsamt för företaget om TB inte räcker till de fasta kostnaderna. Omvänt kan företagets totala ekonomi påverkas av flera projekt samtidigt.`,
    answerSummary: `**Företagsekonomi** omfattar all ekonomi som rör hela företaget på kort och lång sikt. Där ingår alla intäkter, alla kostnader, investeringar, finansiering, likviditet, soliditet och företagets totala lönsamhet. Perspektivet gäller verksamheten tills vidare.`,
    originalNumber: 14,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-16",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 7 och Mölndals Stads upphandlingsunderlag.",
    question: "Vilka beslutskriterier används vid offentlig upphandling?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `I kursmaterialet anges tre huvudsakliga grunder för tilldelning:

1. **Bästa förhållandet mellan pris och kvalitet:** anbudet bedöms utifrån både kostnad och kvalitativa mervärden.
2. **Kostnad:** bedömningen kan omfatta kostnadseffektivitet och exempelvis livscykelkostnad, inte bara inköpspriset.
3. **Pris:** vinnaren avgörs utifrån lägsta pris bland anbud som uppfyller kraven.

Vilka kriterier som används ska framgå av upphandlingsdokumenten. I en IT-upphandling kan kvalitet exempelvis bedömas genom funktionalitet, användbarhet, genomförandeplan, support, kompetens och leveransförmåga.

Det är viktigt att skilja mellan:

- **ska-krav**, som normalt måste uppfyllas för att anbudet ska gå vidare,
- **kvalificeringskrav**, som prövar leverantören,
- **tilldelningskriterier**, som används för att jämföra godkända anbud och välja vinnare.

**Exempel:** Två leverantörer uppfyller alla obligatoriska krav. Den billigaste behöver inte vinna om modellen är bästa förhållandet mellan pris och kvalitet och den andra leverantören får ett så stort kvalitetsmervärde att totalresultatet blir bättre.`,
    originalNumber: 16,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-21",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, \"Balansräkning\".",
    question: "Vad är eget kapital, hur räknar man ut det och vad visar det?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Eget kapital är den del av företagets tillgångar som återstår när skulderna har dragits av.

> Eget kapital = tillgångar - skulder

Det kan bestå av ägarnas insatta kapital, balanserade vinster eller förluster och årets resultat. Eget kapital visar bland annat hur stor ekonomisk buffert företaget har och hur mycket av verksamheten som finansierats av ägarna och tidigare resultat i stället för av skulder.

**Exempel:** Om ett företag har tillgångar på 2 000 000 kronor och skulder på 1 300 000 kronor är eget kapital 700 000 kronor.

Ett positivt och tillräckligt eget kapital ökar normalt motståndskraften mot förluster. Det används också i beräkningen av soliditet. Eget kapital är dock inte samma sak som pengar på bankkontot; kapitalet kan vara bundet i exempelvis inventarier eller kundfordringar.`,
    answerSummary: `Eget kapital är den del av företagets tillgångar som återstår när skulderna har dragits av.`,
    originalNumber: 21,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-22",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 7.",
    question: "Vad betyder RFI och vad avses?",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `RFI står för **Request for Information**. Det är en formell informationsförfrågan som används för att samla kunskap om marknaden, leverantörer, möjliga tekniska lösningar, kostnadsnivåer eller genomförbarhet inför ett framtida projekt eller en upphandling.

En RFI är normalt inte en färdig beställning och innebär inte att kunden har bestämt exakt vad som ska köpas. Kunden försöker ofta förstå vilka lösningar som finns och hur ett kommande kravunderlag bör utformas.

**Exempel:** En kommun planerar att byta dokumenthanteringssystem men vill först veta vilka moln- och lokalt installerade alternativ som finns, hur migrering kan genomföras och vilka säkerhetskrav marknaden kan uppfylla. Kommunen skickar därför en RFI till flera leverantörer.

För leverantören är RFI:n en möjlighet att bidra med kunskap och påverka kundens förståelse, men svaret bör vara informativt och inte behandlas som om kunden redan efterfrågar en slutlig offert.`,
    answerSummary: `RFI står för **Request for Information**. Det är en formell informationsförfrågan som används för att samla kunskap om marknaden, leverantörer, möjliga tekniska lösningar, kostnadsnivåer eller genomförbarhet inför ett framtida projekt eller en upphandling.`,
    originalNumber: 22,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-24",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, \"Balansräkning\".",
    question: "Ge exempel på två olika tillgångsslag",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Två huvudtyper av tillgångar är:

1. **Omsättningstillgångar:** tillgångar som normalt ska omsättas, säljas eller förbrukas inom den löpande verksamheten, exempelvis kassa, bankmedel, kundfordringar och varulager.
2. **Anläggningstillgångar:** tillgångar som är avsedda att användas under längre tid, exempelvis datorer, maskiner, inventarier, fastigheter eller immateriella tillgångar som programvara, varumärken och goodwill.

**Exempel:** En obetald kundfaktura är en omsättningstillgång. Ett egenutvecklat system som redovisas som en immateriell tillgång kan vara en anläggningstillgång.

Skillnaden är viktig eftersom tillgångarna har olika tidshorisont och påverkar analyser som kassalikviditet och avskrivningar på olika sätt.`,
    originalNumber: 24,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-25",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 10, avsnittet om strategisk försäljning.",
    question: "Vad är omni- respektive multikanal och vad skiljer dem åt?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `**Multikanal** innebär att företaget använder flera kanaler för kontakt, marknadsföring, försäljning eller service, exempelvis webbplats, butik, telefon, e-post och sociala medier. Kanalerna kan dock fungera relativt separat från varandra.

**Omnikanal** innebär också flera kanaler, men de är samordnade så att kunden får en sammanhängande upplevelse och kan röra sig mellan kanalerna utan att information eller sammanhang försvinner.

**Exempel:** I ett multikanalupplägg kan en kund läsa om en IT-tjänst på webbplatsen och därefter ringa säljaren, men säljaren saknar information om vad kunden redan har gjort. I ett omnikanalupplägg finns kundens aktivitet, bokade demo, tidigare frågor och offert samlat i CRM-systemet, så nästa kontakt kan fortsätta där den förra slutade.

Skillnaden ligger alltså inte främst i antalet kanaler, utan i graden av integration och kundsammanhang.`,
    answerSummary: `**Multikanal** innebär att företaget använder flera kanaler för kontakt, marknadsföring, försäljning eller service, exempelvis webbplats, butik, telefon, e-post och sociala medier. Kanalerna kan dock fungera relativt separat från varandra.`,
    originalNumber: 25,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-26",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Handkurerat facit",
    question: "Beskriv de fem kundstrategierna i kundsegmenteringsmodellen",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `En kundsegmenteringsmodell används för att välja olika strategi för olika kunder i stället för att behandla alla likadant. En kursnära femdelning är:

1. **Värva nya kunder:** identifiera och kontakta prospekt som matchar målgruppen.
2. **Konvertera:** föra en intresserad kontakt till en första konkret affär.
3. **Utveckla eller merförsälja:** öka kundvärdet genom fler tjänster, större uppdrag eller längre samarbete.
4. **Behålla:** vårda lönsamma och viktiga relationer så att kunden fortsätter köpa och inte går till en konkurrent.
5. **Återvinna:** försöka vinna tillbaka tidigare eller inaktiva kunder när det finns en realistisk affärsmöjlighet.

Strategin väljs utifrån exempelvis nuvarande intäkt, lönsamhet, potential, relation, betalningsrisk och strategiskt värde.

**Exempel:** Ett konsultbolag kan värva prospekt genom webinarier, konvertera intresserade deltagare till en betald förstudie, utveckla förstudiekunden genom ett införandeprojekt, behålla kunden genom ett förvaltningsavtal och försöka återvinna en tidigare kund när ett nytt behov uppstår.

Poängen är att använda tid och säljresurser där de ger störst långsiktigt värde.`,
    answerSummary: `En kundsegmenteringsmodell används för att välja olika strategi för olika kunder i stället för att behandla alla likadant. En kursnära femdelning är:`,
    originalNumber: 26,
    examArea: 2,
    isPriority: false,
    hint: "Föreläsningsmaterialet nämner målgruppsstrategi eller kundstrategi, men den exakta femlistan finns inte utskriven i de tillgängliga PDF-bilderna. Benämningarna ovan är därför en kursnära komplettering och bör läras med denna reservation.",
  },
  {
    id: "tenta-27",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Handkurerat facit",
    question: "Vilka tre huvudsakliga steg innehåller kundens köpprocess och varför är det viktigt för säljaren att ta hänsyn till dessa?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `Kundens köpprocess kan sammanfattas i tre huvudsteg:

1. **Behov och problemmedvetenhet:** kunden upptäcker ett problem, behov eller en möjlighet och börjar förstå att en förändring kan behövas.
2. **Informationssökning och utvärdering:** kunden undersöker alternativ, jämför lösningar, leverantörer, risk, pris och förväntad nytta.
3. **Beslut, köp och efterköpsbedömning:** kunden väljer lösning, förhandlar och tecknar avtal. Efter leveransen bedömer kunden om förväntningarna uppfylldes.

I komplex B2B-försäljning är processen sällan helt rak. Kunden kan gå tillbaka till ett tidigare steg, nya beslutsfattare kan tillkomma och behoven kan förändras.

Det är viktigt för säljaren att förstå steget eftersom olika insatser behövs:

- tidigt ska säljaren hjälpa kunden att förstå problemet och dess konsekvenser,
- i utvärderingen ska säljaren visa relevant värde och minska osäkerhet,
- inför beslut ska säljaren göra valet tydligt och hantera avtal, risk och invändningar,
- efter köpet ska leveransen följas upp för att bygga relation och skapa framtida affärer.

Att lämna en detaljerad offert när kunden fortfarande försöker förstå problemet är ofta för tidigt.`,
    originalNumber: 27,
    examArea: 2,
    isPriority: false,
    hint: "Föreläsningarna visar samma logik genom säljtratten och genom RFI, RFP och RFQ, men den exakta trestegslistan finns inte utskriven i de tillgängliga PDF-bilderna. Formuleringen ovan är därför en kursnära sammanfattning.",
  },
  {
    id: "tenta-28",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5, avsnittet om bundet och fritt eget kapital.",
    question: "Vad är skillnaden mellan bundet och fritt eget kapital?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `**Bundet eget kapital** måste stanna i företaget och får normalt inte delas ut till ägarna. I ett aktiebolag består det främst av aktiekapital, reservfond och uppskrivningsfond. Det fungerar som ett skydd för bolagets fordringsägare.

**Fritt eget kapital** kan, efter beslut och under förutsättning att lagens försiktighetsregler följs, användas för exempelvis utdelning. Det består bland annat av balanserad vinst och årets vinst.

**Exempel:** Ett aktiebolag har 25 000 kronor i aktiekapital och 200 000 kronor i balanserade vinster. Aktiekapitalet är bundet. De balanserade vinsterna är fritt eget kapital, men det betyder inte automatiskt att hela beloppet bör delas ut. Bolaget måste fortfarande ha tillräcklig ekonomisk styrka och betalningsförmåga.`,
    answerSummary: `**Bundet eget kapital** måste stanna i företaget och får normalt inte delas ut till ägarna. I ett aktiebolag består det främst av aktiekapital, reservfond och uppskrivningsfond. Det fungerar som ett skydd för bolagets fordringsägare.`,
    originalNumber: 28,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-30",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "BMC, PESTELID, SWOT, Ansoff samt mastermaterialet.",
    question: "Beskriv innehållet i en Ansoff-matris och hur den används",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `Ansoff-matrisen används för att analysera tillväxtalternativ utifrån två dimensioner: **befintlig eller ny produkt/tjänst** och **befintlig eller ny marknad**.

De fyra strategierna är:

1. **Marknadspenetration:** befintlig produkt på befintlig marknad. Företaget försöker sälja mer av det som redan finns till nuvarande kundgrupper.
2. **Marknadsutveckling:** befintlig produkt på ny marknad. Företaget tar sitt nuvarande erbjudande till en ny bransch, målgrupp eller region.
3. **Produktutveckling:** ny produkt på befintlig marknad. Företaget utvecklar ett nytt erbjudande för kunder som det redan känner.
4. **Diversifiering:** ny produkt på ny marknad. Detta är normalt det mest riskfyllda alternativet eftersom både erbjudandet och marknaden är nya.

**IT-exempel:** Ett konsultbolag säljer fler M365-automationsprojekt till nuvarande kundsegment, vilket är marknadspenetration. Om det utvecklar en ny AI-analystjänst för samma kunder är det produktutveckling.

Matrisen används för att tydliggöra vilken typ av tillväxt företaget väljer, vilken risk den innebär och vilket underlag som behövs innan beslut.`,
    answerSummary: `Ansoff-matrisen används för att analysera tillväxtalternativ utifrån två dimensioner: **befintlig eller ny produkt/tjänst** och **befintlig eller ny marknad**.`,
    originalNumber: 30,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-31",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"Varför misslyckas\".",
    question: "Vad är vanliga skäl till att man misslyckas i sitt försäljningsarbete?",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `Tre vanliga skäl som lyfts i kursen är:

1. **Dåliga förberedelser:** säljaren har inte läst på om kunden, deltagarna, branschen, tidigare kontakt eller möjliga behov.
2. **Dålig planering av mötet:** mötet saknar tydligt mål, agenda och anpassning till kunden.
3. **Fel eller irrelevanta frågor:** säljaren använder ett generellt frågebatteri utan att anpassa frågorna och förstår därför inte kundens verkliga problem.

Andra vanliga orsaker är att säljaren pratar för mycket, presenterar lösningen för tidigt, inte lyssnar, kontaktar fel personer, inte följer upp eller saknar tydligt nästa steg.

**Exempel:** En leverantör visar en standardpresentation om sin plattform utan att först förstå kundens manuella processer. Kunden ser därför inte hur lösningen är relevant och mötet leder inte vidare.

Det gemensamma problemet är att försäljningen utgår från leverantören i stället för kunden.`,
    originalNumber: 31,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-33",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 7.",
    question: "Vad betyder RFP och vad avses?",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `RFP står för **Request for Proposal**. Det är en formell förfrågan där en organisation bjuder in leverantörer att lämna förslag på hur ett definierat behov, projekt eller problem kan lösas, ofta tillsammans med pris och genomförandeupplägg.

Till skillnad från en RFI har kunden kommit längre och vill ha ett konkret lösningsförslag. Till skillnad från en RFQ är behovet ofta inte så standardiserat att enbart pris räcker; leverantören behöver beskriva lösning, metod, tidplan, kompetens och andra kvaliteter.

**Exempel:** Ett företag skickar en RFP för ett nytt CRM-system. Leverantörerna ska beskriva föreslagen lösning, implementation, integrationer, utbildning, support, projektorganisation och pris.`,
    answerSummary: `RFP står för **Request for Proposal**. Det är en formell förfrågan där en organisation bjuder in leverantörer att lämna förslag på hur ett definierat behov, projekt eller problem kan lösas, ofta tillsammans med pris och genomförandeupplägg.`,
    originalNumber: 33,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-35",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 7 och ny-affärsplan-2026.",
    question: "Vad beskriver en affärsplan i stort?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `En affärsplan beskriver hur företagets affär ska fungera och utvecklas. Den samlar företagets riktning, kunder, erbjudande, marknad, ekonomi och genomförande i en sammanhängande plan.

En affärsplan kan bland annat innehålla:

- bakgrund, affärsidé och vision,
- mål,
- kunder, målgrupper och behov,
- marknad och omvärld,
- konkurrenter och differentiering,
- produkt eller tjänst,
- försäljning och marknadsbearbetning,
- affärsmodell, prissättning och intäktsströmmar,
- viktiga resurser, organisation och team,
- budget, finansiering och lönsamhet,
- risker, SWOT och handlingsplaner,
- hållbarhet och aktiviteter över tid.

Affärsplanens viktigaste uppgift är att visa en röd tråd: det ska vara tydligt hur kundbehovet hänger ihop med erbjudandet, hur kunderna ska nås, hur leveransen sker och hur företaget tjänar pengar.

**Exempel:** Om planen anger små organisationer som målgrupp bör pris, paketering, säljkanaler och leveransmodell vara anpassade till deras budget och köpbeteende.`,
    answerSummary: `En affärsplan beskriver hur företagets affär ska fungera och utvecklas. Den samlar företagets riktning, kunder, erbjudande, marknad, ekonomi och genomförande i en sammanhängande plan.`,
    originalNumber: 35,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-37",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5 och de två årsredovisningsexemplen.",
    question: "Vad är en förvaltningsberättelse?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Förvaltningsberättelsen är verksamhetens eller styrelsens egen beskrivning av hur företaget har utvecklats under räkenskapsåret. Den ger sammanhang till siffrorna i resultat- och balansräkningen.

Den kan beskriva:

- verksamhetens inriktning,
- viktiga händelser under året,
- utveckling av verksamhet, resultat och ställning,
- väsentliga risker och osäkerheter,
- förväntad framtida utveckling,
- förslag till disposition av vinst eller förlust.

**Exempel:** Om omsättningen har minskat kan förvaltningsberättelsen förklara att en viktig marknad försvagats eller att ett större kundavtal avslutats.

Man bör därför läsa förvaltningsberättelsen tillsammans med de ekonomiska rapporterna och inte bara titta på enskilda nyckeltal.`,
    answerSummary: `Förvaltningsberättelsen är verksamhetens eller styrelsens egen beskrivning av hur företaget har utvecklats under räkenskapsåret. Den ger sammanhang till siffrorna i resultat- och balansräkningen.`,
    originalNumber: 37,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-39",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 9.",
    question: "Vad ingår i begreppet marknadsföring?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `I kursen beskrivs marknadsföring som att kommunicera till potentiella och befintliga kunder vad företaget erbjuder. Marknadsföringen ska dock bygga på affärens övriga delar:

- strategi för produkter och tjänster,
- varumärkesplattform och kundlöfte,
- målgrupps- eller kundstrategi,
- differentiering,
- paketering,
- positionering.

Marknadsföring kan ske one-to-one, exempelvis personliga kundkontakter, eller one-to-many, exempelvis annonser, webinarier och sociala medier.

Begreppet omfattar därför mer än reklam. Det handlar om att välja målgrupp, förstå behov, utforma ett relevant erbjudande, formulera rätt budskap, välja kanaler och koppla aktiviteterna till försäljning och långsiktiga kundrelationer.

**Exempel:** Ett IT-bolag publicerar inte bara allmänna inlägg om AI. Det riktar ett webinar till ekonomichefer om hur automatiserad fakturahantering kan spara tid, följer upp deltagarna och kopplar aktiviteten till säljpipelinen.`,
    answerSummary: `I kursen beskrivs marknadsföring som att kommunicera till potentiella och befintliga kunder vad företaget erbjuder. Marknadsföringen ska dock bygga på affärens övriga delar:`,
    originalNumber: 39,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-40",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5 och årsredovisningsexemplen.",
    question: "Vad är en revisionsberättelse?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Revisionsberättelsen är revisorns skriftliga uttalande efter granskning av årsredovisningen, bokföringen och i förekommande fall styrelsens och den verkställande direktörens förvaltning.

Den beskriver bland annat om revisorn anser att:

- årsredovisningen har upprättats enligt tillämpliga regler,
- den ger en rättvisande bild,
- resultat- och balansräkningen bör fastställas,
- styrelse och vd bör beviljas ansvarsfrihet,
- det finns anmärkningar eller särskilda upplysningar.

En revisionsberättelse utan anmärkning är positiv, men den betyder inte att företaget garanterat är lönsamt eller riskfritt. Den visar framför allt revisorns bedömning av redovisningen och förvaltningen enligt uppdraget.`,
    answerSummary: `Revisionsberättelsen är revisorns skriftliga uttalande efter granskning av årsredovisningen, bokföringen och i förekommande fall styrelsens och den verkställande direktörens förvaltning.`,
    originalNumber: 40,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-41",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 10, \"Lösningsförslag\".",
    question: "Vad ingår bland annat i ett lösningsförslag som vi lämnar till kund?",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `Ett lösningsförslag ska översätta behovsanalysen till en konkret och kundanpassad affär. Det kan innehålla:

- bakgrund och sammanfattning av kundens situation,
- identifierade behov, problem och mål,
- föreslagen lösning och avgränsning,
- berörda målgrupper och användare,
- funktionskrav och eventuella tekniska krav,
- leveranser och vad som inte ingår,
- tidplan, milstolpar och projektorganisation,
- kundens och leverantörens ansvar,
- investering, pris och betalningsmodell,
- nyttor, mätetal och business case,
- risker, beroenden och antaganden,
- förvaltning, support och utbildning,
- avtalsdelar, sekretess, data, ägande och ändringshantering,
- nästa steg och giltighetstid.

**Exempel:** För ett nytt ärendehanteringssystem ska förslaget inte bara beskriva funktioner. Det ska koppla dem till kundens problem, exempelvis dubbelarbete, svår sökning och bristande spårbarhet, och visa hur nyttan ska följas upp.

Ett generellt produktblad är därför inte samma sak som ett bra lösningsförslag.`,
    originalNumber: 41,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-43",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5 och budgetmallarna.",
    question: "Vad är en likviditetsbudget och vad visar den?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `En likviditetsbudget är en plan över företagets faktiska in- och utbetalningar under en framtida period, ofta månad för månad. Den visar hur mycket pengar som förväntas finnas tillgängliga vid olika tidpunkter.

Den innehåller exempelvis:

- ingående likvida medel,
- kundinbetalningar,
- lån eller kapitaltillskott,
- löner, skatter och sociala avgifter,
- leverantörsbetalningar,
- investeringar, räntor och amorteringar,
- utgående likvida medel.

Likviditetsbudgeten skiljer sig från resultatbudgeten eftersom intäkt och inbetalning, eller kostnad och utbetalning, kan inträffa vid olika tidpunkter.

**Exempel:** Ett konsultbolag kan visa vinst i resultatbudgeten men ändå få likviditetsproblem om kunder betalar efter 60 dagar samtidigt som löner och skatter ska betalas varje månad.

Likviditetsbudgeten används för att upptäcka betalningsproblem i förväg och planera exempelvis fakturering, kredit, kapitaltillskott eller senarelagda investeringar.`,
    answerSummary: `En likviditetsbudget är en plan över företagets faktiska in- och utbetalningar under en framtida period, ofta månad för månad. Den visar hur mycket pengar som förväntas finnas tillgängliga vid olika tidpunkter.`,
    originalNumber: 43,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-44",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "AM5 och Affärsmannaskap 6.",
    question: "Beskriv vad som avses med en prognos",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `En prognos är en uppdaterad bedömning av hur verksamheten förväntas utvecklas utifrån aktuell information.

Skillnaden mellan budget och prognos är:

- **Budgeten** är den ursprungliga planen eller målsättningen.
- **Prognosen** är den bästa aktuella bedömningen av det sannolika utfallet.

Prognosen uppdateras när verkligheten förändras, exempelvis när en affär försenas, beläggningen sjunker, kostnader ökar eller nya uppdrag tillkommer.

**Exempel:** Budgeten räknar med 80 procents debiteringsgrad. Efter första kvartalet har två projekt flyttats fram. Prognosen justeras därför till 68 procent och visar hur intäkter, kassaflöde och bemanning påverkas.

En prognos ska hjälpa ledningen att agera tidigt. Det är därför fel att hålla fast vid budgeten som om den fortfarande vore den mest sannolika utvecklingen.`,
    originalNumber: 44,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-45",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 6 och Business Model Canvas-materialet.",
    question: "Vad är en affärsmodell? Exemplifiera",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `En affärsmodell beskriver hur ett företag **skapar värde, levererar värde och tjänar pengar på värdet**. Den omfattar mer än produkten och ska visa hur hela affären fungerar.

Den kan beskriva:

- kunder och kundbehov,
- värdeerbjudande,
- kanaler och kundrelationer,
- aktiviteter, resurser och partners,
- kostnadsstruktur,
- intäktsströmmar och prissättning.

**Exempel:** Ett IT-bolag säljer en fastprisförstudie, ett införandeprojekt på löpande räkning och ett månadsabonnemang för support och förbättringar. Värdet skapas genom processförståelse och automation, levereras av konsulter i kundens Microsoft 365-miljö och betalas genom tre olika intäktsströmmar.

Andra affärsmodeller är freemium, prenumeration, licens, plattform eller marknadsplats, franchise, paketering och rakhyvel-och-bladmodellen.`,
    answerSummary: `En affärsmodell beskriver hur ett företag **skapar värde, levererar värde och tjänar pengar på värdet**. Den omfattar mer än produkten och ska visa hur hela affären fungerar.`,
    originalNumber: 45,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-46",
    mode: "tenta",
    type: "open",
    category: "Försäljning & förhandlingsteknik",
    source: "Affärsmannaskap 11, \"Vinnande argumentation\".",
    question: "Vinnande argumentation - ge minst tre konkreta förslag",
    tags: ["Försäljning & förhandlingsteknik"],
    answer: `Vinnande argumentation innebär att argumentera för en lösning på kundens problem eller behov, inte bara beskriva en produkt.

Konkreta principer är:

1. **Utgå från behovsanalysen och kundens perspektiv.** Beskriv de fördelar som kunden själv har sagt är betydelsefulla.
2. **Var konkret.** Använd siffror, exempel och tydliga effekter i stället för vaga påståenden som "bättre" och "smartare".
3. **Var trovärdig och undvik överdrifter.** Erkänn relevanta begränsningar eller nackdelar när det behövs.
4. **Koppla egenskap till nytta.** Använd exempelvis FAB för att visa vad funktionen betyder för kunden.
5. **Använd ett fåtal starka argument.** Många svaga argument gör budskapet otydligt.
6. **Tala inte illa om konkurrenterna.** Förklara den egna skillnaden sakligt.

**Exempel:** Säg inte bara "vårt system har automatiserade arbetsflöden". Säg: "Ni beskrev att varje ärende registreras två gånger. Vårt automatiserade flöde tar bort det steget, vilket enligt er volym motsvarar cirka 15 arbetstimmar per vecka och minskar risken för registreringsfel."`,
    answerSummary: `Vinnande argumentation innebär att argumentera för en lösning på kundens problem eller behov, inte bara beskriva en produkt.`,
    originalNumber: 46,
    examArea: 3,
    isPriority: false,
  },
  {
    id: "tenta-47",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2 och 3.",
    question: "Vad innebär en SWOT-analys och hur använder man den?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `SWOT står för:

- **Strengths - styrkor:** interna faktorer som hjälper verksamheten.
- **Weaknesses - svagheter:** interna faktorer som skadar eller begränsar verksamheten.
- **Opportunities - möjligheter:** externa faktorer som kan gynna verksamheten.
- **Threats - hot:** externa faktorer som kan skada verksamheten.

Analysen används för att skapa en samlad nulägesbild och därefter fatta beslut. Det viktiga är att skilja interna faktorer från externa.

**Exempel för ett IT-bolag:**

- Styrka: hög kompetens inom Microsoft 365.
- Svaghet: få kundreferenser.
- Möjlighet: ökande efterfrågan på AI-stödd administration.
- Hot: stora konsultbolag och nya standardverktyg som kan ersätta delar av tjänsten.

Analysen bör leda till handling. Bolaget kan exempelvis använda sin kompetens för att genomföra billiga pilotprojekt, skapa referenser och minska svagheten. SWOT är alltså inte bara en lista, utan ett beslutsunderlag.`,
    originalNumber: 47,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-48",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 11, \"Business Case\".",
    question: "Varför gör man ett Business Case?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Ett business case, eller affärsfall, är ett beslutsunderlag som motiverar varför en investering, ett projekt eller en förändring bör genomföras.

Syftet är att visa att:

- det finns ett verkligt problem eller en möjlighet,
- den föreslagna lösningen är relevant,
- nyttan överstiger kostnader och risker,
- initiativet stödjer organisationens övergripande mål,
- det finns resurser och en realistisk tidsplan.

Ett business case innehåller ofta:

- bakgrund och problem,
- föreslagen lösning,
- affärsnytta och ROI,
- kostnader och resursbehov,
- tidsplan och milstolpar,
- riskanalys,
- nollalternativet, alltså vad som händer om man inte gör något.

**Exempel:** Ett företag överväger ett nytt ärendehanteringssystem. Business caset jämför investeringen med tidsbesparing, minskade fel, lägre risk och kostnaden för att fortsätta med dagens manuella process.`,
    answerSummary: `Ett business case, eller affärsfall, är ett beslutsunderlag som motiverar varför en investering, ett projekt eller en förändring bör genomföras.`,
    originalNumber: 48,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-54",
    mode: "tenta",
    type: "open",
    category: "Kundbearbetning & kundrelation",
    source: "Affärsmannaskap 2, \"Konkurrenter\".",
    question: "Vad kan ingå i en konkurrentanalys och hur använder man den?",
    tags: ["Kundbearbetning & kundrelation"],
    answer: `En konkurrentanalys kan omfatta:

- vilka direkta konkurrenter som finns,
- indirekta konkurrenter och substitut, exempelvis intern IT eller standardverktyg,
- vilka produkter och tjänster de erbjuder,
- paketering och affärsmodell,
- priser och prismodeller,
- målgrupper och kundtyper,
- kompetens och personalprofil,
- sälj- och distributionskanaler,
- partners och allianser,
- styrkor och svagheter,
- positionering, varumärke och kundlöfte,
- nyckeltal, bokslut, nyheter, rekryteringar och marknadsmaterial.

Analysen används för att förstå vad kunden faktiskt jämför företaget med och för att fatta beslut om positionering, differentiering, pris och paketering.

**Exempel:** Ett mindre IT-bolag jämför sig inte bara med stora konsultfirmor. Kundens alternativ kan också vara en frilansare, en intern utvecklare eller ett färdigt no-code-verktyg. Bolaget väljer därför att differentiera sig genom snabb pilot, verksamhetsförståelse och utbildning.

Analysen ska inte bara konstatera att konkurrenterna finns. Den ska leda till ett svar på frågan: varför ska rätt kund välja oss?`,
    originalNumber: 54,
    examArea: 2,
    isPriority: false,
  },
  {
    id: "tenta-56",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 6.",
    question: "Vad är ett NDA? Vad betyder det och vad innebär det?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `NDA står för **Non-Disclosure Agreement**, alltså sekretessavtal. I föreläsningsmaterialet står "None Disclosure Agreement", men den etablerade engelska termen är Non-Disclosure Agreement.

Ett NDA reglerar hur konfidentiell information får användas, delas, lagras och skyddas. Det kan bland annat ange:

- vilken information som är konfidentiell,
- vilka personer som får ta del av den,
- vilket syfte informationen får användas för,
- hur länge sekretessen gäller,
- undantag, exempelvis redan offentlig information,
- vad som händer vid avtalsbrott,
- hur material ska återlämnas eller förstöras.

**Exempel:** En IT-konsult får tillgång till kundens systemarkitektur, säkerhetsbrister och affärsprocesser. NDA:t innebär att informationen bara får användas för det avtalade projektet och inte spridas till andra kunder eller utomstående.

Ett NDA kan vara ett separat avtal eller en sekretessklausul i ett konsultavtal. Det ersätter inte behovet av andra regler om exempelvis personuppgifter, informationssäkerhet eller immateriella rättigheter.`,
    answerSummary: `NDA står för **Non-Disclosure Agreement**, alltså sekretessavtal. I föreläsningsmaterialet står "None Disclosure Agreement", men den etablerade engelska termen är Non-Disclosure Agreement.`,
    originalNumber: 56,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-58",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 7.",
    question: "Vilka är kriterierna i offentlig upphandling enligt LOU?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Enligt kursmaterialet kan den upphandlande organisationen använda:

- **bästa förhållandet mellan pris och kvalitet,**
- **kostnad**, exempelvis kostnadseffektivitet eller livscykelkostnad,
- **pris.**

Utöver själva tilldelningsgrunden vilar offentlig upphandling på grundläggande principer:

- likabehandling,
- icke-diskriminering,
- öppenhet och transparens,
- proportionalitet,
- ömsesidigt erkännande.

Kriterierna och utvärderingsmodellen måste vara tydliga i förväg så att leverantörerna kan förstå hur anbuden kommer att bedömas och lämna jämförbara svar.

**Exempel:** Om kvalitet ska påverka resultatet måste det framgå vilka kvalitetsområden som bedöms, hur poäng ges och hur poängen vägs mot priset. Kunden får inte efteråt välja en annan metod för att gynna ett visst anbud.`,
    originalNumber: 58,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-59",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 9.",
    question: "Vad är speciellt förbjudet i marknadsföringslagen?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Marknadsföringslagen innehåller särskilda förbud mot:

- **vilseledande marknadsföring**, exempelvis falska eller otydliga påståenden om pris, innehåll, resultat eller villkor,
- **aggressiv marknadsföring**, exempelvis trakasserier, tvång, hot eller otillbörlig påverkan.

Marknadsföring ska dessutom vara tydligt identifierbar som marknadsföring, och det ska framgå vem som ansvarar för den.

**Exempel på vilseledande marknadsföring:** Ett företag lovar "säker vinst" i ett onlinespel eller kallar något gratis trots att en obligatorisk avgift tillkommer.

**Exempel på bristande tydlighet:** Ett företag betalar för en studie och använder resultatet i reklam utan att det framgår att materialet är sponsrat eller kommersiellt.

Grundtanken är att mottagaren ska kunna fatta ett informerat beslut utan att luras eller pressas.`,
    originalNumber: 59,
    examArea: 1,
    isPriority: false,
  },
  {
    id: "tenta-60",
    mode: "tenta",
    type: "open",
    category: "Företagsekonomi & avtalsrätt",
    source: "Affärsmannaskap 9, \"Ramverk för scenarioplanering med kopplade handlingsplaner\".",
    question: "Vad är ramverket för scenarioplanering med kopplade handlingsplaner?",
    tags: ["Företagsekonomi & avtalsrätt"],
    answer: `Ramverket har tre huvuddelar:

### 1. Scenarioanalys

Beskriv flera tänkbara framtida lägen utifrån nuläget, exempelvis:

- optimistiskt scenario,
- realistiskt scenario,
- pessimistiskt scenario.

Scenarierna bör konkretiseras med antaganden och mätetal, inte bara allmänna berättelser.

### 2. Effektanalys

Analysera hur varje scenario påverkar relevanta perspektiv, exempelvis:

- kunder och försäljning,
- organisation och bemanning,
- verksamhetsdrift och leverans,
- ekonomi, EBIT, kassaflöde och finansiering.

### 3. Handlingsplaner

Ta fram prioriterade aktiviteter som förstärker positiva effekter eller minskar negativa effekter. Varje aktivitet bör ha:

- ansvarig person,
- datum eller tidsram,
- förväntad effekt,
- mätetal,
- uppföljning.

Arbetet ska förankras med nyckelpersoner och följas upp kontinuerligt. När förutsättningarna ändras ska scenarier, beslut och handlingar kunna justeras.

**IT-exempel:** Ett konsultbolag gör tre scenarier för leadvolym, debiteringsgrad, intäkt och kassa. I det pessimistiska scenariot startas riktad bearbetning av befintliga kunder, kostnader senareläggs och mindre paketerade pilotprojekt lanseras.`,
    originalNumber: 60,
    examArea: 1,
    isPriority: false,
  }
];
