/**
 * Generates src/logic/tentaprio-questions.ts from 25q.md
 * Run: npx tsx scripts/build-25q-questions.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_MD = resolve(__dirname, '../../25q.md');
const OUTPUT = resolve(__dirname, '../src/logic/tentaprio-questions.ts');

const AREA_LABELS: Record<1 | 2 | 3, string> = {
  1: 'Företagsekonomi & avtalsrätt',
  2: 'Kundbearbetning & kundrelation',
  3: 'Försäljning & förhandlingsteknik',
};

interface ParsedQuestion {
  number: number;
  question: string;
  summary: string;
  depth: string;
  examArea: 1 | 2 | 3;
}

function cleanMd(text: string): string {
  return text
    .replace(/\\([.!*=+\-()])/g, '$1')
    .replace(/\r\n/g, '\n')
    .trim();
}

function escapeTemplate(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function examAreaForNumber(number: number): 1 | 2 | 3 {
  if (number <= 8) return 1;
  if (number <= 16) return 2;
  return 3;
}

function parseQuestions(md: string): ParsedQuestion[] {
  const cleaned = cleanMd(md);
  const questions: ParsedQuestion[] = [];

  const sections = cleaned.split(/\n(?=### \*\*\d+)/);

  for (const section of sections) {
    const headerMatch = section.match(/^### \*\*(\d+)\.\s*(.+?)\*\*/);
    if (!headerMatch) continue;

    const number = Number(headerMatch[1]);
    const question = headerMatch[2].trim();
    const body = section.slice(headerMatch[0].length).trim();

    const summaryMatch = body.match(
      /\*\*Kort sammanfattning:\*\*\s*([\s\S]*?)(?=\*\*Fördjupning|$)/
    );
    const depthMatch = body.match(/\*\*Fördjupning & Exempel:\*\*\s*([\s\S]*?)$/);

    const summary = summaryMatch?.[1]?.trim() ?? '';
    const depth = depthMatch?.[1]?.trim() ?? '';

    if (!summary) {
      throw new Error(`Missing summary for question ${number}`);
    }

    questions.push({ number, question, summary, depth, examArea: examAreaForNumber(number) });
  }

  return questions.sort((a, b) => a.number - b.number);
}

function buildOutput(questions: ParsedQuestion[]): string {
  const blocks = questions.map(q => {
    const fields = [
      `    id: "tentaprio-${q.number}",`,
      `    mode: "tentaprio",`,
      `    type: "open",`,
      `    category: "${AREA_LABELS[q.examArea]}",`,
      `    source: "25q.md",`,
      `    question: ${JSON.stringify(q.question)},`,
      `    tags: ${JSON.stringify([AREA_LABELS[q.examArea], 'Tentaprio 25', `Fråga ${q.number}`])},`,
      `    answer: \`${escapeTemplate(q.summary)}\`,`,
      ...(q.depth ? [`    why: \`${escapeTemplate(q.depth)}\`,`] : []),
      `    originalNumber: ${q.number},`,
      `    examArea: ${q.examArea},`,
    ];

    return `  {\n${fields.join('\n')}\n  }`;
  });

  return `// AUTO-GENERATED by scripts/build-25q-questions.ts — do not edit by hand.
// Source: 25q.md (Kort sammanfattning + Fördjupning & Exempel)
// Generated: ${new Date().toISOString()}

import type { TentaprioQuestion } from './questions';

export const TENTAPRIO_QUESTIONS: TentaprioQuestion[] = [
${blocks.join(',\n')}
];
`;
}

const md = readFileSync(SOURCE_MD, 'utf-8');
const questions = parseQuestions(md);

if (questions.length !== 25) {
  throw new Error(`Expected 25 questions, got ${questions.length}`);
}

writeFileSync(OUTPUT, buildOutput(questions), 'utf-8');
console.log(`Wrote ${questions.length} tentaprio questions → ${OUTPUT}`);