window.FOKUS_QUESTIONS = [
  {
    id: "soliditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara soliditet med egna ord",
    tags: ["Ekonomi", "AM5"],
    answer: "Soliditet visar hur stor del av företagets tillgångar som är finansierade med eget kapital.",
    why: "Måttet säger något om långsiktig finansiell motståndskraft. Högre soliditet ger större buffert vid förlust eller sämre tider.",
    example: "Essiq AB rapporterade 28,20 procent soliditet 2021, medan Hälsö Fisk AB rapporterade 11 procent 2017.",
    related: ["Eget kapital", "Balansräkning", "Risk", "Likviditet"]
  },
  {
    id: "likviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder likviditet?",
    tags: ["Ekonomi", "AM5"],
    answer: "Likviditet betyder kortsiktig betalningsförmåga: om företaget kan betala sina löpande skulder i tid.",
    why: "Ett företag kan visa vinst men ändå få problem om pengarna sitter i kundfordringar eller lager i stället för kassa.",
    example: "Essiq AB hade bättre balanslikviditet än Hälsö Fisk AB, men mycket av Essiqs kortsiktiga betalningsförmåga låg i fordringar.",
    related: ["Kassalikviditet", "Balanslikviditet", "Kassaflöde", "Kortfristiga skulder"]
  },
  {
    id: "kassalikviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Förklara kassalikviditet",
    tags: ["Ekonomi", "AM5"],
    answer: "Kassalikviditet är omsättningstillgångar exklusive lager och pågående arbeten dividerat med kortfristiga skulder.",
    why: "Måttet visar om korta skulder kan betalas utan att bolaget först måste sälja sitt lager.",
    example: "Hälsö Fisk AB låg ungefär runt 80 procent i kassalikviditet utifrån 2017 års balansräkning.",
    related: ["Likviditet", "Balanslikviditet", "Lager", "Kortfristiga skulder"]
  },
  {
    id: "balanslikviditet",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter balanslikviditet?",
    tags: ["Ekonomi", "AM5"],
    answer: "Balanslikviditet är omsättningstillgångar dividerat med kortfristiga skulder.",
    why: "Det ger en bred bild av kortsiktig betalningsförmåga, men säger inte om tillgångarna redan finns som pengar på banken.",
    example: "Essiq AB hade cirka 144 procent i balanslikviditet 2021.",
    related: ["Omsättningstillgångar", "Likviditet", "Kassalikviditet", "Kundfordringar"]
  },
  {
    id: "resultatrakning",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en resultaträkning?",
    tags: ["Ekonomi", "AM5"],
    answer: "Resultaträkningen visar intäkter minus kostnader under en period och leder fram till årets resultat.",
    why: "Den visar om affären faktiskt går med vinst eller förlust, inte bara hur mycket bolaget säljer för.",
    example: "Essiq AB hade 2021 ett resultat efter finansiella poster på 11 305 793 kr.",
    related: ["Nettoomsättning", "Kostnader", "Rörelseresultat", "Årets resultat"]
  },
  {
    id: "balansrakning",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en balansräkning?",
    tags: ["Ekonomi", "AM5"],
    answer: "Balansräkningen visar tillgångar, skulder och eget kapital vid en viss tidpunkt.",
    why: "Den visar hur bolaget är finansierat och hur stor del av tillgångarna som är bundna i skulder eller eget kapital.",
    example: "Hälsö Fisk AB hade 1 184 841 kr i tillgångar och 130 528 kr i eget kapital 2017.",
    related: ["Tillgångar", "Skulder", "Eget kapital", "Soliditet"]
  },
  {
    id: "eget-kapital",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är eget kapital?",
    tags: ["Ekonomi", "AM5"],
    answer: "Eget kapital är tillgångar minus skulder, alltså ägarnas kapital i bolaget.",
    why: "Det fungerar som buffert och är grunden för soliditeten.",
    example: "Essiq AB hade 10 468 395 kr i eget kapital 2021.",
    related: ["Soliditet", "Balansräkning", "Bundet eget kapital", "Fritt eget kapital"]
  },
  {
    id: "kassaflode",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder kassaflöde?",
    tags: ["Ekonomi", "AM5"],
    answer: "Kassaflöde är pengar som kommer in och går ut ur företaget över tid.",
    why: "Kassaflödet avgör om bolaget kan betala löpande även när resultatet ser bra ut.",
    example: "Essiq AB:s likvida medel minskade från 26 509 757 kr till 2 822 630 kr under 2021.",
    related: ["Likviditet", "Kassa och bank", "Kundfordringar", "Resultat"]
  },
  {
    id: "tackningsbidrag",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är täckningsbidrag?",
    tags: ["Ekonomi", "AM5"],
    answer: "Täckningsbidrag är försäljningsintäkt minus direkta kostnader för en tjänst eller ett projekt.",
    why: "Det visar hur mycket ett projekt bidrar till fasta kostnader och vinst.",
    example: "Ett projekt som säljs för 180 000 kr och kostar 105 000 kr direkt ger 75 000 kr i täckningsbidrag.",
    related: ["Intäkter", "Direkta kostnader", "Lönsamhet", "Projekt"]
  },
  {
    id: "budget-prognos",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är skillnaden mellan budget och prognos?",
    tags: ["Ekonomi", "AM5"],
    answer: "Budget är planen i förväg. Prognos är en uppdaterad bedömning av hur utfallet verkar bli.",
    why: "Skillnaden hjälper ett företag att styra både mål och verklighet när intäkter eller kostnader ändras.",
    example: "Ett konsultbolag kan budgetera 80 procent beläggning men justera prognosen när uppdrag försenas.",
    related: ["Uppföljning", "Q/T/H", "Likviditetsbudget", "Lönsamhet"]
  },
  {
    id: "arsredovisning",
    mode: "begrepp",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vad är en årsredovisning?",
    tags: ["Årsredovisning", "AM5"],
    answer: "En årsredovisning är ett paket med förvaltningsberättelse, resultaträkning, balansräkning, noter och ofta revisionsberättelse.",
    why: "Den ger flera vinklar på hur bolaget mår och gör det möjligt att läsa ekonomi och verksamhet tillsammans.",
    example: "AM5 använder Hälsö Fisk AB och Essiq AB som exempel på hur olika bolag kan läsas.",
    related: ["Förvaltningsberättelse", "Resultaträkning", "Balansräkning", "Revisionsberättelse"]
  },
  {
    id: "forvaltningsberattelse",
    mode: "begrepp",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Varför ska man läsa förvaltningsberättelsen?",
    tags: ["Årsredovisning", "AM5"],
    answer: "Förvaltningsberättelsen beskriver vad som har hänt i verksamheten under året.",
    why: "Den hjälper dig förstå varför siffrorna ser ut som de gör, inte bara vad siffrorna är.",
    example: "Hälsö Fisk AB beskriver färre kundbesök och pressad försäljning på grund av infrastrukturförändringar i Kungälv.",
    related: ["Årsredovisning", "Resultat", "Omvärld", "Risk"]
  },
  {
    id: "bmc",
    mode: "begrepp",
    type: "open",
    category: "Modeller",
    source: "AM1/BMC",
    question: "Vad används Business Model Canvas till?",
    tags: ["Modeller", "BMC"],
    answer: "Business Model Canvas används för att beskriva hur ett företag skapar, levererar och tar betalt för värde.",
    why: "Modellen binder ihop kund, erbjudande, resurser, aktiviteter, intäkter och kostnader i en helhetsbild.",
    example: "Ett IT-konsultbolag kan beskriva kundsegment, värdeerbjudande, kanaler, nyckelresurser och intäktsmodell i BMC.",
    related: ["Kundsegment", "Värdeerbjudande", "Intäktsströmmar", "Kostnadsstruktur"]
  },
  {
    id: "kundsegment",
    mode: "begrepp",
    type: "open",
    category: "Modeller",
    source: "BMC",
    question: "Vad betyder kundsegment i BMC?",
    tags: ["BMC", "Kund"],
    answer: "Kundsegment är de grupper av kunder företaget väljer att rikta sig till.",
    why: "Utan tydligt kundsegment blir erbjudandet lätt allmänt och svårt att sälja.",
    example: "Små och medelstora organisationer med mycket administration kan vara ett kundsegment för ett M365-konsultbolag.",
    related: ["Värdeerbjudande", "Kanaler", "Relationer", "Marknad"]
  },
  {
    id: "vardeerbjudande",
    mode: "begrepp",
    type: "open",
    category: "Modeller",
    source: "AM2/BMC",
    question: "Vad är ett värdeerbjudande?",
    tags: ["Erbjudande", "BMC"],
    answer: "Värdeerbjudandet är den nytta kunden får och varför kunden ska välja just den lösningen.",
    why: "Det flyttar fokus från vad företaget säljer till vilket problem kunden får löst.",
    example: "Mindre administration, färre manuella steg och snabbare handläggning kan vara värde i ett automationspaket.",
    related: ["FAB", "Kundnytta", "Differentiering", "Kundsegment"]
  },
  {
    id: "fab",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Förklara FAB-modellen",
    tags: ["Erbjudande", "AM2"],
    answer: "FAB står för Features, Advantages, Benefits: egenskap, fördel och kundnytta.",
    why: "Modellen tvingar dig att gå från vad lösningen är till varför den spelar roll för kunden.",
    example: "Egenskap: Power Automate-flöde. Fördel: färre manuella steg. Nytta: snabbare handläggning.",
    related: ["Värdeerbjudande", "Kundnytta", "Erbjudande", "Differentiering"]
  },
  {
    id: "5p",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Vilka delar ingår i 5P?",
    tags: ["Erbjudande", "AM2"],
    answer: "5P består av produkt, pris, plats, påverkan och personal.",
    why: "Modellen ger en enkel helhetsbild av erbjudandet och hur det faktiskt når kunden.",
    example: "Tjänst, prismodell, digital leverans, LinkedIn/referenser och konsulternas kompetens kan beskrivas med 5P.",
    related: ["Pris", "Paketering", "Kanal", "Personal"]
  },
  {
    id: "swot",
    mode: "begrepp",
    type: "open",
    category: "Strategi",
    source: "AM2/AM3",
    question: "Vad är SWOT?",
    tags: ["Strategi", "SWOT"],
    answer: "SWOT är en analys av styrkor, svagheter, möjligheter och hot.",
    why: "Den skiljer intern situation från extern omvärld och hjälper gruppen att formulera beslut.",
    example: "Styrka: M365-kompetens. Hot: större konsulter och AI-verktyg som substitut.",
    related: ["Intern analys", "Extern analys", "PESTELID", "Beslut"]
  },
  {
    id: "pestelid",
    mode: "begrepp",
    type: "open",
    category: "Omvärld",
    source: "AM3",
    question: "Vad används PESTELID till?",
    tags: ["Omvärld", "PESTELID"],
    answer: "PESTELID används för att analysera omvärldsfaktorer: politiskt, ekonomiskt, socialt, teknologiskt, legalt, internationellt, miljö och demografi.",
    why: "Modellen visar faktorer utanför bolaget som kan påverka efterfrågan, risk och affärsmöjlighet.",
    example: "AI-regler, budgetläge, hybridarbete och kompetensbrist kan påverka ett IT-konsultbolag.",
    related: ["Omvärld", "SWOT", "Marknad", "Risk"]
  },
  {
    id: "ansoff",
    mode: "begrepp",
    type: "open",
    category: "Strategi",
    source: "AM3",
    question: "Vad visar Ansoffs matris?",
    tags: ["Strategi", "Ansoff"],
    answer: "Ansoff visar tillväxtval utifrån nuvarande eller ny produkt och nuvarande eller ny marknad.",
    why: "Matrisen hjälper dig förstå risknivån i olika tillväxtstrategier.",
    example: "Att sälja samma automationspaket till fler befintliga kunder är lägre risk än att skapa en helt ny mjukvarutjänst för ny marknad.",
    related: ["Marknadspenetration", "Produktutveckling", "Marknadsutveckling", "Diversifiering"]
  },
  {
    id: "produkt-marknad",
    mode: "begrepp",
    type: "open",
    category: "Strategi",
    source: "Produkt-marknadsmatris",
    question: "Vad gör produkt-marknadsmatrisen i grupparbetet?",
    tags: ["Grupparbete", "Strategi"],
    answer: "Den hjälper gruppen jämföra produkt- eller tjänsteidéer mot möjliga marknader och kundgrupper.",
    why: "Matrisen gör prioriteringen mer konkret än en vanlig magkänsla.",
    example: "Gruppen kan väga tillväxt, lönsamhet, konkurrens och egen kompetens innan den väljer erbjudande.",
    related: ["Marknad", "Kund", "Konkurrens", "Kompetens"]
  },
  {
    id: "konkurrentanalys",
    mode: "begrepp",
    type: "open",
    category: "Strategi",
    source: "BMC/PESTELID/SWOT",
    question: "Varför gör man konkurrentanalys?",
    tags: ["Strategi", "Konkurrens"],
    answer: "Konkurrentanalys används för att förstå vilka alternativ kunden har och hur det egna erbjudandet kan särskiljas.",
    why: "Utan konkurrentanalys riskerar företaget att beskriva sitt erbjudande som unikt fast kunden ser många alternativ.",
    example: "Ett litet IT-konsultbolag kan konkurrera med snabbhet och nisch, medan större bolag konkurrerar med kapacitet och varumärke.",
    related: ["Differentiering", "Positionering", "Pris", "Värdeerbjudande"]
  },
  {
    id: "foretagsformer",
    mode: "begrepp",
    type: "open",
    category: "Företagsform",
    source: "Företagsformer 2025",
    question: "Varför är aktiebolag ofta rimligt i gruppcaset?",
    tags: ["Företagsform", "Grupparbete"],
    answer: "Aktiebolag är ofta rimligt eftersom ägarna normalt inte ansvarar personligen för bolagets skulder.",
    why: "När bolaget säljer konsulttjänster och kan ta avtal, risk och anställningar blir begränsat ansvar viktigt.",
    example: "Ett IT-konsultbolag med flera delägare och tillväxtambition passar ofta bättre som AB än enskild firma.",
    related: ["Ansvar", "Ägande", "Kapital", "Risk"]
  },
  {
    id: "enskild-firma",
    mode: "begrepp",
    type: "open",
    category: "Företagsform",
    source: "Företagsformer 2025",
    question: "Vad är den viktiga risken med enskild firma?",
    tags: ["Företagsform"],
    answer: "I en enskild firma är företagaren och företaget inte juridiskt separerade på samma sätt som i ett aktiebolag.",
    why: "Det betyder större personligt ansvar för skulder och åtaganden.",
    example: "En ensam konsult kan starta enkelt, men personlig risk blir större om större avtal eller skulder uppstår.",
    related: ["Personligt ansvar", "Aktiebolag", "Risk", "Administration"]
  },
  {
    id: "balanced-scorecard",
    mode: "begrepp",
    type: "open",
    category: "Styrning",
    source: "AM4",
    question: "Vad är poängen med Balanced Scorecard?",
    tags: ["Styrning", "AM4"],
    answer: "Balanced Scorecard hjälper företaget styra med fler perspektiv än bara ekonomi.",
    why: "Det gör att mål kan kopplas till kunder, processer, lärande och ekonomi samtidigt.",
    example: "Ett konsultbolag kan följa lönsamhet, kundnöjdhet, leveranskvalitet och kompetensutveckling.",
    related: ["Mål", "KPI", "Kund", "Process"]
  },
  {
    id: "foretagsplattform",
    mode: "begrepp",
    type: "open",
    category: "Styrning",
    source: "AM4",
    question: "Vad innehåller en företagsplattform?",
    tags: ["Styrning", "AM4"],
    answer: "En företagsplattform sammanfattar riktning, värderingar, mål och hur företaget vill agera.",
    why: "Den gör affärsidén mer konsekvent och hjälper gruppen motivera sina val.",
    example: "Ett IT-konsultbolag kan formulera mission, vision, värderingar och mål kring effektivare digital administration.",
    related: ["Affärsidé", "Vision", "Mål", "Värderingar"]
  },
  {
    id: "professionellt-konsultskap",
    mode: "begrepp",
    type: "open",
    category: "Affärsmannaskap",
    source: "AM1",
    question: "Vad betyder professionellt konsultskap i kursen?",
    tags: ["Affärsmannaskap", "AM1"],
    answer: "Det betyder att agera pålitligt, förstå kundens situation och skapa värde i stället för att bara sälja timmar.",
    why: "Affärsmannaskap handlar om relation, nytta, ansvar och ekonomi samtidigt.",
    example: "En konsult som kopplar teknisk lösning till kundens mål visar mer affärsmannaskap än en konsult som bara beskriver tekniken.",
    related: ["Kundnytta", "Värdeerbjudande", "Professionalism", "Relation"]
  },
  {
    id: "positionering",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Vad betyder positionering?",
    tags: ["Erbjudande", "AM2"],
    answer: "Positionering handlar om vilken plats erbjudandet ska ha i kundens huvud jämfört med alternativ.",
    why: "Det hjälper företaget förklara varför kunden ska välja just detta erbjudande.",
    example: "Ett litet konsultbolag kan positionera sig som snabb nischspecialist snarare än fullserviceleverantör.",
    related: ["Differentiering", "Konkurrentanalys", "Värdeerbjudande", "Pris"]
  },
  {
    id: "pris",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Varför är pris mer än bara en siffra?",
    tags: ["Erbjudande", "AM2"],
    answer: "Pris signalerar värde, position och risk, och påverkar både kundens beslut och företagets lönsamhet.",
    why: "För lågt pris kan skada marginalen och få erbjudandet att verka mindre värdefullt.",
    example: "Ett fastpris på en förstudie kan vara enklare för kunden än timdebitering, men kräver tydlig avgränsning.",
    related: ["Lönsamhet", "Paketering", "Täckningsbidrag", "Positionering"]
  },
  {
    id: "fast-good-cheap",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Vad betyder fast-good-cheap-avvägningen?",
    tags: ["Erbjudande", "AM2"],
    answer: "Den visar att snabb, bra och billig leverans sällan kan maximeras samtidigt.",
    why: "Den hjälper företaget förklara tradeoffs i pris, kvalitet och leveranstid.",
    example: "Om kunden vill ha snabb leverans och hög kvalitet kan priset behöva bli högre.",
    related: ["Pris", "Kvalitet", "Paketering", "Kundförväntan"]
  },
  {
    id: "paketering",
    mode: "begrepp",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Varför paketerar man en tjänst?",
    tags: ["Erbjudande", "AM2"],
    answer: "Paketering gör tjänsten tydligare, lättare att köpa och lättare att jämföra.",
    why: "Kunden förstår bättre vad som ingår, vad det kostar och vilket resultat som kan förväntas.",
    example: "En förstudie på två veckor med fast pris kan vara enklare att sälja än ett öppet konsultupplägg.",
    related: ["Pris", "Värdeerbjudande", "5P", "Kundnytta"]
  },
  {
    id: "debiteringsgrad",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder debiteringsgrad?",
    tags: ["Ekonomi", "Konsult"],
    answer: "Debiteringsgrad visar hur stor del av arbetstiden som kan faktureras till kund.",
    why: "I konsultbolag påverkar debiteringsgrad direkt intäkter och lönsamhet.",
    example: "Om en konsult arbetar 160 timmar men bara 120 timmar faktureras blir debiteringsgraden 75 procent.",
    related: ["Snittdebitering", "Lönsamhet", "Intäkter", "Konsultbolag"]
  },
  {
    id: "snittdebitering",
    mode: "begrepp",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad betyder snittdebitering?",
    tags: ["Ekonomi", "Konsult"],
    answer: "Snittdebitering är genomsnittligt fakturerat pris per timme eller konsultinsats.",
    why: "Måttet visar om bolaget säljer sin kompetens till en nivå som täcker kostnader och ger marginal.",
    example: "Hög beläggning med för låg timtaxa kan fortfarande ge svag lönsamhet.",
    related: ["Debiteringsgrad", "Pris", "Täckningsbidrag", "Lönsamhet"]
  },
  {
    id: "likviditet-soliditet-samband",
    mode: "samband",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur hänger likviditet och soliditet ihop?",
    tags: ["Samband", "Ekonomi"],
    answer: "Likviditet handlar om kortsiktig betalningsförmåga, medan soliditet handlar om långsiktig finansiell motståndskraft.",
    why: "Ett bolag kan ha god soliditet men svag likviditet om pengarna är bundna i tillgångar. Ett bolag kan också ha tillfälligt god likviditet men svag soliditet om den bygger på skulder.",
    example: "Essiq AB hade bättre balanslikviditet än Hälsö Fisk AB, men soliditeten behöver ändå läsas separat.",
    related: ["Likviditet", "Soliditet", "Balansräkning", "Kassaflöde"]
  },
  {
    id: "resultat-kassaflode-samband",
    mode: "samband",
    type: "open",
    category: "Ekonomi",
    source: "AM5",
    question: "Varför är resultat och kassaflöde inte samma sak?",
    tags: ["Samband", "Ekonomi"],
    answer: "Resultat visar intäkter minus kostnader enligt redovisningen, medan kassaflöde visar faktiska pengar in och ut.",
    why: "Försäljning kan bokföras som intäkt innan pengarna finns på kontot, och kostnader kan påverka kassan vid andra tidpunkter.",
    example: "Essiq AB gjorde positivt resultat men hade kraftigt minskade likvida medel under 2021.",
    related: ["Resultaträkning", "Kassaflöde", "Kundfordringar", "Likviditet"]
  },
  {
    id: "swot-pestelid-samband",
    mode: "samband",
    type: "open",
    category: "Strategi",
    source: "AM3",
    question: "Hur hänger SWOT och PESTELID ihop?",
    tags: ["Samband", "Strategi"],
    answer: "PESTELID analyserar omvärlden, och resultatet kan användas för externa delar i SWOT: möjligheter och hot.",
    why: "Det minskar risken att SWOT blir en lös åsiktslista utan källor eller analys.",
    example: "AI-regler i PESTELID kan bli ett hot eller en möjlighet i SWOT beroende på bolagets kompetens.",
    related: ["PESTELID", "SWOT", "Omvärld", "Möjligheter och hot"]
  },
  {
    id: "bmc-swot-samband",
    mode: "samband",
    type: "open",
    category: "Modeller",
    source: "AM1-AM3",
    question: "Hur kan BMC och SWOT användas tillsammans?",
    tags: ["Samband", "Modeller"],
    answer: "BMC beskriver affärsmodellen, medan SWOT bedömer styrkor, svagheter, möjligheter och hot kring den.",
    why: "Tillsammans hjälper de gruppen både beskriva idén och pröva om den verkar hållbar.",
    example: "BMC visar att nyckelresursen är M365-kompetens. SWOT kan visa att få referenskunder är en svaghet.",
    related: ["BMC", "SWOT", "Affärsmodell", "Beslut"]
  },
  {
    id: "fab-varde-samband",
    mode: "samband",
    type: "open",
    category: "Erbjudande",
    source: "AM2",
    question: "Hur hjälper FAB dig skriva ett bättre värdeerbjudande?",
    tags: ["Samband", "Erbjudande"],
    answer: "FAB gör att du översätter egenskaper till fördelar och sedan till faktisk kundnytta.",
    why: "Ett värdeerbjudande blir svagt om det bara beskriver vad lösningen innehåller.",
    example: "Power Automate är egenskapen, färre manuella steg är fördelen och snabbare handläggning är kundnyttan.",
    related: ["FAB", "Värdeerbjudande", "Kundnytta", "Erbjudande"]
  },
  {
    id: "5p-bmc-samband",
    mode: "samband",
    type: "open",
    category: "Erbjudande",
    source: "AM2/BMC",
    question: "Hur kompletterar 5P Business Model Canvas?",
    tags: ["Samband", "Erbjudande"],
    answer: "BMC visar hela affärsmodellen, medan 5P hjälper dig konkretisera erbjudandet mot marknaden.",
    why: "5P gör det lättare att diskutera pris, kanal, påverkan och personal, inte bara produkt.",
    example: "BMC säger att bolaget säljer digitaliseringstjänster. 5P gör klart prisform, leveranssätt och kompetensprofil.",
    related: ["5P", "BMC", "Pris", "Kanaler"]
  },
  {
    id: "ansoff-risk-samband",
    mode: "samband",
    type: "open",
    category: "Strategi",
    source: "AM3",
    question: "Varför säger Ansoff något om risk?",
    tags: ["Samband", "Strategi"],
    answer: "Ju mer nytt både marknad och produkt är, desto större blir osäkerheten.",
    why: "Marknadspenetration är ofta lägre risk än diversifiering eftersom företaget redan förstår kund eller erbjudande.",
    example: "Samma tjänst till fler befintliga kunder är normalt mindre risk än ny produkt till helt ny kundgrupp.",
    related: ["Ansoff", "Marknad", "Produkt", "Diversifiering"]
  },
  {
    id: "pris-tb-samband",
    mode: "samband",
    type: "open",
    category: "Ekonomi",
    source: "AM2/AM5",
    question: "Hur hänger pris och täckningsbidrag ihop?",
    tags: ["Samband", "Ekonomi"],
    answer: "Priset påverkar intäkten, och täckningsbidraget visar vad som blir kvar efter direkta kostnader.",
    why: "Ett erbjudande kan kännas säljbart men ändå vara ekonomiskt svagt om priset inte täcker kostnaderna.",
    example: "Om ett fastprisprojekt kräver fler timmar än planerat sjunker täckningsbidraget.",
    related: ["Pris", "Täckningsbidrag", "Direkta kostnader", "Lönsamhet"]
  },
  {
    id: "halsos-fisk-resultat-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "Hälsö Fisk AB",
    question: "Vad säger Hälsö Fisk AB:s resultat om bolagets situation?",
    tags: ["Case", "Hälsö Fisk AB"],
    answer: "Hälsö Fisk AB hade -44 903 kr i resultat efter finansiella poster och årets resultat 2017.",
    why: "Det visar att omsättningen inte räckte för att skapa vinst när kostnader och finansiella poster räknades in.",
    example: "Förvaltningsberättelsen beskriver minskad försäljning och färre kundbesök kopplat till förändringar i Kungälv.",
    related: ["Resultaträkning", "Förvaltningsberättelse", "Omsättning", "Kostnader"]
  },
  {
    id: "essiq-resultat-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "Essiq AB",
    question: "Vad säger Essiq AB:s resultat 2021?",
    tags: ["Case", "Essiq AB"],
    answer: "Essiq AB hade 11 305 793 kr i resultat efter finansiella poster och 7 636 962 kr i årets resultat.",
    why: "Bolaget ser starkare ut resultatmässigt än Hälsö Fisk AB, men resultatet behöver ändå läsas tillsammans med balans och kassaflöde.",
    example: "Essiq beskriver hög efterfrågan, hög beläggningsgrad och rekrytering under året.",
    related: ["Resultaträkning", "Årets resultat", "Kassaflöde", "Beläggning"]
  },
  {
    id: "halsos-fisk-soliditet-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "Hälsö Fisk AB",
    question: "Vad betyder Hälsö Fisk AB:s soliditet på 11 procent?",
    tags: ["Case", "Hälsö Fisk AB"],
    answer: "Den låga soliditeten betyder att bolaget hade en tunn buffert av eget kapital i relation till tillgångarna.",
    why: "Det gör bolaget mer sårbart för förluster eller ytterligare press på försäljningen.",
    example: "Bolaget hade 130 528 kr i eget kapital mot 1 184 841 kr i tillgångar.",
    related: ["Soliditet", "Eget kapital", "Risk", "Balansräkning"]
  },
  {
    id: "essiq-likviditet-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "Essiq AB",
    question: "Vad är viktigt att se i Essiq AB:s likviditet?",
    tags: ["Case", "Essiq AB"],
    answer: "Essiq AB hade cirka 144 procent i balanslikviditet, men den rena kassan var bara 2 822 630 kr.",
    why: "Det betyder att mycket av betalningsförmågan låg i fordringar som måste betalas in för att bli kassa.",
    example: "Omsättningstillgångarna var 70 915 128 kr och kortfristiga skulder 49 244 570 kr.",
    related: ["Balanslikviditet", "Kassa och bank", "Kundfordringar", "Kortfristiga skulder"]
  },
  {
    id: "halsos-essiq-jamfor-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Hur skiljer sig Hälsö Fisk AB och Essiq AB ekonomiskt?",
    tags: ["Case", "Jämförelse"],
    answer: "Essiq AB visar vinst, högre rapporterad soliditet och bättre balanslikviditet. Hälsö Fisk AB visar förlust, 11 procent soliditet och pressad betalningsförmåga.",
    why: "Jämförelsen visar varför man måste läsa resultat, balans, likviditet, soliditet och förvaltningsberättelse tillsammans.",
    example: "Essiqs situation ser mer ut som tillväxt- och kassaflödesstyrning, medan Hälsö Fisk ser mer pressat ut.",
    related: ["Resultat", "Likviditet", "Soliditet", "Förvaltningsberättelse"]
  },
  {
    id: "arsredovisning-metod-case",
    mode: "case",
    type: "open",
    category: "Årsredovisning",
    source: "AM5",
    question: "Hur läser du en årsredovisning snabbt men vettigt?",
    tags: ["Case", "Metod"],
    answer: "Börja med förvaltningsberättelsen, läs resultaträkningen, kontrollera balansräkningen och avsluta med nyckeltal som likviditet och soliditet.",
    why: "Ordningen gör att du både förstår berättelsen och kan kontrollera den mot siffrorna.",
    example: "Hälsö Fisk AB:s berättelse förklarar pressad försäljning; Essiq AB:s berättelse förklarar efterfrågan och rekrytering.",
    related: ["Förvaltningsberättelse", "Resultaträkning", "Balansräkning", "Nyckeltal"]
  },
  {
    id: "grupp-ekonomisk-halsokoll-case",
    mode: "case",
    type: "open",
    category: "Grupparbete",
    source: "Modellverkstad",
    question: "Vad ska en ekonomisk hälsokoll i grupparbetet fånga?",
    tags: ["Case", "Grupparbete"],
    answer: "Den ska fånga resultat, likviditet, soliditet, kassaflöde och hur affärsmodellen påverkar ekonomin.",
    why: "Det gör gruppens bolag mer trovärdigt än om presentationen bara beskriver idé och marknad.",
    example: "Ett konsultbolag kan visa att fastprisprojekt kräver kontroll på timmar, täckningsbidrag och betalningsvillkor.",
    related: ["Resultat", "Likviditet", "Soliditet", "Täckningsbidrag"]
  },
  {
    id: "rebr-case",
    mode: "case",
    type: "open",
    category: "Omvärld",
    source: "REBR 2026",
    question: "Hur kan REBR 2026 användas i affärsresonemanget?",
    tags: ["Case", "Omvärld"],
    answer: "REBR kan användas som extern källa för att styrka trender kring arbetsmarknad, kompetens, attraktivitet och rekrytering.",
    why: "Det gör gruppens resonemang mindre gissningsbaserat och mer förankrat i omvärldsdata.",
    example: "Om caset handlar om IT-konsulter kan rapporten stödja argument om kompetensbrist eller arbetsgivarattraktivitet.",
    related: ["PESTELID", "Omvärldsanalys", "Kompetens", "Employer branding"]
  },
  {
    id: "swot-beslut-case",
    mode: "case",
    type: "open",
    category: "Grupparbete",
    source: "SWOT",
    question: "Hur gör man SWOT användbar i presentationen?",
    tags: ["Case", "Grupparbete"],
    answer: "Avsluta SWOT med ett beslut eller en konsekvens, inte bara fyra listor.",
    why: "Annars blir analysen lätt en sammanställning utan affärsmässig poäng.",
    example: "Hotet större konsulter kan leda till beslutet att börja nischat med förstudier för mindre organisationer.",
    related: ["SWOT", "Beslut", "Differentiering", "Positionering"]
  },
  {
    id: "bmc-roda-traden-case",
    mode: "case",
    type: "open",
    category: "Grupparbete",
    source: "BMC",
    question: "Vad är den röda tråden i BMC för gruppbolaget?",
    tags: ["Case", "Grupparbete"],
    answer: "Kundsegment, värdeerbjudande, kanaler, resurser, intäkter och kostnader måste stödja samma affärsidé.",
    why: "Om rutorna inte hänger ihop ser bolaget konstruerat ut.",
    example: "Små organisationer som kundsegment bör matchas med enkel paketering, rimligt pris och tydliga leveranskanaler.",
    related: ["BMC", "Kundsegment", "Värdeerbjudande", "Intäktsmodell"]
  },
  {
    id: "produktmarknad-beslut-case",
    mode: "case",
    type: "open",
    category: "Grupparbete",
    source: "Produkt-marknad",
    question: "Hur kan produkt-marknadsmatrisen hjälpa gruppen välja idé?",
    tags: ["Case", "Grupparbete"],
    answer: "Den gör det möjligt att jämföra idéer mot marknad, kundnytta, konkurrens, tillväxt och egen kompetens.",
    why: "Det ger ett mer affärsmässigt beslut än att välja den idé som låter roligast.",
    example: "Automationspaket för befintlig målgrupp kan väga starkare än en mer osäker ny produkt mot ny marknad.",
    related: ["Produkt", "Marknad", "Konkurrens", "Ansoff"]
  },
  {
    id: "repetition-start",
    mode: "repetition",
    type: "open",
    category: "Repetition",
    source: "System",
    question: "Vad ska du repetera först?",
    tags: ["Repetition", "Start"],
    answer: "Börja med frågor du själv markerat som Nästan eller Träna igen.",
    why: "Det gör repetitionen mer träffsäker än att läsa allt i samma ordning varje gång.",
    example: "Om du blandar ihop likviditet och soliditet ska de komma tillbaka oftare.",
    related: ["Självbedömning", "Likviditet", "Soliditet", "Träna igen"]
  },

  // ── MC: Ekonomi / Nyckeltal ──────────────────────────────────────────
  {
    id: "mc-soliditet-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter soliditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Hur stor del av tillgångarna som finansieras med kortfristiga skulder",
      "Företagets kortsiktiga betalningsförmåga",
      "Hur stor del av tillgångarna som är finansierade med eget kapital",
      "Skillnaden mellan intäkter och kostnader under en period"
    ],
    correctIndex: 2,
    explanation: "Soliditet = eget kapital / totala tillgångar. Det visar långsiktig finansiell styrka. Alternativ B beskriver likviditet, inte soliditet. Alternativ D beskriver resultat.",
    related: ["Eget kapital", "Balansräkning", "Likviditet"]
  },
  {
    id: "mc-likviditet-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad beskriver likviditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Hur stor andel av tillgångarna som ägs av ägarna",
      "Företagets kortsiktiga betalningsförmåga",
      "Hur lönsamt företaget är på lång sikt",
      "Hur mycket utdelning ägarna kan ta ut"
    ],
    correctIndex: 1,
    explanation: "Likviditet handlar om att kunna betala löpande skulder i tid. Alternativ A beskriver soliditet. Alternativ C och D handlar om lönsamhet respektive utdelning.",
    related: ["Kassalikviditet", "Balanslikviditet", "Soliditet"]
  },
  {
    id: "mc-kassalikviditet-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur beräknas kassalikviditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Omsättningstillgångar / kortfristiga skulder",
      "Eget kapital / totala tillgångar",
      "(Omsättningstillgångar − lager) / kortfristiga skulder",
      "Kassa och bank / långfristiga skulder"
    ],
    correctIndex: 2,
    explanation: "Kassalikviditet exkluderar lagret från omsättningstillgångarna för att visa om kortfristiga skulder kan betalas utan att sälja lager. Alternativ A är formeln för balanslikviditet.",
    related: ["Balanslikviditet", "Likviditet", "Lager"]
  },
  {
    id: "mc-balanslikviditet-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vilken formel beskriver balanslikviditet?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Omsättningstillgångar / kortfristiga skulder",
      "(Omsättningstillgångar − lager) / kortfristiga skulder",
      "Totala tillgångar / totala skulder",
      "Eget kapital / omsättningstillgångar"
    ],
    correctIndex: 0,
    explanation: "Balanslikviditet = omsättningstillgångar / kortfristiga skulder. Den ger en bred bild av kortsiktig betalningsförmåga. Alternativ B är kassalikviditet. Alternativ C och D är inte standardmått.",
    related: ["Kassalikviditet", "Omsättningstillgångar", "Kortfristiga skulder"]
  },
  {
    id: "mc-resultat-vs-balans",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad visar en resultaträkning som en balansräkning inte visar?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Företagets tillgångar vid en viss tidpunkt",
      "Skulder och eget kapital vid årets slut",
      "Intäkter minus kostnader under en tidsperiod",
      "Hur mycket kassa företaget har just nu"
    ],
    correctIndex: 2,
    explanation: "Resultaträkningen visar flödet av intäkter och kostnader under en period. Balansräkningen visar ögonblicksbilden av tillgångar, skulder och eget kapital. Alternativ A, B och D tillhör balansräkningen.",
    related: ["Resultaträkning", "Balansräkning", "Årets resultat"]
  },
  {
    id: "mc-eget-kapital-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur definieras eget kapital?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Pengar som finns på företagets bankkonto",
      "Totala intäkter minus totala kostnader",
      "Tillgångar minus skulder",
      "Aktiekapital plus långfristiga lån"
    ],
    correctIndex: 2,
    explanation: "Eget kapital = tillgångar − skulder, dvs. ägarnas andel i företaget. Alternativ A är bara likvida medel. Alternativ B beskriver resultat. Alternativ D blandar in skulder i eget kapital.",
    related: ["Soliditet", "Balansräkning", "Tillgångar"]
  },
  {
    id: "mc-kassaflode-vs-resultat",
    mode: "samband",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Varför kan ett företag visa vinst men ändå ha dåligt kassaflöde?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Intäkter bokförs när fakturan skickas, men pengarna kanske inte kommit in ännu",
      "Vinst och kassaflöde är alltid samma sak i redovisningen",
      "Kassaflödet räknar bara fasta kostnader",
      "Resultaträkningen visar bara kassa och bank"
    ],
    correctIndex: 0,
    explanation: "Intäkter kan bokföras innan betalning kommit in (t.ex. kundfordringar). Därför kan resultat se positivt ut medan kassan krymper. Alternativ B är direkt felaktigt. Essiq AB visade detta tydligt 2021.",
    related: ["Kassaflöde", "Resultat", "Kundfordringar"]
  },
  {
    id: "mc-tackningsbidrag-formel",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Hur beräknas täckningsbidrag?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Intäkter minus alla kostnader inklusive fasta",
      "Nettoomsättning minus skatt",
      "Försäljningsintäkt minus direkta kostnader",
      "Eget kapital minus skulder"
    ],
    correctIndex: 2,
    explanation: "Täckningsbidrag = försäljningsintäkt − direkta kostnader. Det visar hur mycket ett projekt bidrar till fasta kostnader och vinst. Alternativ A beskriver snarare rörelseresultat.",
    related: ["Intäkter", "Direkta kostnader", "Lönsamhet"]
  },
  {
    id: "mc-debiteringsgrad-def",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad mäter debiteringsgrad i ett konsultbolag?",
    tags: ["Ekonomi", "Konsult"],
    options: [
      "Andelen av omsättningen som går till löner",
      "Andelen av arbetstiden som kan faktureras till kund",
      "Genomsnittligt pris per timme",
      "Andelen av vinsten som delas ut till ägarna"
    ],
    correctIndex: 1,
    explanation: "Debiteringsgrad = fakturerbar tid / total arbetstid. Alternativ C beskriver snittdebitering. Hög debiteringsgrad påverkar direkt intäkter och lönsamhet i konsultbolag.",
    related: ["Snittdebitering", "Lönsamhet", "Beläggning"]
  },
  {
    id: "mc-budget-vs-prognos",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Vad är huvudskillnaden mellan budget och prognos?",
    tags: ["Ekonomi", "AM5"],
    options: [
      "Budget görs efter räkenskapsåret, prognos görs före",
      "Budget är planen i förväg, prognos är en uppdaterad bedömning av utfallet",
      "Budget används bara i aktiebolag, prognos i enskild firma",
      "Budget visar intäkter, prognos visar kostnader"
    ],
    correctIndex: 1,
    explanation: "Budget sätts före perioden som en plan. Prognos uppdateras under perioden när ny information tillkommer. Alternativ A har ordningen bakvänd.",
    related: ["Uppföljning", "Likviditetsbudget", "Lönsamhet"]
  },

  // ── MC: Modeller / Strategi ──────────────────────────────────────────
  {
    id: "mc-bmc-syfte",
    mode: "begrepp",
    type: "mc",
    category: "Modeller",
    source: "AM1/BMC",
    question: "Vad är huvudsyftet med Business Model Canvas?",
    tags: ["Modeller", "BMC"],
    options: [
      "Att analysera externa hot och möjligheter",
      "Att beskriva hur ett företag skapar, levererar och tar betalt för värde",
      "Att beräkna företagets soliditet och likviditet",
      "Att jämföra konkurrenters priser"
    ],
    correctIndex: 1,
    explanation: "BMC ger en helhetsbild av affärsmodellen: kund, erbjudande, resurser, aktiviteter, intäkter och kostnader. Alternativ A beskriver SWOT/PESTELID. Alternativ C är nyckeltal.",
    related: ["Kundsegment", "Värdeerbjudande", "Intäktsströmmar"]
  },
  {
    id: "mc-swot-intern-extern",
    mode: "begrepp",
    type: "mc",
    category: "Strategi",
    source: "AM2/AM3",
    question: "Vilka delar av SWOT handlar om interna faktorer?",
    tags: ["Strategi", "SWOT"],
    options: [
      "Möjligheter och hot",
      "Styrkor och svagheter",
      "Styrkor och möjligheter",
      "Svagheter och hot"
    ],
    correctIndex: 1,
    explanation: "Styrkor och svagheter är interna (inom företaget). Möjligheter och hot är externa (omvärlden). Alternativ C och D blandar ihop intern och extern.",
    related: ["SWOT", "Intern analys", "Extern analys", "PESTELID"]
  },
  {
    id: "mc-pestelid-bokstaver",
    mode: "begrepp",
    type: "mc",
    category: "Omvärld",
    source: "AM3",
    question: "Vad står T för i PESTELID?",
    tags: ["Omvärld", "PESTELID"],
    options: [
      "Tillgångar",
      "Teknologiska faktorer",
      "Täckningsbidrag",
      "Tillväxtmål"
    ],
    correctIndex: 1,
    explanation: "PESTELID: Politiskt, Ekonomiskt, Socialt, Teknologiskt, Ekologiskt/miljö, Legalt, Internationellt, Demografiskt. T = teknologiska omvärldsfaktorer. Alternativ A och C är ekonomiska begrepp.",
    related: ["PESTELID", "Omvärld", "SWOT"]
  },
  {
    id: "mc-ansoff-kvadranter",
    mode: "begrepp",
    type: "mc",
    category: "Strategi",
    source: "AM3",
    question: "Vad kallas strategin i Ansoffs matris när ett företag säljer en ny produkt på en ny marknad?",
    tags: ["Strategi", "Ansoff"],
    options: [
      "Marknadspenetration",
      "Produktutveckling",
      "Marknadsutveckling",
      "Diversifiering"
    ],
    correctIndex: 3,
    explanation: "Diversifiering = ny produkt + ny marknad, vilket är den mest riskfyllda strategin. Marknadspenetration (A) är befintlig produkt + befintlig marknad. Produktutveckling (B) är ny produkt + befintlig marknad.",
    related: ["Ansoff", "Risk", "Tillväxt", "Marknad"]
  },
  {
    id: "mc-fab-delar",
    mode: "begrepp",
    type: "mc",
    category: "Erbjudande",
    source: "AM2",
    question: "Vad står B för i FAB-modellen?",
    tags: ["Erbjudande", "AM2"],
    options: [
      "Budget",
      "Balansräkning",
      "Benefits (kundnytta)",
      "Brand (varumärke)"
    ],
    correctIndex: 2,
    explanation: "FAB = Features, Advantages, Benefits. B står för Benefits, alltså den konkreta nyttan kunden upplever. Modellen tvingar dig att gå från egenskap till kundnytta.",
    related: ["FAB", "Värdeerbjudande", "Kundnytta"]
  },
  {
    id: "mc-5p-delar",
    mode: "begrepp",
    type: "mc",
    category: "Erbjudande",
    source: "AM2",
    question: "Vilka är de fem delarna i 5P?",
    tags: ["Erbjudande", "AM2"],
    options: [
      "Produkt, pris, plats, påverkan, personal",
      "Produkt, pris, plan, process, presentation",
      "Produkt, paketering, positionering, press, personal",
      "Pris, plats, process, promotion, profit"
    ],
    correctIndex: 0,
    explanation: "5P = produkt, pris, plats, påverkan och personal. Modellen ger en helhetsbild av erbjudandet och hur det når kunden. De andra alternativen blandar in begrepp som inte ingår i 5P.",
    related: ["5P", "Pris", "Paketering", "Kanal"]
  },
  {
    id: "mc-bsc-perspektiv",
    mode: "begrepp",
    type: "mc",
    category: "Styrning",
    source: "AM4",
    question: "Vilka fyra perspektiv ingår i Balanced Scorecard?",
    tags: ["Styrning", "AM4"],
    options: [
      "Ekonomi, kund, intern process, lärande och tillväxt",
      "SWOT:s fyra rutor: styrkor, svagheter, möjligheter, hot",
      "Produkt, pris, plats, påverkan",
      "Intäkter, kostnader, tillgångar, skulder"
    ],
    correctIndex: 0,
    explanation: "Balanced Scorecard mäter verksamheten ur fyra perspektiv: ekonomi, kund, interna processer samt lärande och tillväxt. Alternativ B är SWOT. Alternativ C är 5P (minus personal). Alternativ D är redovisningsbegrepp.",
    related: ["Balanced Scorecard", "KPI", "Mål", "Styrning"]
  },
  {
    id: "mc-positionering-def",
    mode: "begrepp",
    type: "mc",
    category: "Erbjudande",
    source: "AM2",
    question: "Vad innebär positionering?",
    tags: ["Erbjudande", "AM2"],
    options: [
      "Att bestämma var kontoret ska ligga geografiskt",
      "Att bestämma vilken plats erbjudandet ska ha i kundens huvud jämfört med alternativ",
      "Att välja rätt position i organisationsschemat",
      "Att placera produkter i butikshyllan"
    ],
    correctIndex: 1,
    explanation: "Positionering handlar om hur kunden uppfattar erbjudandet i relation till konkurrenter. Det är ett strategiskt val om hur företaget vill bli sett. De andra alternativen handlar om fysisk placering.",
    related: ["Differentiering", "Konkurrentanalys", "Värdeerbjudande"]
  },
  {
    id: "mc-konkurrentanalys-syfte",
    mode: "begrepp",
    type: "mc",
    category: "Strategi",
    source: "BMC/PESTELID/SWOT",
    question: "Varför genomför man en konkurrentanalys?",
    tags: ["Strategi", "Konkurrens"],
    options: [
      "För att kopiera konkurrenternas erbjudande exakt",
      "För att räkna ut företagets soliditet",
      "För att förstå vilka alternativ kunden har och hur det egna erbjudandet kan särskiljas",
      "För att bestämma företagets organisationsform"
    ],
    correctIndex: 2,
    explanation: "Konkurrentanalys hjälper företaget förstå marknaden och differentiera sitt erbjudande. Utan den riskerar man att beskriva sitt erbjudande som unikt trots att kunden ser många alternativ.",
    related: ["Differentiering", "Positionering", "Värdeerbjudande"]
  },
  {
    id: "mc-vardeerbjudande-def",
    mode: "begrepp",
    type: "mc",
    category: "Modeller",
    source: "AM2/BMC",
    question: "Vad är ett värdeerbjudande?",
    tags: ["Erbjudande", "BMC"],
    options: [
      "En lista på alla produkter företaget säljer",
      "Den nytta kunden får och varför kunden ska välja just den lösningen",
      "Företagets prislista",
      "En beskrivning av företagets interna processer"
    ],
    correctIndex: 1,
    explanation: "Värdeerbjudandet fokuserar på kundens problem och den nytta som lösningen ger. Det är mer än en produktlista – det förklarar varför kunden ska välja just detta. Alternativ A och C är för snäva.",
    related: ["FAB", "Kundnytta", "Kundsegment"]
  },

  // ── MC: Företagsform / Praktik ───────────────────────────────────────
  {
    id: "mc-ab-vs-enskild",
    mode: "begrepp",
    type: "mc",
    category: "Företagsform",
    source: "Företagsformer 2025",
    question: "Vad är den avgörande skillnaden mellan aktiebolag och enskild firma gällande ansvar?",
    tags: ["Företagsform"],
    options: [
      "I enskild firma har ägaren begränsat ansvar precis som i aktiebolag",
      "I aktiebolag ansvarar ägarna normalt inte personligen för bolagets skulder",
      "Enskild firma kräver högre aktiekapital än aktiebolag",
      "Det finns ingen skillnad i ansvar mellan företagsformerna"
    ],
    correctIndex: 1,
    explanation: "I aktiebolag är ägarna normalt skyddade från personligt ansvar, medan enskild firma innebär att företagaren personligen ansvarar för skulder. Det är den viktigaste skillnaden.",
    related: ["Ansvar", "Aktiebolag", "Enskild firma", "Risk"]
  },
  {
    id: "mc-arsredovisning-delar",
    mode: "begrepp",
    type: "mc",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vilka delar ingår i en årsredovisning?",
    tags: ["Årsredovisning", "AM5"],
    options: [
      "Bara resultaträkning och balansräkning",
      "Förvaltningsberättelse, resultaträkning, balansräkning, noter och ofta revisionsberättelse",
      "Bara budget och prognos",
      "SWOT-analys och konkurrentanalys"
    ],
    correctIndex: 1,
    explanation: "En årsredovisning är ett komplett paket som ger flera perspektiv på företagets ekonomi och verksamhet. Enbart resultat- och balansräkning (alternativ A) räcker inte.",
    related: ["Förvaltningsberättelse", "Resultaträkning", "Balansräkning"]
  },
  {
    id: "mc-forvaltningsberattelse-syfte",
    mode: "begrepp",
    type: "mc",
    category: "Årsredovisning",
    source: "AM5",
    question: "Vad är syftet med förvaltningsberättelsen?",
    tags: ["Årsredovisning", "AM5"],
    options: [
      "Att lista alla anställdas löner",
      "Att beskriva vad som hänt i verksamheten under året och ge kontext till siffrorna",
      "Att visa företagets soliditet och likviditet i diagramform",
      "Att presentera nästa års budget"
    ],
    correctIndex: 1,
    explanation: "Förvaltningsberättelsen ger kontext och förklarar varför siffrorna ser ut som de gör – t.ex. att Hälsö Fisk AB hade färre kundbesök på grund av infrastrukturförändringar.",
    related: ["Årsredovisning", "Resultat", "Omvärld"]
  },
  {
    id: "mc-fast-good-cheap",
    mode: "begrepp",
    type: "mc",
    category: "Erbjudande",
    source: "AM2",
    question: "Vad säger fast-good-cheap-principen?",
    tags: ["Erbjudande", "AM2"],
    options: [
      "Alla tre kan alltid levereras om man planerar rätt",
      "Man kan bara välja en av tre: snabb, bra eller billig",
      "Man kan maximera två av tre men sällan alla tre samtidigt",
      "Principen gäller bara fysiska produkter, inte tjänster"
    ],
    correctIndex: 2,
    explanation: "Fast-good-cheap visar att man kan optimera två av tre men sällan alla tre samtidigt. Om kunden vill ha snabbt och bra blir det sällan billigt. Alternativ A är orealistiskt. Alternativ B är för extremt.",
    related: ["Pris", "Kvalitet", "Leveranstid", "Kundförväntan"]
  },

  // ── MC: Sant / Falskt ────────────────────────────────────────────────
  {
    id: "mc-tf-resultat-kassaflode",
    mode: "samband",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Positivt resultat betyder alltid bra kassaflöde.\"",
    tags: ["Ekonomi", "AM5"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. Resultat baseras på bokförda intäkter och kostnader, men kassaflödet visar faktiska pengar in och ut. Essiq AB hade positivt resultat men kraftigt minskat kassaflöde 2021 på grund av stora kundfordringar.",
    related: ["Kassaflöde", "Resultat", "Kundfordringar"]
  },
  {
    id: "mc-tf-soliditet-kortsiktig",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Soliditet visar kortsiktig betalningsförmåga.\"",
    tags: ["Ekonomi", "AM5"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. Soliditet visar långsiktig finansiell motståndskraft (eget kapital / totala tillgångar). Det är likviditet som visar kortsiktig betalningsförmåga. Studenter blandar ofta ihop dessa begrepp.",
    related: ["Soliditet", "Likviditet", "Eget kapital"]
  },
  {
    id: "mc-tf-pestelid-intern",
    mode: "begrepp",
    type: "mc",
    category: "Omvärld",
    source: "AM3",
    question: "Påstående: \"PESTELID analyserar interna faktorer i företaget.\"",
    tags: ["Omvärld", "PESTELID"],
    options: ["Sant", "Falskt"],
    correctIndex: 1,
    explanation: "Falskt. PESTELID analyserar externa omvärldsfaktorer (politiska, ekonomiska, sociala osv.). Interna faktorer analyseras genom SWOT:s styrkor och svagheter.",
    related: ["PESTELID", "SWOT", "Omvärld", "Intern analys"]
  },
  {
    id: "mc-tf-eget-kapital",
    mode: "begrepp",
    type: "mc",
    category: "Ekonomi",
    source: "AM5",
    question: "Påstående: \"Eget kapital = tillgångar minus skulder.\"",
    tags: ["Ekonomi", "AM5"],
    options: ["Sant", "Falskt"],
    correctIndex: 0,
    explanation: "Sant. Eget kapital är den del av tillgångarna som inte finansieras med skulder. Det är ägarnas kapital i bolaget och fungerar som buffert. Det är inte samma sak som pengar på banken.",
    related: ["Eget kapital", "Tillgångar", "Skulder", "Soliditet"]
  }
];
